### ISSUE TITLE
Is OTP used as a primary authentication mechanism?

### ISSUE THREAD

**Issue by SachiniSiriwardene** [ConsumerDataStandardsAustralia/standards-maintenance#100]
# Description
In the standards, it is advised to not ask for the password from the customer and request the customer to enter just a unique identifier and then use OTP for authentication.
Here, should OTP step be considered as a second factor or is it a part of the primary authentication flow?

**Comment by CDR-API-Stream** [comment]
As no password is request the one-time password should not be considered a second factor.  It is the primary factor and should considered part of the primary authentication flow.

**Comment by SachiniSiriwardene** [comment]
Thank you for the clarification.

**Comment by cdradr** [comment]
Can you clarify what do you mean by “primary authentication flow” vs “2nd factor”? You are not saying that the banks are allowed to share customer data with OTP instead of regular authentication methods???

**Comment by SachiniSiriwardene** [comment]
As mentioned in the CDS, 
`Data Holders MUST request a user identifier that can uniquely identify the customer and that is already known by the customer in the redirected page `
`Data Holders MUST NOT request that the customer enter an existing password in the redirected page`
`Data Holders MUST provide a one-time password (OTP) to the customer through an existing channel or mechanism that the customer can then enter into the redirected page`

What I wanted to clarify is whether we should consider the unique identification of the customer step as the basic authentication mechanism and OTP be considered as a secondary factor for authentication.

**Comment by CDR-API-Stream** [comment]
The standards require authentication to through the use of a user identifier (ie. a username) and a single credential which is a one-time password delivered through an existing mechanism that the customer is familiar with.  This position was the outcome of twelve months of security review and consultation within the Banking sector and considered risks holistically (including the increased risk of phishing that occurs with the use of passwords in OAuth flows).

A change to this position will not be considered at this time.

**Comment by cdradr** [comment]
Thanks for your response @CDR-API-Stream 

Was security review public? Can you please point us to a direction where I can find it.

Are we saying that CDS is replacing existing authentication methods that the banks currently support (passwords, pins, biometric and other methods) with a user identifier and an OTP sent via SMS?

What if my username / user identifier is an email or mobile number (public information)?

Europe is starting to enforce stronger customer authentication and Australia is relaxing it?

Use of SMS is also highly questionable from security point of view.

Who accepts responsibility for data breach and identity theft? Banks? Data61? ACCC? @CDR-API-Stream?

PS what does this mean exactly?

“increased risk of phishing that occurs with the use of passwords in OAuth flows)“

**Comment by CDR-API-Stream** [comment]
Hi @cdradr,
 
Let me answer each question individually.
 
**Re: Security Reviews**
Security reviews have been conducted and they have followed a period of public consultation. You can find the two independent security reviews here: https://consumerdatastandards.org.au/resources/reports/reports-information-security/

**Re: Authentication methods**
- The CDS is not replacing existing authentication methods for banks. The use of the User Identifier and OTP must not be used for logging a customer into any internet banking session. Its use is purely a time-based one time passcode for consent establishment.
- Data Holders may use SMS or other OTP methods such as Email or a secure authenticator app to allow customers to receive and enter a valid OTP. The choices are at the discretion of the Data Holder as are the additional protection methods a Data Holder may put in place to remain within the their security posture.
- The User Identifier must uniquely identify the person however, Data Holders SHOULD implement additional controls to minimise the risk of enumeration attacks via the redirect page

**Re: Data Breach**
It is the responsibility of Accredited Data Recipients and Data Holders to protect and minimise the likelihood of data breaches and identity theft as is common today for internet banking. 
 
**Re: Strong Customer Authentication**
DSB is continually reviewing other methods from strong customer authentication and would welcome proposals from the community.
It is important to note that because the CDR is cross-sector, a baseline security position has been established that can be universally implemented by Data Holders.

**Re: Increased risk of phishing**
As part of consultation with the community, customer username and password is not used as the method of authentication because it conditions consumers to enter a secret (password) within a flow outside a customer’s internet banking channel. This goes against standard security best-practice.

**Comment by cdradr** [comment]
Thanks for the detailed response. We will go through this in the next few days.

Just one quick comment: 

It seams that CDS allows all in scope customer data to be shared for extended period of time by going through the consent flow like this:
1) Customer is redirected from Data Recipient web page to Data Holder web page 
2) Customer enters their email address
3) Data Holder sends 4 digit code to customer’s email.
4) Customer enters this code and the data is gone.

Data holder has fulfilled their obligations... 

Data recipient cannot trust who actually signed in and authorized data sharing. 

Would customer feel secure?

Could you please confirm which security review signed this authorisation flow off?

There is a significant privacy impact here too. Has this flow been assessed by privacy professionals?

**Comment by CDR-API-Stream** [comment]
Hello @cdradr,
 
These questions have been clarified in the previous post. I would direct you to look at the security reports and the CX guidelines to properly understand the considerations for the authentication flow.
 
This issue has now been clarified and will be closed.

**Comment by cdradr** [comment]
May be this information is captured somewhere else, I am a bit late to this discussion.

The security report you mentioned (the older one):
- Does not seem to consider the use of email as OTP delivery mechanism.

- Considers SMS OTP and calls out a risk: “There are security risks associated with this flow due to the use of SMS as an OTP”.

- Does not consider a scenario where no other password or code is verified to allow data sharing.

- Does NOT recommend adopting this ”redirect with OTP” flow.

So this question is still not answered: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/100#issuecomment-582808423.

I would be happy if I missed something here but at the moment this does concern me as a potential consumer. Lack of trust and clarity in the flows will concern data recipients as it threatens adoption and introduce potential breaches. 

PS It looks like quite an old report too.
