### ISSUE TITLE
Links in the Payload - Can this be relative URL ? Or Should it be an absolute URL?

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#111]
# Request For Clarification
The [Payload conventions ](https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions) describe the structure of the payload.

Response which are Http Status code 200  should return _data_ and _links_ 

The links object will contain multiple links of which one is self which must be "absolute" aka Fully Qualified.

What is the expectation on the other links such as in the [pagination](https://consumerdatastandardsaustralia.github.io/standards/#pagination) scenarios.

The specs talk about URI and it does not state about absolute or relative.

The terms absolute and relative may be mis-interpreted. Here is how I am using these terms.

Absolute  URL Example -  https://dataholder.com.au/public/cds-au/v1/banking/products

Relative URL Example -  public/cds-au/v1/banking/products

Looked at one of the big four they are returning absolute URLs. I wanted to see if both are acceptable or is the spec prescribing absolute URL over a relative URL.

**Comment by perlboy** [comment]
[Babelfish-cdr](https://github.com/bizaio/babelfish-cdr) currently enforces all URI's in all payloads to be [non-opaque and absolute](https://github.com/bizaio/babelfish-cdr/blob/develop/src/main/java/io/biza/babelfish/cdr/converters/UriStringToUriConverter.java) and will raise validation errors for payloads which do otherwise.

**Comment by CDR-API-Stream** [comment]
Hi @bmangalaganesh
 
It is expected that the URIs generated by the API should be absolute URIs.
 
The standards have been based on JSONAPI.org which recommends absolute URIs.  

The reason for absolute URIs is mostly for ease of use by the client, so that it never has to find out the correct base URI for a resource, which is needed to interpret a relative URL. This will also provide you with greater control on how you can direct the flow of clients between resources in the future (load balancing, A/B testing, etc.).

**Comment by bmangalaganesh** [comment]
Thanks. This provides the required clarity.
