### ISSUE TITLE
Enhanced error handling Stage 2 delivery risk impact assessment - request for comment

### ISSUE THREAD

**Issue by CDR-AMO** [ConsumerDataStandardsAustralia/standards-maintenance#118]
# Request For Clarification
It is understood that an existing "enhanced error handling" decision [#68](http://github.com/ConsumerDataStandardsAustralia/standards/issues/68) exists within the standards section of CDS github and is currently under discussion regarding potential impact to the CDR Stage 2 production release timeframe (i.e. 1st July 2020).

As such CDR AMO would like to seek feedback from participants regarding the following delivery risk in order to guage if participants: (1) feel the risk is material for them or not; and if material, (2) what is the probability and potential severity of the risk from their perspective.

- **Potential Delivery Risk**: Inconsistent error handling understanding across participants involved in Stage 2 delivery, deployment and transition. In the CDS standards and ACCC Register design there is currrently a likely deficiency of error code detail and/or handling guidance (thus decision [#68](http://github.com/ConsumerDataStandardsAustralia/standards/issues/68) exists) as well as risk of inconsistency in interpretation of implicit* vs explicit** HTTP response error code definitions. As a by-product the Stage 2 industry test scenario coverage may also be put at risk given standards definition is not providing a level of detail that can be confidently translated into a comprehensive set of negative test scenario definitions regarding HTTP response error code handling.

- **Potential Delivery Risk Impact**: May manifest in more industry test defects due to misunderstandings, misalignments and/or clarifications from participants leading to lost effort/time and pressure on Stage 2 go live date. If participants successfully exit test phases with poor/inconsistent error handling solutions (due to light testing quality conditions on error codes as articulated above) then it is possible that the risk impact may expand/materialise further in a range of ways including more issues/incidents during production as well as a potentially disjointed/inconsistent experience for consumers across different participants post go live; in turn this may lead to negative press or social media outcomes for the program and/or specific participants. The hypothesised mechanics for how this delivery risk could manifest itself:

   1. Service Provider (due to potential lack of clarity in standards) chooses what they “think” is the right error code to return to the Service Consumer based on a given negative scenario occurring as well as based on that same understanding/interpretation the Servicer Provider chooses what they “think” is the right handling/processing approach for that error within their organisation and assocaited systems which may be unique/inconsistent compared to the approach taken by other service providers
   2. Service Consumer (due to potential lack of clarity in standards) may both; 
      * Receive inconsistent error code responses from Service Provider A vs Service Provider B for the same API and negative scenario trigger; and,
      * Based on the Service Consumer’s understanding/interpretation of a given error code returned by a Service Provider, the Service Consumer chooses what they ‘think’ is the correct handing/processing for that error within their organisation/systems which may be unique/inconsistent with other service consumers
   3. Materiality/severity of this particular risk’s impact is likely to scale commensurately with the amount of in-scope Stage 2 APIs shared across the set of service providers and consumers involved in the ecosystem; thus the risk for Stage 2 may be significant given volume of unique API combinations across DH, DR and Register acting as either service provider or service consumer even if the number of participants is rather contained
    4. The “choice” of error codes as well as handling/processing approach per error code on both service provider and service consumer sides may translate into inconsistent and/or confusing consumer experience journeys during negative scenario flows 

_* There is a set of **implicitly defined HTTP response error codes** at the RESTful HTTP API type (i.e. GET, POST, DELETE) level in CDS standards [HERE](http://consumerdatastandardsaustralia.github.io/standards/#http-response-codes) (HTTP response codes) 
** There is a set of **explicitly defined HTTP response error codes** and to date there appears to be some feedback that implicit vs explicit positions in the standards may not be matching. e.g. Banking API section for Get Accounts [HERE](http://consumerdatastandardsaustralia.github.io/standards/#get-accounts) has no error code explicitly defined, however as a GET type API according to [HERE](http://consumerdatastandardsaustralia.github.io/standards/#http-response-codes) (HTTP response codes) the Get Accounts should be able to return a 422 error code_

**Comment by WestpacOpenBanking** [comment]
The standards as written allow for differences in the expected behaviour of data holder implementations. This approach is not unique to the Australian standards – the normative references in the security profile and the UK open banking standard all allow for significant flexibility in error scenarios. We believe that a degree of flexibility is needed for the standards to remain unambiguous, implementable and maintainable. This is because different data holders have different architectures, implementations and underlying data sources.  Forcing consistency, especially in edge cases, may incur significant reimplementation effort and additional solution complexity with little benefit to customers or data consumers. We especially do not recommend specifying error scenarios in the information security profile beyond the normative references as this may be incompatible with pre-existing commercially available implementations.

We welcome articulation of scenarios where further specification of error codes and HTTP headers will result in improved customer experiences. These scenarios may become evident if future versions of the CX standards address error scenarios in the consent flow or in other scenarios articulated by data recipients. In these cases the standards would need to be worded carefully to avoid ambiguities in edge cases. In particular we would recommend for a significant portion of cases that the MUST keyword RFC2119 is only used to specify errors at a limited level of granularity and that specific error messages should make use of the SHOULD keyword (e.g. “In the case of xyz error scenario, then the server MUST return a 4xx HTTP response code and SHOULD return a 415 HTTP response code…”).

**Comment by mattp-rab** [comment]
We can already see how misalignment of error code expectations can create false positives and false negatives causing lengthy adjudication processes. The error codes themselves are not as material as the confidence of standardisation. As a Data Recipient, we want the confidence that our implementation will work consistently against all Data Holders without false negatives or positives.

Having said that, the practical severity of the issue is, at this stage, minimal as there is only four Data Holders. The severity will increase with other ADIs becoming Data Holders within the ecosystem and the scenarios as described are more likely to manifest.

If unpredictable behaviour does eventuate as a result of inconsistent error responses from DHs then there is real risk of reduced consumer and participant confidence in CDR. 

@WestpacOpenBanking, if error responses were to become more explicitly defined I don't think needing to conform to existing behaviour of commercial products trumps needing to conform to the CDR specs. I've probably misinterpreted something (haha!), but I'm also confused how being more explicit would result in ambiguity.

A lot of the foundation standards (e.g. OAuth2 RFCs) of CDR explicitly mandate certain error responses, so it is likely a matter of the standards forming an adjudication of explicit error responses based on a foundation spec or otherwise.

This is a good example of the need for a conformance suite. A conformance suite would automatically test for expected responses to various conditions to ensure the API provider is conforming to the standards. One was talked about last year, but seemed to fizzle out. Any word on one being developed & maintained???

**Comment by NationalAustraliaBank** [comment]
NAB acknowledges the current standards around error handling may result in an inconsistent experience for DR’s across all data holders, however we believe trying to iron out all inconsistencies at this stage would be time consuming and would introduce changes to the standard and risk the July release. We believe there is enough guidance within the standards to result in a serviceable outcome. Multilateral testing should prove this out and/or at least provide a focus on where/if there are any fundamental issues.

**Comment by perlboy** [comment]
Seriously, delivering a poor quality outcome timeline is of little value to the ecosystem. Holding a timeline hostage because people can't sit down and work through at least a modicum of normalisation for errors is both unhelpful and counterproductive.

@mattp-rab The D61 Engineering team is effectively disbanded. There is one person left reporting to the API and InfoSec Lead delivering outputs unknown.

FWIW, Biza.io has been developing assets for end to end conformance for some time starting with [babelfish-cdr](https://github.com/bizaio/babelfish-cdr), progressing to [Deep Thought](https://github.com/bizaio/deepthought) and soon Sens-o-matic. We have made it known, repeatedly, to the government that we have been developing these but thus far have received radio silence. Presumably they will be paying a bunch of Big Co's to do something eventually....

**Comment by bazzat** [comment]
@perlboy I think you need to re-read the [GitHub Community Forum Code of Conduct](https://help.github.com/en/github/site-policy/github-community-forum-code-of-conduct). The section under "Contribute in a positive and constructive way" particularly springs to mind. A couple of highlights - "_Be respectful of the topics and the people discussing them, even if you disagree with some of what is being said_" and "_don't post unsolicited links to your own projects or sites on other user's threads._"

**Comment by perlboy** [comment]
Hi @bazzat, I'm _positive_ that the error codes should be clarified and the links I provided were _shared with the intent of providing relevant and appropriate information_.

**Comment by CDR-API-Stream** [comment]
Thanks @CDR-AMO and everyone for their feedback.

- Based on consultation enhanced error handling was not included in the scope of the current maintenance iteration 
- Enhanced error handling is on the roadmap for the CDS however the current working assumption is that this work would benefit from reviewing implementations of the CDR before being more prescriptive
- We would welcome feedback from the community when they would like to see this consulted on and introduced - for instance, should new standards be enforceable for the November compliance timeframes or the non-majors' Feb/July timeframes?
- Being specific in the error scenarios to be addressed would also be welcomed

**Comment by spikejump** [comment]
As a DR participating in the initial CDR go-live program, we would like to put forward the issues we're seeing in the ecosystem due to lack of clarity on Error Codes/Error Responses and how they impact DRs.

The CDS spec, in the latest 1.2 version, has a section on HTTP Response Codes.  In this section, it generically defines the possible status that can be encountered in the CDR ecosystem and how they can occur.  There is a Notes column that further clarifies the error condition.  In only two of the error codes, 403 and 422, the Notes column specifies that the error will result in an error payload that is the CDS defined [ResponseErrorList](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponseerrorlist).

Looking at the Banking APIs, there are very few APIs with any of the HTTP error status code defined in the Response Headers section.  Only 3 of the 17 defined APIs have specific mention of a HTTP error status code.  Speficially, [Get Balances for Specific Accounts](https://consumerdatastandardsaustralia.github.io/standards/#get-balances-for-specific-accounts), [Get Direct Debits For Specific Accounts](https://consumerdatastandardsaustralia.github.io/standards/#get-direct-debits-for-specific-accounts) and [Get Scheduled Payments For Specific Accounts](https://consumerdatastandardsaustralia.github.io/standards/#get-scheduled-payments-for-specific-accounts).

From our experience, any REST APIs need to clearly define the errors that they can return.  This allows the client side to predictably handle error scenarios appropriately.  In addition, there can only be one error response object returned per API.  Again, this allows the client to process the error appropriately.  CDS APIs has not clearly delivered on both fronts.

The lack of clarity of what HTTP status code should be returned for what kind of error has resulted in many back and forth iteration beteween DRs and DHs including ACCC and DSB involvement.  While it is acknowledged across the ecosystem the status code can be better defined the advise DRs have received is to treat all 4xx errors on an equal footing.  So what is the issue with this?  This issue is the DRs can't deal with errors succinctly and accurately.  For example, a DR getting a 400 knows it somehow screwed up with the request; getting a 401 probably means the credentials used was somehow wrong; 403 probably means DR needs to have a chat with DH to further understand the cause.  Each of these errors need to be handled differently on the DR side.  Without the ability to triage them systematically DRs abililty to provide the best experience/service for customers is impacted.

The fallout from lack of clarity on the error response payload is also interesting.  DRs are currently facing the challenge of dealing with two or more error response payloads.  First, there is the CDS defined [ResponseErrorList](https://consumerdatastandardsaustralia.github.io/standards/#tocSresponseerrorlist).  Natural assumption is all errors that can be returned from Banking APIs will be of this form.  However, only error codes 403 and 422 says ResponseErrorList needs to be returned.  During testing, we have come across error responses that conform to OAuth2 style for the Banking APIs.  For example, while DH validates a Bearer token to be invalid a 401 is returned with a response payload of { "error":"xxxxx" }.  The justification of an OAuth2 error payload is because this error occurred while processing is at the OIDC layer.  While this may seem acceptable, what happens when a DH is validating the required `x-v` HTTP header, should this result in 400 and a CDS ResponseErrorList payload?  What about validating '`content-type: application/jwt`' when `application/json` is received?  Should an error of 400 with another form of error response be returned?  Where does this stop?

At this point in time, DRs have been advised that DHs need to return whatever code/response payload that's defined in the CDS spec as long as they're spelled out.  (Very little is spelled out currently as mentioned above.) Implication is DHs can return any error codes/response payload they see fit when the spec does not spell it out.  This means the DRs needs to deal with all kinds of unknown; DRs can't predictably process errors properly until DR come across such an error.

While we acknowledge clearly defining error codes/responses is a challenging task, it is critical to recognise software can't function appropriately when the underlying specification lacks clarity.

**Comment by cdradr** [comment]
Let’s just not make any mistakes and hope for the best. Then we don’t need any error codes beside 404, 500 and 418.

Seriously, error handling is one of the key design principles for distributed systems: 
- "You have to design distributed systems with the expectation of failure.”
-“ Explicitly define failure scenarios and identify how likely each one might occur. ”

Data Recipients will suffer if error handling is not consistent between Data Holders, End users will suffer (possibly even financially), Data Holders will be impacted if the have to fix this later. Full CDR ecosystem will have a limited value after millions of dollars spent.

**Comment by cdradr** [comment]
One of many examples: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/174

**Comment by ryderwj** [comment]
Similar to #174  I note difference in implementation choices for error handling when an invalid page filter is supplied to the GetProducts operation, returning either a 200 OK with empty response or a 4xx error.  While this example is not likely to be a significant issue, on some other API operations having different behaviour for the same error situation will make it difficult for consumers - particularly as the DH ecosystem grows.

While identifying and standardising every possible error scenario is not realistic, is there an opportunity with [https://github.com/ConsumerDataStandardsAustralia/standards/issues/68](url) (which I note is now being considered for attention in [https://github.com/ConsumerDataStandardsAustralia/standards/issues/108](url) to define the expected http responses against each API/operation individually and where common and likely error scenarios can occur at an operation level, look to standardise the error codes presented for these in some way?

**Comment by Michael-Backhouse** [comment]
Just adding feedback from our developers - having errors explicitly listed in the openAPI spec, would be helpful as it removes ambigiouity - special mention was given to 404, when a resource does not exist.  From a recipient viewpoint, when having to aggregate across hundreds of endpoints, if error codes/endpoint behaviour differs, this is going to be an implementation and maintenance nightmare.

**Comment by perlboy** [comment]
@Michael-Backhouse of course it will be. I reiterate again that this issue was raised as [internal DSB tickets](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/3) as early as **25 January 2019**. Adding to swagger definition was dismissed as "They are common" and "Swagger does not represent the standard". That latter definition has been trotted out a few times since. It'd be great to say this wasn't predicted but it most definitely was. 

I'm glad it's now being prioritised in https://github.com/ConsumerDataStandardsAustralia/standards/issues/108 but between this ticket,  https://github.com/ConsumerDataStandardsAustralia/standards/issues/99 and the fact the cycle is defined as 8 weeks ([against Biza's suggestion](https://github.com/ConsumerDataStandardsAustralia/standards/issues/84#issuecomment-529258963)), putting best case of a revised spec at June 1, the Australian government seems to have successfully kicked an own goal with respect to it's timelines and a July launch date.

I hope it is something they learn from but I'm dubious.

**Comment by nils-work** [comment]
Version 1.10.0 of the Standards incorporated enhanced error handling as a result of the consultation and decisions outlined in [DSB Item - Enhanced error handling](https://github.com/ConsumerDataStandardsAustralia/future-plan/issues/9).
