### ISSUE TITLE
Changes to Authorised Accounts Associated to an Active Consent

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#126]
**The Issue**

- The CX Guidelines v1.2 pg.111, Guideline 1 says: “It is at the discretion of data holders to provide functionality to add/remove additional accounts from the data sharing arrangement.”  This guideline means customers can login to the bank and add/remove accounts from consents that they have already established.
- The consent under CDR is now mutable post original consent.
- CDR does not support a mechanism for DH to notify the DRs of the change.

**Impact to Customers**

- Customers may add/remove accounts to/from an existing consent.
- DRs will not know of the change until an explicit look up of available accounts is done.
- After consent changes, the consent dashboards are essentially out of sync between the DH and DRs (as DRs are not aware of the changes).
- Misaligned information in dashboards may lead to confusion and trust issue with customers.
- When a previous connection to an account is lost, DRs have to notify customers to fix their connections.  This results in bad consumer experience.  (The fix may or may not be straightforward depending on use-cases at the DRs.)

**Request**

Given the ecosystem is trying to reach the milestone of Jul 2020 and this issue may have a significant implications to customer experience, we'd like to request for consideration to limit the ability to change accounts that are associated to an active consent post initial authorisation for July 2020 until proper analysis and impact can be done.  A potential solve may be related/dependent on concurrent consent, fine grained consent, renew/revise of an active consent etc.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump, accounts are not part of consent, they are _associated_ to the consent. As such the consent remains immutable.

Issues #117 and #131 are a good overview of the considerations you raise. Currently it is at the discretion of a Data Holder whether accounts can be changed for an existing consent as opposed to revocation. There are many valid business reasons why accounts may not be available for a period of time during an active consent's sharing duration.

**Comment by cdradr** [comment]
What is the reason for accounts not being a part of consent? As far as the customer concerned they should be, right?

**Comment by spikejump** [comment]
#117 arises because DH allows authorised accounts to be changed post consent.  This can be avoided.
#131 arises due to joint account.  There does not seem to be a concrete approach/solution from CDS perspective.  Our understanding is a complete solution will be in the near future for CDS.

Without doubt, if authorised accounts were changed post consent, confusion will arise with customers.  DRs need to introduce ways to deal with it in software as well as operational procedures.  One of the hard questions that DR will need to answer as an example, is did the customer really intend to remove the account from consent? What if it was **_unintentional_** and the DR now **delete** the previously consumed CDR data and its derived data which causes **irrecoverable** damage to customer's service at the DR?

Given the target state of concurrent consent is in consultation (#99), fine grained control is being requested by the community, and joint account solution will be worked on as well, it seemed prudent to temporarily pause the change of authorised accounts post consent for the July 2020 milestone.

**Comment by cdradr** [comment]
Agree with @spikejump suggestion to remove account list change on Data Holder side until proper consent design is implemented.

Any update on our query above @CDR-API-Stream?

**Comment by JoyceZ-collabZone** [comment]
Totally agree with @spikejump .

**Comment by CDR-API-Stream** [comment]
Hi @spikejump the capability for DHs to offer account selection after-consent in their DH dashboard has been in the CX Guidelines since September 2019 and is not intended to be revisited at this stage. 
 
> The CX Guidelines v1.2 pg.111, Guideline 1 says: “It is at the discretion of data holders to provide functionality to add/remove additional accounts from the data sharing arrangement.” This guideline means customers can login to the bank and add/remove accounts from consents that they have already established.

Noting that implementation for adding and removing accounts post-consent is at the discretion of the Data Holder some Data Holders may not offer this service to their customers.

There are many valid reasons that accounts are associated to consent and not expressly part of the immutable consent arrangement. Consumers using the DH dashboard to manage which accounts they share is one example, however there are other reasons that the accounts may be available or unavailable, such as:
	
* DHs can offer more flexible solutions to allow consumers to opt-in new accounts as they are opened, 
* Joint accounts may be pending authorisation of the second joint account holder,
* An entitlement of the account may not be met, in which case the account will not be returned where previously it was. These reasons will depend on the business logic of the data holder but they may include customer vulnerability statuses, fraud and KYC statuses and so forth
* An account has been closed more than 24 months before the data request

As a result, ADRs cannot rely on the original list of accounts that were elected to always be available. Vice versa, ADRs may gain access to more accounts over time if consumers choose to opt-in or elect additional accounts. 
 
> The consent under CDR is now mutable post original consent.

Accounts are associated to consent so consent would still be immutable.
 
> CDR does not support a mechanism for DH to notify the DRs of the change.

The ADR can, at any time, call Get Accounts to get a list of the available accounts provided the consumer has consented to sharing account data. If an ADR chose simply to request account data for a given accountId, it will receive an error clearly indicating that the account is invalid. If there is a view that knowing whether the account is invalid because it is no longer elected for data sharing versus invalid for other reasons, this can be considered under the current Enhanced Error Handling consultation.
 
 > Without doubt, if authorised accounts were changed post consent, confusion will arise with customers. 

In the situation described, the consumer is expressly managing which associated accounts will be shared so the argument of confusion on the consumer's part is minimised. For joint account scenarios this would be catered for via the consumer's DH dashboard. For other reasons account data is not disclosed, there would be an expectation this would align to the DH's existing digital banking practices.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
