### ISSUE TITLE
Clarification on Joint Account Election Revoke and Consent

### ISSUE THREAD

**Issue by Randima-ibm** [ConsumerDataStandardsAustralia/standards-maintenance#131]
We are seeking clarification on Joint Account Election Revoke process and impact of the same to  Authorizations to disclose (consent) active for the Joint Account:

Assume a scenario where an election(jointly together) is already provided for a Joint Account to expose CDR data for  each of the account holders.
In accordance to that election, one of the account holder(A) has already provided authorization to disclose the CDR data for the joint account.

While this authorization to disclose (consent) is in place, if account holder(B) decided to revoke the election on joint account, should the authorizations to disclose (consent) for the joint account should automatically revoke too?

CDR rules 4.2 (1) (b) reference,
_(b) by either of the joint holders individually to revoke, to the satisfaction of the data holder, such an election._

CDR rules 4.2(4) reference,
_(4)  If an election is made on a joint account management service, the data holder must give effect to the election as soon as practicable._

**Comment by CDR-API-Stream** [comment]
Hi @Randima-ibm please see #117 for further clarification on the relationship between consent and accounts.

If, as you say, account holder B revokes their election to share the joint account, then it is no longer entitled to be shared by account holder A. The joint account is now _disassociated_.

Account holder A's consent is still valid and any subsequent data sharing request would respond with account data related to their remaining associated accounts.

A data holder may wish to notify one or both joint holder parties of the change is accounts that will be disclosed for associated consents.

In summary: A change in the availability of an account for sharing (for instance, by a change in election via the Joint Account Management service described in the rules) does not effect the lifecycle of the consent itself.

---

If we use an example, let's call our joint account holders Alice and Bob.

Alice has consented to share her data from data holder, _FriendlyDH_, with an ADR application, _HappyADR-app_. Her consent receipt is represented as ``consent_abc`` and is _associated_ with three accounts ``{account-123, account-345, account-567}`` (pretend these account identifiers observe Permanence ID rules).

In this example, ``{account-567}`` represents the joint account which Bob has previously elected to share if Alice establishes consent with an ADR. Let's express this as ``sharing_election[Bob] = {account-567}``

Current state: 
```javascript
consent_abc.customer = "Alice"  
consent_abc.adr_software_product = "HappyADR-app"  
consent_abc.data_holder = "FriendlyDH"  
consent_abc.associated_accounts = ["account-123", "account-345", "account-567"]  
consent_abc.getAccount("account-567").sharing_elections = [{"party": "Bob", "election_status": "true"}]  
consent_abc.listShareableAccounts() = ["account-123", "account-345", "account-567"] 
```

_HappyADR-app_ requests data from _FriendlyDH_ on behalf of Alice and will receive account data for ``{account-123, account-345, account-567}``.

Bob now chooses to revoke his election for ``account-567``.  After revocation of election:
```javascript
consent_abc.customer = "Alice"  
consent_abc.adr_software_product = "HappyADR-app"  
consent_abc.data_holder = "FriendlyDH"  
consent_abc.associated_accounts = ["account-123", "account-345", "account-567"]  
consent_abc.getAccount("account-567").sharing_elections = [{"party": "Bob", "election_status": "false"}]  
consent_abc.listShareableAccounts() = ["account-123", "account-345"] 
```

_HappyADR-app_ requests data from _FriendlyDH_ on behalf of Alice and will receive account data for ``{account-123, account-345}`` **only**.

**Comment by cdradr** [comment]
> HappyADR-app requests data from FriendlyDH on behalf of Alice and will receive account data for {account-123, account-345} only.

At this point HappyADR is transitioned to UnhappyADR because they don’t understand why they receive less transaction data, customer is unhappy because they are now being misled by their UnhappyADR-app. Or both customer and UnhappyADR are unaware of this change 

Customer was already unhappy before because of the unnecessary friction introduced by this joint account election process which, by the way, causes significant drop out for UnhappyADRs....

Seriously, can @CDR-API-Stream please explain why we have this account association instead of accounts being a part of consent? We have asked this question before and it hasn’t been answered.
If there are valid reasons we would like to understand them. https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/126

Secondly, why do we need this joint account election process instead of either allowing customer to share their accounts (joint or not) without explicit permission of a joint account holder (notification is possible). Alternatively, we could adopt real-time capture of joint account consent not to disrupt authorisation UX. 

Similar discussion: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/117

We hope https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/99 will provide a pathway forward.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
