### ISSUE TITLE
Account Status when Frozen

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#133]
# Request For Clarification
Accounts enter Frozen/Suspended status on a somewhat irregular basis. The `BankingAccount` has an `openStatus` of `CLOSED` and `OPEN`. How (or maybe If?) should frozen/suspended accounts be presented?

**Comment by CDR-API-Stream** [comment]
Hi @perlboy, good question.
 
The frozen and suspended statuses are specific situations where there are consumer considerations to take into account. Because those statuses often have a negative implication for the customer, those statuses are not included in the standards.
 
Instead, there are a few considerations to take into account:

- The treatment of accounts in these states should be consistent with the Data Holder’s existing channels (e.g. internet banking)
- A consumer’s privacy should be safeguarded
- The Data Holder should have safeguards not to leak sensitive information in this regards (say, an account has been frozen due to AML/CTF breaches)
- There is discretion for the Data Holder whether or not to block returning data for these accounts when an ADR request is received
 
If a Data Holder decides to block an account they may cease to make it available via the CDR if this is consistent with their other channels. 
 
In this instance, it will appear to the ADR as if the account had been removed from the consent and, importantly, the reason will not be exposed.

**Comment by perlboy** [comment]
Hi @CDR-API-Stream, thanks for the detailed response, very valid points given. With further thought there are a number of good reasons why Holders may not want or not authorised to disclose an account status other than those listed. Data Recipients do however need a "signal" to indicate that it's "not you it's me" when making calls. 

Consequently perhaps further guidance could be provided in the Standards regarding the following statements:

- From `BankingAccount` `openStatus`: _Open or closed status for the account. If not present then OPEN is assumed_ could perhaps be altered to something along the lines of _If not present then the previous state is assumed, if this is the first request OPEN is assumed_. This would allow Holders to omit `openStatus` entirely in situations where the account is neither `OPEN` nor `CLOSED` while providing Recipients guidance on whether to specifically register a state change.
- For `GET /banking/accounts/{accountId}` (and others involving `{accountId}`) introduce a `422 Unprocessable` response that allows a Holder to indicate that while a Consent exists it is unable to disclose for business reasons it cannot provide further clarity on. Essentially "we understood your request but a business rule stops us proceeding". This way a Recipient can understand that they haven't done anything wrong but the data is unavailable right now.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

No further response received on this although there is discussion relatted to status codes ongoing. Closing.
