### ISSUE TITLE
Clarification of admin/metrics as they apply to public API's and timing

### ISSUE THREAD

**Issue by markt-amp** [ConsumerDataStandardsAustralia/standards-maintenance#136]
Hi Team,
With respect to the returned data from the response metrics list - do the below apply to public product API’s? 

If so, is this from launch of public product API's or a later date? What is the reporting window?
We're asking in case we need to capture metrics early on

Endpoints - admin/metrics
Schema: https://consumerdatastandardsaustralia.github.io/standards/#tocSresponsemetricslist
•	Availability
•	Performance
•	Invocations
•	averageResponse
•	averageTPS
•	peakTps
•	errors
•	rejections

Any insight would be greatly appreciated
Best
-Mark

**Comment by CDR-API-Stream** [comment]
Hello @markt-amp yes metrics apply to all product reference data (PRD) endpoints. The only metrics that do no apply to the unauthenticated endpoints are rejections, sessionCount, customerCount and recipientCount. Those metrics are related to consumer requests.

In your list, rejections is not required for the PRD endpoints.

**Comment by markt-amp** [comment]
@CDR-API-Stream - great thank you - in terms of the reporting window the rules stipulate 12 months after launch...can we get confirmation of this?

**Comment by CDR-API-Stream** [comment]
This would need to be posed to the ACCC as it is a rules interpretation question.

**Comment by nils-work** [comment]
Hi @CDR-API-Stream 

Could you please clarify why rejections of PRD requests are not required for reporting in the Get Metrics endpoint?
https://consumerdatastandardsaustralia.github.io/standards/#get-metrics
https://consumerdatastandardsaustralia.github.io/standards/#reporting-requirements

Unauthenticated endpoints appear to have stated thresholds -
https://consumerdatastandardsaustralia.github.io/standards/#traffic-thresholds

Get Metrics includes a section for the number of calls rejected due to thresholds -
https://consumerdatastandardsaustralia.github.io/standards/#tocSrejectionmetrics

Thank you

**Comment by CDR-API-Stream** [comment]
Hi @nils-work 

The reason why rejection counts don’t apply to public APIs including PRD is for a few reasons:
1. Rejection counts are most important where a request to access consumer data is denied.
2. Because there is no granular reporting of rejections per API, if rejections for public data were counted they would significantly outweigh the rejections for authenticated data. This may obscure any more important issues such as banks rejecting requests based on a business rule or affecting the service of a use case.
3. Typically the infrastructure used for public APIs will be different to what the DHs use for authenticated APIs. This may include Content Delivery Networks (CDNs) outside the DH’s core infrastructure and reporting on rejections may not be visible to them.
 
That being said, 
* all banks should expect to keep details on rejections regardless of the API because the ACCC may choose to ask for this evidence via the periodic reporting forms. This may also involve breaking down the types of reasons for rejections.
* the NFRs are still applicable, it is simply that they are not counted for **public APIs** within the Get Metrics response

If participants believe there is value in reporting on public API rejections the DSB is open to change requests such as separately reporting on rejections by endpoint/reason/public vs authenticated.

**Comment by nils-work** [comment]
Thanks @CDR-API-Stream that makes sense in the context of your point 2. 
Would it be worth highlighting the above clarification/exception to the standards to ensure consistent interpretation across data holders?

**Comment by CDR-API-Stream** [comment]
Hi @nils-work yes, that would be reasonable. Further clarification will be included into the standards.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
