### ISSUE TITLE
At Cost Fees in Product Reference Data

### ISSUE THREAD

**Issue by DG-TMBL** [ConsumerDataStandardsAustralia/standards-maintenance#161]
This is a question for Weekly Data Holder meeting agenda.

The Consumer Data Standards do not appear to address at cost fees.  The standard requires that an amount in the form of an amountstring is provided – which means we need to enter an amount.

At cost fees are fees that do not have standard amounts associated to them.  They are calculated based on individual circumstance, and may vary significantly for different scenarios.

We have consulted various channels for direction on this, and received various advice.

•	One suggestion is using a $0.00 amount for At Cost Fees, and then explaining the fee in the additional information section.  We feel that this approach is misleading, as it could be misinterpreted by a person that the fee was in fact $0.00 and would not be charged.  Note:  It appears that is what ANZ Bank have done with their product reference data (i.e. using $0.00 and explaining in the additional info section).
•	Another suggestion is using a “typical” or average amount for At Cost Fees, and then explaining the fee in the additional information section. We feel that this approach is misleading, as it could be misinterpreted by a person that the fee was in fact that typical amount, when more likely they would be charged something else.  We also don’t know how we could come up with a typical amount for some fees such as "break cost" on a fixed loan.
•	An alternative is to not disclose fees in the Fee section, and then refer to our websites via the URI links.  This reduces the risk to our organisation, and while it may meet our obligation under the rules and the standard, it is not aligned with the intent of the rules, which is to help with product comparisons.  Referring to our website for fees will not help product comparisons.

Can we have the standard changed, so that "at cost" fees can be disclosed clearly and without risk of misleading the consumer?

**Comment by nils-rbal** [comment]
We have a similar situation where fees may be calculated or otherwise variable according to context.

An example is for early withdrawal from a term deposit, where a fee may be based on the time elapsed and amount of interest already paid against the agreed term. 
I imagine this may be the intention of 'accruedRate', but the rate is not fixed.

A $0 amount or 0% rate doesn't seem to be accurate and additionalInfo may not be presented in a sufficient way to act as a 'disclaimer' where more information would support that placeholder value.

Could an option be to add a new feeType enumeration like 'CALCULATED' and have the Description for amount changed to -
'The amount charged for the fee. One of amount, balanceRate, transactionRate and accruedRate is mandatory **unless feeType is CALCULATED**'

**Comment by DG-TMBL** [comment]
The suggested change from nils-rbal would suit our requirements.

How do we make this a change request please?

**Comment by CDR-API-Stream** [comment]
To raise this as a change request create a new issue using the change request issue template and document the specific change requested.  You can also link to this issue for context (but please do be specific of the change proposed inline in the new issue).

**Comment by CDR-API-Stream** [comment]
Noting that change request #168 has been raised and adopted accordingly. This issue has been answered and it is being closed accordingly.
