### ISSUE TITLE
Clarification of the intent of ProductName on BankingAccount response

### ISSUE THREAD

**Issue by Susan-CDR** [ConsumerDataStandardsAustralia/standards-maintenance#165]
The BankingAccount Response has a DisplayName and a ProductName field. If DisplayName is what the customer sees in their online channels what is the point of the ProductName field (akin to model number?). Our core system product names will have no meaning to any consumer of the data and may just be confusing to the consumer as they will be similar but different. Can we populate both fields with the Product Name that the customer usually sees?

**Comment by CDR-API-Stream** [comment]
**Product Name:** In effect, the Product Name is the model number or model name of the product. It isn't intended to be displayed to the customer but it is useful for the data recipient to correlate similar types of accounts and products.

**Display Name:** On the other hand, the display name is the human-readable text the bank would define and would show customers to recognise an account. For example "Everyday Savers Account", "First Home Buyers Fixed Loan" or "Access Advantage Account".

**Nickname:** The nickname is an alternative that the customer would choose to recognise a particular account. For example "My Splurge Account", "Jack and Jills Travel Saver", "Daily Expenses".

---
During the initial consultation for product data there was discussion about the Product vs Product ID and the idea of a Product Reference Data ID being able to be tracked back to a particular product. Because instantiated products can exist for 30 years or more - say in the case of a home loan - there isn't necessarily a time limit on the account. However the product on the market may no longer exist and may not have existed for decades.

Nevertheless that doesn't preclude the need for a unique identifier when talking about a particular type of account that denotes what that account type is as defined by the bank. This is the purpose of the Product Name.

**Comment by CDR-API-Stream** [comment]
Hi @Susan-CDR  if there are no more questions related to this query it will be closed in 7 days.

**Comment by CDR-API-Stream** [comment]
Hi, we've captured this in a Knowledge Article on the CDR Support Portal: https://cdr-support.zendesk.com/hc/en-us/articles/900001932463
