### ISSUE TITLE
HTTP Status codes supported by the specification

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#174]
# Request For Clarification
The list of HTTP status codes returned  by the APIs are listed [here](https://consumerdatastandardsaustralia.github.io/standards/#http-response-codes)

Is 404 conspicuous in this list by its absence?

E.g if somebody enters a non-existent product ID in a 
`GET https://data.holder.com.au/cds-au/v1/banking/products/NonExistentProductID`

HTTP and REST API Standards state a 404 should be returned. 

What does the Specification expect as the status code for these scenarios?

I looked at the Big 4 behaviour and there were 4 different responses:

1. CBA - 200 
2. Westpac - 404 
3. NAB -  400 
4. ANZ -  403

How are the ADR/TPP Software products going to interpret such varying results?

**Comment by bmangalaganesh** [comment]
Thanks @cdradr I had seen this issue #118 . It is generic and broader. 

My question is very specific  - As 404 is not in this list of status codes, are we allowed to return a 404? Will that be considered as non-compliance?

**Comment by Camios** [comment]
Agree that 404 should be added to the spec and used as a response from Get Product Detail when there's no matching product.
I'm also curious why the two banking product endpoints don't have a list of response codes for errors. Only the success case (200) is listed.

**Comment by perlboy** [comment]
While I agree that the responses for all payloads should be explicitly defined `404` missing is deliberate and is aligned [with UK Open Banking](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1077805207/Read+Write+Data+API+Specification+-+v3.1.2#Read/WriteDataAPISpecification-v3.1.2-400(BadRequest)v/s404(NotFound)). 

The primary reason for not allowing 404's is due to the risk of information disclosure within authenticated APIs whereby there should be no difference in response between a missing object (ie. account id etc) and an endpoint that a user is not granted to. Admittedly this isn't much of an issue for Product APIs but these are only two endpoints of a larger landscape. The **only** acceptable 404 response within OBUK is where an endpoint is not implemented.

Nonetheless, coming back to my first sentence, this underscores the importance of explicitly defining all response types in all payloads rather than relying upon a table of ambiguous statements.

**Comment by Camios** [comment]
> While I agree that the responses for all payloads should be explicitly defined `404` missing is deliberate and is aligned [with UK Open Banking]

Is it fair to compare to UK Open Banking - there are lots of differences? (rhetorical)

> The primary reason for not allowing 404's is due to the risk of information disclosure within authenticated APIs whereby there should be no difference in response between a missing object (ie. account id etc) and an endpoint that a user is not granted to. Admittedly this isn't much of an issue for Product APIs but these are only two endpoints of a larger landscape and, at least personally I'd prefer consistent behaviour. The **only** acceptable 404 response within OBUK is where an endpoint is not implemented.

Regarding the suggestion that the UK made it indistinguishable to the error for an endpoint that the user is not granted to, it looks like they use different errors to distinguish between unauthorised (401), forbidden (403) and non-existent object 400. 

So I don't understand how using 400 helps. If the uk returns a 400 (instead of 404), then a bad actor can still use the 400 as an indicator that the account doesn't exist and keep trying for a valid account. It's not like the bad actor won't know that the endpoint is there because the endpoint url and the request format is part of a public standard. 

I can't see any justification for using the UK's 400 response code as a good example. Happy for you to try to change my mind. I might have missed something.

> Nonetheless, coming back to my first sentence, this underscores the importance of explicitly defining all response types in all payloads rather than relying upon a table of ambiguous statements.
This I agree with.

**Comment by perlboy** [comment]
> > While I agree that the responses for all payloads should be explicitly defined `404` missing is deliberate and is aligned [with UK Open Banking]
> Is it fair to compare to UK Open Banking - there are lots of differences? (rhetorical)

Well... the original mission statement (way back in 2018 if memory serves) stated UK OB should be used as the baseline. Admittedly the DSB has seemed to pick and choose when they feel like following this Treasury directive but, nonetheless, the idea was that shared lessons/behaviours across ecosystems would encourage adoption.

> <snip>
> Regarding the suggestion that the UK made it indistinguishable to the error for an endpoint that the user is not granted to, it looks like they use different errors to distinguish between unauthorised (401), forbidden (403) and non-existent object 400.

There's a nuanced difference in that 401 is used when a token is expired, 403 for when the token used doesn't have applicable scopes (border control drop) while 400 is when the oauth2 token layer passes but the resource server itself encounters an issue. 

> So I don't understand how using 400 helps. If the uk returns a 400 (instead of 404), then a bad actor can still use the 400 as an indicator that the account doesn't exist and keep trying for a valid account. It's not like the bad actor won't know that the endpoint is there because the endpoint url and the request format is part of a public standard. Essentially 400 (and 404, if it was available) are RS level and used to describe "You asked for something wrong" as opposed to authorisation server "You might be bad".

The simple example is that a 404 triggered indicates the account doesn't exist at all while a 400 would indicate the account is there, your token has scopes access but the token isn't granted consent to the account. By making the response the same you don't disclose that there is an account you don't have access to. Now, in the context of UUID's this is a bit of a silly distinction BUT the pairwise identifiers in use don't specify a complexity requirement so (poor) implementations may be exposed to enumeration attacks.

> I can't see any justification for using the UK's 400 response code as a good example. Happy for you to try to change my mind. I might have missed something.

There's **some** justification but I do accept it is weak (primarily as a "bad implementation" protection) so I'm not trying to convince you either way. What I would say is that UK OB already set the ground work, this was discussed long long ago both publicly @ https://github.com/ConsumerDataStandardsAustralia/standards/issues/11 and a lengthy thread internally during my time at the DSB in early 2019. I commented internally at the time that the most "REST-like" approach was to allow 404's but accepted that alignment with UK OB was the stated goal. Given the time passed and if you were so inclined presumably you could lodge an FOI requesting visibility of this discussion (along with the 50+ other issues I raised at the time).

> > Nonetheless, coming back to my first sentence, this underscores the importance of explicitly defining all response types in all payloads rather than relying upon a table of ambiguous statements.
> This I agree with.

Well that's something! :smile:

**Comment by CDR-API-Stream** [comment]
It would be expected that 404 would be returned in this case (as per normal RESTful API practice).

As stated previously for improving error handling, specific suggestions for improvement are most welcome.  If any of the contributors would like to raise a specific change request for this issue it will be considered for inclusion in the standards.

**Comment by perlboy** [comment]
> It would be expected that 404 would be returned in this case (as per normal RESTful API practice).

This is a change of the defined Standard. In fact 404 is never mentioned within the the Standards because [DP11](https://github.com/ConsumerDataStandardsAustralia/standards/issues/11) defined alignment with the UK Standards.

If the DSB wishes to now alter the decision perhaps they should create a change request themselves.

**Comment by perlboy** [comment]
Oh and further on this, 404 error codes were discussed internally and rejected by the lead.

If the DSB is now going to revisit decisions to align with "normal" RESTful practices perhaps it should review the use of `POST` for what would be `GET` calls as raised by me as early as  [November 2018]:(https://github.com/ConsumerDataStandardsAustralia/standards/issues/39#issuecomment-436827283).

**Comment by CDR-API-Stream** [comment]
The scenario originally raised in this thread has been addressed through Enhanced Error Handling with standardised error codes now [defined in the Data Standards](https://consumerdatastandardsaustralia.github.io/standards/index.html#error-codes) since v1.10.0.
