### ISSUE TITLE
LoA level to be enforced by the data holder

### ISSUE THREAD

**Issue by SachiniSiriwardene** [ConsumerDataStandardsAustralia/standards-maintenance#182]
# Request For Clarification
The security profile mentions about level of assurance. It mentions that

> READ operations SHALL only be allowed where at least an LoA of 2 has been achieved during the establishment of consent.

> WRITE operations SHALL only be allowed where:
> 
> At least an LoA of 3 has been achieved during the establishment of consent, or
> At least an LoA of 2 has been achieved during the establishment of consent and a subsequent challenge/response has resulted in an LoA of 3 being achieved within the lifespan of the current Access Token.

Since the current specification does not allow any write operation, can this be interpreted as minimal LoA requirement for a bank is LoA 2 which maps to CL1 (basic authentication).

When determining the value for the acr claim, should the user identifier and OTP be considered as "urn:cds.au:cdr:2" for acr?

**Comment by CDR-API-Stream** [comment]
Hi @SachiniSiriwardene that is correct.

**Comment by perlboy** [comment]
LoA 2 and 3 are currently defined in the Standards as:
![image](https://user-images.githubusercontent.com/4291448/78850297-313dcb00-7a5a-11ea-8368-13340db77e0f.png)

Which within the referenced _Authentication Credential Requirements_ these are defined as:
![image](https://user-images.githubusercontent.com/4291448/78850357-5df1e280-7a5a-11ea-9bdf-35453502dd4c.png)

Since the existing consent flow only uses an OTP then a single factor is achieved. It will be interesting to see what the strategy is to achieve multi factor without asking a user for their password in an environment where the OTP is already used as the first factor.

**Comment by cdradr** [comment]
Current authentication flow described by CX would not be classified as CL1 (mobile number and SMS sent to the same number).

Data61 hasn’t answered the question about authentication here: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/100#issuecomment-586073056

Also what if a Data Recipient request CL2 but CL2 can not be achieved by a Data Holder? Data sharing should be denied?

**Comment by perlboy** [comment]
> Current authentication flow described by CX would not be classified as CL1 (mobile number and SMS sent to the same number).

I admit my coverage of the TDIF is limited but the mobile number is content known by the DH and not disclosed to the consumer during login. Additionally the consumer supplies their account number as well as the OTP generated to their mobile number via blind lookup.

Based purely on the screenshot I supplied above it says "MUST use at least a single factor authentication". This seems to fit the bill?

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.

**Comment by Smoovsky** [comment]
> > Current authentication flow described by CX would not be classified as CL1 (mobile number and SMS sent to the same number).
> 
> I admit my coverage of the TDIF is limited but the mobile number is content known by the DH and not disclosed to the consumer during login. Additionally the consumer supplies their account number as well as the OTP generated to their mobile number via blind lookup.
> 
> Based purely on the screenshot I supplied above it says "MUST use at least a single factor authentication". This seems to fit the bill?

So the OTP required by Consumer Data Standard is classified as CL1, or CL2?
When the TIDF says MFA, I'm assuming something like username+password combination plus one more other factor like SMS/Email.
But OTP is here, due to the fact I assume that not all Data Holders have a "Customer Portal System". With solely OTP, is it still considered CL2?
If not, I guess the non-normative example in the CDS is sort of misleading:
```json
// ...
  "claims": {
    "sharing_duration": 7776000,
    "cdr_arrangement_id": "02e7c9d9-cfe7-4c3e-8f64-e91173c84ecb",
    "id_token": {
      "acr": {
        "essential": true,
        "values": ["urn:cds.au:cdr:3"]
      }
    }
// ...
```
Because under no circumstance that a user would achieve CL2.

Though OP mentioned ```urn:cds.au:cdr:3``` is not an ```acr``` value that is essentially required by a data recipient as currently there is no write action defined. (Though I think revocation is a write action but Private JWT Key Authentication is required by the standard for that action.)
