### ISSUE TITLE
Clarification Needed for offline_access scope

### ISSUE THREAD

**Issue by spikejump** [ConsumerDataStandardsAustralia/standards-maintenance#185]
[OIDC defines `offline_access` scope](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess).  This scope is defined as 

> This scope value requests that an OAuth 2.0 Refresh Token be issued that can be used to obtain an Access Token that grants access to the End-User's UserInfo Endpoint even when the End-User is not present (not logged in)

## Request For Clarification

1. Given OIDC is the backbone of CDS, does it imply to access UserInfo the DRs MUST request for `offline_access `from DH?  Similarly, DHs then must validate and support such scope.

2. CDS does not seem to explicitly address `offline_access`, however, it does define` x-fapi-customer-ip-address` and `x-cds-client-headers` that are explicitly to be used when the customers are logged on.  Does this mean the banking APIs are **NOT** restricted by the scope of `offline_access`?

3. Is `offline_access `relevant for CDS at all?  If not, can the specification explicitly state its override of `offline_access `for CDS?

4. If `offline_access `is to be used, how is this to be reflected in the user consent flow?  Will this be _hidden_ from users like 'openid'?

**Comment by perlboy** [comment]
In the UK the experience of differentiating present and not present calls has been of limited values. While on paper the separation between these calls "seemed" like a good idea in reality the CMA9 generally found implementing different QoS behaviours to be more effort than provisioning resource. Additionally the fraud detection component was of limited value as the data itself was implicitly of low trust value because it was sourced from an external party (ie. the recipient).

Things would be a lot simpler if CDR simply aligned with the FAPI profile in this area.

**Comment by spikejump** [comment]
Thanks for the info @perlboy 
I've just realised I forgot to put in a reasonable title for this.  Now updated.

**Comment by CDR-API-Stream** [comment]
The `offline_access` scope in OIDC is separate to the components of the CDR standard that were used to separate between customer present and customer not present scenarios.  The `offline_access` scope relates to the  Authorisation Server implementations that accommodate different `response_type` values.  The CDR standards explicitly limit the value of `response_type` as the intent is to restrict all data transfer to the back channel.  This position would appear to render the `offline_access` scope redundant.

If it would be helpful to include a statement to this effect in the standards please raise a change request and it will be considered.

It should be noted that the components of the CDR standards used to differentiate customer present and customer not present traffic are similar but not exactly the same as the `offline_access` scope as these mechanisms are used to differentiate types of traffic that are both sent back channel.  Also, these mechanisms are not intended for consent management, only traffic and fraud management.

**Comment by spikejump** [comment]
A bit confused on how response_type is related to offline_access.

In any case, it would help to have the spec mentions offline_scope is not relevant for CDR.

**Comment by CDR-API-Stream** [comment]
Hello @spikejump, if this issue is still relevant, we'd encourage you to create a change request so this can be consulted on.

A related article is available on the CDR Support Portal: https://cdr-support.zendesk.com/hc/en-us/articles/900003036086-Clarification-for-OIDC-offline-access-scope

The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
