### ISSUE TITLE
Decision Proposal Process Documentation

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#193]
# Request For Clarification
Please provide detail on the process being adopted for Decision Proposals and provide details on how this is being followed.

By way of example [DP99](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99) has just been released. The linked document indicates a publishing date of `14th April 2020` and an approval by the Chairman on `17th April 2020`. Where was this published on the 14th?

Further the last comment before publishing and prior to immediate closure was _"Thanks everyone for all your feedback and participation. The feedback period has now closed. The DSB will review the responses and will provide additional commentary here."_

Why does the DSB continue to have no clearly defined change process?

**Comment by CDR-API-Stream** [comment]
In the issue description of for [DP99](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99) (as linked in the issue description) there is a link to the final decision directly underneath the final decision endorsed by the Chair.

See the text: `The prior decision proposal consulted on is available [here](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-604196943).`

The DSB continues to use the same process for decisions that has been in place since mid 2018.

**Comment by perlboy** [comment]
The prior decision is not the content of the new decision and the new decision was not published until it was approved. The DSB continues to follow a process which has **never been defined** since mid-2018. On numerous occasions requests have been made for the process to be defined and on numerous occasions references have been made to noting papers and ultimately ended in _"The chair has ultimate authority"_. Why is the DSB so evasive on actually **documenting** the change process as requested by numerous participants in banking and now those in Energy as well?

**Comment by perlboy** [comment]
We see no value in continuing to pursue this as the DSB has shown they have no intention of being transparent in their decision making process. Clearing backlog and closing ticket.
