### ISSUE TITLE
Address the data gaps identified in feedback by FinTech Australia

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#2]
# Description
During the May consultation the submission from FinTech Australia identified a series of data gaps that they have requested be added to the standards.  A decision by the DSB was provided in response to the May submission.  The fields that were then decided not to be included are now being raised for wider consultation.

# Area Affected
This change affects the payloads of the existing Banking end points.

# Change Proposed
The following requested data has not been included in the standards:
* Account holder date of birth
* Default status for customer (including details of the default, such as product, date of default, principal amount, outstanding amount with fees and interest)
* Guarantors linked to particular products
* Whether mortgages are for owner occupied or investment property
* Details of relevant security property or other secured assets (including type of security, valuation)
* Application details (including date of applications, products applied for, current status)

**Comment by anzbankau** [comment]
## Mortgages: owner occupied or investment property
For the proposed change listed as _'Whether mortgages are for owner occupied or investment property'_, please consider using the same pattern as for #48 [Inclusion of repaymentType in the Product detail API](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/48) i.e. incorporate a new property at both `product` and `lendingRate` levels. Data recipients may consider owner-occupier and investment loans as distinct products or may consider them as different interest rate sets within a single product. Data recipients could readily split a single product into separate products as required for comparison/matching purposes. 
Note: The original interest rate tiers proposal included a new property `loanPurpose`: _'The reason for taking out the loan. The purpose generally affects the rate offered due to different risk profiles.'_ with enumerations: `OWNER_OCCUPIER` and `INVESTOR`. This should be `OCCUPATION` and `INVESTMENT` for consistency with `loanPurpose` (and ownership is implicit in both).

**Comment by nils-work** [comment]
As part of a backlog review in Maintenance Iteration 21, it was [suggested](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-21:-Meeting-notes-(18-September-2024)#issues-that-will-be-closed) that this issue could be closed. 
If there are no further comments, this issue will be closed on 25 October 2024.
