### ISSUE TITLE
Errors for Product Reference Data

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#205]
Hi, 

Can you please clarify these two questions around error handling for PRD APIs
 
1)      If GetProducts API receives invalid Brand or product-category query parameters in the request, is the expectation to respond with HTTP 200 with empty data {} or HTTP 400 bad request? Tried to cross checked this with live implementations by data holders, but the respective responses are inconsistent
 
2)      If GetProducts API receives page param value out of range in the request, how does a data holder handle the behavior of pagination objects – links & meta for an empty response.
 
Thank you

**Comment by CDR-API-Stream** [comment]
Hello @jakubvozarik this issue has been moved to the [Standards Maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues). This issue will be addressed here.

Queries and change requests are being addressed in the [Standards Maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance). In future it would be appreciated if you could post your questions there and the DSB will respond to them.

**Comment by nils-work** [comment]
Hi @jakubvozarik 

Although this is an older query that may have since been solved, I thought I would provide a comment with answers to your questions and later close this issue if there are no other concerns raised.

**Question 1**
> If GetProducts API receives invalid Brand or product-category query parameters in the request, is the expectation to respond with HTTP 200 with empty data {} or HTTP 400 bad request? Tried to cross checked this with live implementations by data holders, but the respective responses are inconsistent

Guidance has suggested a **200** response with an empty array, presuming there were no products matching what might have otherwise been valid parameters.

If the `product-category` provided in the query was not a valid value defined in the [Standards](https://consumerdatastandardsaustralia.github.io/standards/#get-products), a **400 - Invalid Field** error would be appropriate, with the code `urn:au-cds:error:cds-all:Field/Invalid`.

**Question 2**
> If GetProducts API receives page param value out of range in the request, how does a data holder handle the behavior of pagination objects – links & meta for an empty response.

There are now two types of enhanced errors relating to pagination of [Get Products](https://consumerdatastandardsaustralia.github.io/standards/#get-products) requests: 
- **400 - Invalid Page Size** with the code `urn:au-cds:error:cds-all:Field/InvalidPageSize` if the `page-size` value exceeds 1000.
- **422 - Invalid Page** with the code `urn:au-cds:error:cds-all:Field/InvalidPage` if the `page` requested is out of range according to the `page-size` parameter (or default value) and the number of records actually available.

As these are error responses, the `links` and `meta` objects usually required for a successful response are not applicable.
