### ISSUE TITLE
Multiple Simultaneous end point versions

### ISSUE THREAD

**Issue by DeanJonesBrisbane** [ConsumerDataStandardsAustralia/standards-maintenance#209]
**Are data holders REQUIRED to support multiple simultaneous versions of the same end point?**

With respect to end point versioning, specifically for product reference data. 

During the transition period covering the release of a new minor version of an end point (e.g. version 1 being replaced by version 2 of the get products APIs), is it expected that; 

- A)	Data holders will be allowed to upgrade from V1 to V2 in one activity, both releasing V2 and deprecating support for V1 at the same time? The effect of this would be that support for simultaneous versions would reside with the 3rd party consuming systems, as they would need to support both old and new versions until all data holders have updgraded to the new version.

**OR** 

- B)	Data holders are expected to provide support for both the old AND the new versions of an end point during the transition period? The effect of this would be that support for simultaneous versions would reside with the data holders and consuming systems would be able to upgrade at any time during the transition period.

Which of these (A or B) is the expected approach?

Note: This question assumes that the only reason multiple versions of the same endpoint would exist ‘live’ at the same time is to support the transition from the old to the new, and that there would never be more than TWO versions of any endpoint simultaneously live. Are these valid assumptions?

**Comment by perlboy** [comment]
Each version should be online until the retirement date specified in the [Future Dated Obligatitons](https://consumerdatastandardsaustralia.github.io/standards/#future-dated-obligations). It is possible holders will need to provide more than 2 versions concurrently.

So the short answer to your question is **Yes**, 2 or more simultaneous versions of an endpoint should be assumed during architecture.

**Comment by CDR-API-Stream** [comment]
Hi @DeanJonesBrisbane thanks for the question. There is nuance in the answer to your problem here.

In the case of an ADI commencing obligations - such as the non-majors being required to share product reference data (PRD) from July 2020, they can choose to go-live with version 2 support and do not have to support version 1 of the PRD endpoints. See here: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/201

Where a Data Holder already has an API in market, then as @perlboy states, the Data Holder should maintain that version up until the retirement date specified in the standards. Similarly, the Data Holder must support any newer versions by their support dates listed in the Future Dated Obligations. This aligns to Option B you present.

This means that a Data Holder should expect to have some endpoints in production where they are supporting more than one version. A Data Holder must follow the [Versioning guidelines](https://consumerdatastandardsaustralia.github.io/standards/#versioning) including [data recipient version negotiation](https://consumerdatastandardsaustralia.github.io/standards/#request-headers) with ``x-v`` and ``x-min-v`` headers.

**Comment by CDR-API-Stream** [comment]
This issue has been closed as per the [Data Standards Maintenance process](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance#closing-issues). No further questions or comments have been received since an answer was provided.
