### ISSUE TITLE
ID Permanence - Realization by the Data Holders

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#210]
# Request For Clarification
The cost (and associated complexity )of implementing 
[ID Permanence](https://consumerdatastandardsaustralia.github.io/standards/#id-permanence) (https://consumerdatastandardsaustralia.github.io/standards/#id-permanence)

The following identifiers are subject to ID Permanence rules

- accountdD
- transactionId
- payeeId
- scheduledPaymentId

Let's look at the scenario described below and see what is expected here.

1 Customer - John Doe

2 Accounts - 123456789 , 987654321  (these are the actual account IDs in the core systems

Each account has 3 transactions

Account ID: 123456789

Txn001

Txn002

Txn003

Account ID: 987654321

Txn 991

Txn 992

Txn 993

2 ADRs one with 2 Software Products and other with a single Software

HonestMoneyBee  - Software Products - FriendlyMoney, ConservativeMoney

TrustfulMoneyPal - Software Product - MoneyGrow

If John Doe provides consent to all three software products, the expectation from ID Permanence is as follows:

Customer | TPP | Software Product | accountId (ID Permanence) | Account ID in Back End SoRs
-- | -- | -- | -- | --
John Doe | HonestMoneyBee | FriendlyMoney | 25f9e794323b453885f5181f1b624d0b | 123456789
John Doe | HonestMoneyBee | ConservativeMoney | 25f9e794323b453885f5181f1b624d0b | 123456789
John Doe | TrustfulMoneyPal | MoneyGrow | 9b3e61bf29f17c75572fae2e86e17809 | 123456789

The DH is expected to keep a mapping of this value (for each account ) and translate that to the actual account numbers to fetch data from their backend SoRs.

The number of account ID in the big 4 banks as well as the other banks would be a few million easily. If the ecosystem grows then the Data Holders have to maintain this mapping info for a long long time.

Now if we have to do this for a transaction ID then the numbers are phenomenal (considering that the Data Holders are supposed to serve data for over a number of years). 

How are the Big 4 and other Data Holders addressing the ID Permanence rules (for transactions, in particular? )

I am not sure hashing mechanism can work for ID Permanence.

> A unique ID of the transaction adhering to the standards for ID permanence. This is mandatory (through hashing if necessary) unless there are specific and justifiable technical reasons why a transaction cannot be uniquely identified for a particular account type

Also, I don't see a lot of discussions on ID Permanence and wondering if I am the only one who is thinking that this is a difficult problem to manage and operate (at scale!).

**Comment by CDR-API-Stream** [comment]
Hi @bmangalaganesh there are a number of options to solve ID Permanence, not all include the storage of the computed values in a data store. As you correctly identify this approach is unlikely to scale in the long term. ID Permanence, itself, is not unique to the CDR and has been solved in other markets and problems.

Other examples may employ the use of shift ciphers, hashing algorithms or symmetric key encryption or a combination of these and computed storage. The solution will be dependent on the Data Holder's needs and constraints including infrastructure capacity, security requirements and so forth.

Other data holders or solution providers may be able to comment on their respective implementations.

**Comment by perlboy** [comment]
Probably of key note here is that the Standards don't dictate that the ID Permanence has to be a specific format. Ie. In your examples provided you've used UUID's but this isn't strictly required and you can pick and choose what you want as long as it can still be url encoded. 

Also, the storage of a 1:1 map of trillions of combinations with an efficient KV store isn't _actually_ that big a deal these days. Nonetheless, on the basis of trying to do something a little bit better producing a reversible but not derivable transaction identifier is relatively easy. As an oversimplified example take a small sample of what is known during calls:

1. The arrangement identifier assigned to the token and bound to the client id (Known by Recipient & Holder) 
2. The first "arrangement setup record" representing the first time the Consumer went through the flow that setup the arrangement (Known only by Holder)
3. The internal transaction identifier (Known only by Holder)

Assuming each of these is internally mapped as a UUID this represents 3 x 128bit identifiers with 1 known by both parties (but not by others), 1 known only by the holder and 1 (depending on the call type) either able to be derived from a result or generated as an output. That leaves us with:

1) Arrangement ID: 17652220-4a69-459f-a14e-959519411526 (31097358046021964006304448745861879078)
2) "First Flow": d3721bf8-3bf9-4f28-bdd0-15c31c58bdc5 (281059596244694833592055703441048649157)
3) Internal TX ID: 619bc40e-b30c-4650-9469-84bc883421a7 (129743898121098984801139026108293063079)

If we assume our method is to be rather lazy and multiply them all together we would get a decimal result as follows:
(1) * (2) * (3) = `1133989032137280052935966223881672807202826200523097207656439507909255439328091360613981327830248363930094094840434`

Since that is a really long number one can convert it to hex:
`75E1FF9CD0C2295AD2D0E19A5B0F86C6E558135B4C8447040DB411D1E06577A1E8117C98227A3EE6F88F5A8F038F272`

Or (and don't quote me, I cheated and [used this tool](https://www.mobilefish.com/services/big_number/big_number.php)) base64:

`1ruV_SqC8fMjBGuPfR3uR6vLWJMqo4HmGDj17Hu6LteUWHV9WYUZxc_8zQZmEF9o`

Now you have a string that can be reverse back to a tx id internally. If you wanted to be "extra special" the Holder could use some magic prime or apply some square root or modulo arithmetic on it.

I'm at pains to highlight this is **strictly** an example and there are many (**many many**) optimisations that you most definitely **should** do but it shows that it's possible to eliminate transaction identifiers from needing storage.

As for whether you apply the same technique on others is up to you but personally I question whether it's really "worth" it at that point.

**Comment by CDR-API-Stream** [comment]
This issue has been closed as per the [Data Standards Maintenance process](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance#closing-issues). 

It is understood that responses by the community and the DSB have answered the questions raised in this issue.

**Comment by nils-work** [comment]
Hi @bmangalaganesh 

According to the [DSB update](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/269), the ID Permanence values in your fourth column should all be unique to the different Software Products (SP.)

One account accessed through two different consent arrangements* in the same SP would have the same ID though -


Customer | TPP | Software Product | accountId (ID Permanence) | Account ID in Back End SoRs
-- | -- | -- | -- | --
John Doe |ADR 1 |SP A (*1) | **AAAAA**|123456789
John Doe |ADR 1| SP A (*2)| **AAAAA**|123456789
John Doe |ADR 1|Same ADR, different SP|**BB**|123456789
John Doe |Other ADR|Other SP|**CCCC**|123456789

**Comment by bmangalaganesh** [comment]
@nils-work Yes the ID Permanence value will be the same as long these elements do not change

- Customer
- Software Product
- Resource 

> IDs MUST be immutable across sessions and consents
 
Here are a few pictures that I use for my reference to clearly understand this space:

A table that describes the ID Permanence requirements using example names for Customers, Software product, and resource 

![image](https://user-images.githubusercontent.com/12740620/93160770-61e60700-f754-11ea-8604-07f616a2c99f.png)

A visual representation of ID permanence for a customer across different ADR/ADR Software products 

![image](https://user-images.githubusercontent.com/12740620/93161139-43344000-f755-11ea-8970-74b28d255307.png)

A visual view of ID permanence for Joint Account Holder scenario

![image](https://user-images.githubusercontent.com/12740620/93161468-f7ce6180-f755-11ea-9eea-fdd96fbd70c7.png)

Hope these are useful to the community.

**Comment by CDR-SN** [comment]
We are using encryption/decryption solve Id Permanence.
We are using client_id (software product id) & a private key (from x509 certificate) to

encrypt/decrypt an **unique payload** containing the real ids.
The difference in the payload will ensure an unique id on encryption.

For eg.

Customer Id & Account Id are an unique combination in the system.

So, we encrypt them to generate the Account Permanence Id.

`j7HaSL0TqbytW8DLU+k5lrQ4f3iKr8I4owzgwnMc%2F4f0p+WmHvBt6Vuv7347b48d`

Meaningless to the client. They cannot decrypt it without the private key.
And, we can decrypt it to get the real ids back from the payload.

Also, encrypting the same payload will always result in the same unique id.
So, the permanence id is immutable.

We are doing the same for Transaction Id.
