### ISSUE TITLE
Handling of Inactive Software Products

### ISSUE THREAD

**Issue by NationalAustraliaBank** [ConsumerDataStandardsAustralia/standards-maintenance#217]
# Request For Clarification
NAB would like to express our concern regarding inconsistencies around how we handle inactive software products and OAuth standards. On one side its been communicated that we should treat an inactive software product as an invalid client (from an OAuth perspective) and thus should reject requests on token and authorisation endpoints. However due to the data holder responsibilities we are expected to facilitate consent withdrawals on the revocation endpoint, meaning we need to authenticate and trust an “invalid” OAuth client on the revocation endpoint.

In addition to the above the CDR spec doesn’t mention revocation of access tokens for inactive software products. Access tokens would have already been revoked by the DH however if an ADR calls the endpoint should we return error or success?

**Comment by bmangalaganesh** [comment]
@NationalAustraliaBank 

> On one side its been communicated that we should treat an inactive software product as an invalid client (from an OAuth perspective) and thus should reject requests on token and authorisation endpoints

Where is this information available? I am unable to locate this info in the [CDR Register API](https://cdr-register.github.io/register)

The way I read the specifications is the DH should reject CDR API requests from a "Inactive" software product. In other words, the access tokens and refresh token are still valid but the DH returns an error stating they are not entitled to view the date.

This allows the ADR to still facilitate the Consent withdrawal even when the software product is Invalid.

Also from a Data Holder perspective,  they can support the scenario described under **[ADR Software Product Reactivated](https://cdr-register.github.io/register/#status-changes)** as the refresh (and access) tokens that are held by the ADR when they transition from Inactive and active will now start working  (i.e they will start receiving CDR data).

**Comment by CDR-API-Stream** [comment]
It is the understanding of the DSB that the comments by above @bmangalaganesh are correct.

To be specific there are two scenarios where an impaired status can be given to a software product:

**The software product has been surrendered or revoked**
In this scenario the the client ID provided for the software product should be considered invalid and should be treated as invalid as instructed in the normative standards such as OAuth 2 and OIDC.  As this is a permanent state of impairment all consents, refresh tokens and access tokens should be considered to be revoked also.

In this scenario there is no need for the calling of revocation end points as any consent that could be revoked has already been implicitly revoked by the status change of the software product.

**The software product is suspended**
Suspension is a potentially temporary situation.  Consents, client IDs, refresh tokens and access tokens should not be permanently revoked but, for the duration of the suspension should be treated as if they are revoked so that no data sharing can occur.  Client IDs, Refresh tokens and Access tokens should be treated as invalid as per the normative standards for the duration of the suspension.

As consents are not revoked they should still appear in Data Holder dashboards and it is reasonable that a customer may wish to revoke these consents as they would under normal circumstances.  Notification of revocation should occur in these situations so that, if the suspension is lifted.  As notification to the ADR only requires authentication of the data holder by the ADR this can still occur. 

Notification of revocation from the ADR to the Data Holder cannot occur as the ADR cannot be authenticated without a valid client ID.

The comments above are based on the understanding of the DSB.  If this is inconsistent with the position of the Register then it would be good for this to be clarified and we will clarify our understanding as a result.  If there is a desire to change the standards this can be accomplished in the normal way via a change request.

**Comment by CDR-API-Stream** [comment]
In discussion with the ACCC it has been agreed that, as this issue is primarily related to the interpretation and understanding of the rules relating to notification of revocation and the meaning of suspension, that further discussion should occur on the Register GitHub site.

As the issue is potentially a subset of the broader problem of notification when the counter-party is unavailable or unable to handle the notification it is suggested further comments be made in relation to the existing thread for this issue:
https://github.com/cdr-register/register/issues/82

**Comment by CDR-API-Stream** [comment]
This issue has been answered. Accordingly, the issue is closed.
