### ISSUE TITLE
Allow retrieval of current refresh_token by arrangement ID

### ISSUE THREAD

**Issue by pcurtisrab** [ConsumerDataStandardsAustralia/standards-maintenance#219]
# Description
Data recipients face the possibility of effectively losing sharing arrangements because of a communication failures during calls to token endpoints resulting in the loss of a refresh_token. This [has already been discussed in some detail](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/52).

# Area Affected
[CDR Arrangement Management End Point](https://consumerdatastandardsaustralia.github.io/standards/#end-points)

# Change Proposed
Add a GET method to the Data Holder arrangement endpoint that allows the current refresh_token to be retrieved.

This would allow Data Recipients to gracefully recover from unintended refresh_token loss or expiry without unnecessarily asking the consumer again for consent. Since we now have a Data Holder endpoint (i.e. the arrangement endpoint), that requires a data holder to be able to retrieve a refresh_token for a given arrangement ID, it seems logical and simple to extend that endpoint to allow the retrieval of the current refresh_token.

**Comment by perlboy** [comment]
I don't think the solution to loss of refresh token during cycling (?) is to expose an alternate method of obtaining the security credential. I would suggest instead the solution to loss of token would be the disabling of the old tokens **after** the use of the new one (ie. "Confirmation of handover"). I also raised and discussed at length this race condition as far back as November 2019 with no real clarity provided by the DSB in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/34.

Allowing for refresh token retrieval from the Sharing Arrangement API means that this API has access to security credentials (ie. is part of the IdP domain not the resource server one) versus being able to verify a token and only be aware of an arrangement id. Beyond the security concerns this also has implementation concerns because this endpoint is marked as [MTLS for Data Holders](https://consumerdatastandardsaustralia.github.io/standards/#end-points).

For what it's worth this race condition is considered in the [Grant Management API](https://bitbucket.org/openid/fapi/src/master/Financial_API_Grant_Management.md) specification the FAPI WG has in draft status. Our solution was to allow for the supply of an existing `grant_id` and a `grant_management_mode` of `update` whereby IF the update request matched the existing grant id a user could be exposed to an "optimised browser flow" to allow for a recoverable but authorised retrieval of refresh token. The authors felt this approach provided for a balance between the need to ensure security credentials were not unintentionally leaked, as could be the case in #219's proposal but not in Grant Management API because it is an OAuth2 extension. Conversely the authors felt the user experience impact could remain low (ie. "2 click reauth") for, arguably, what should be a low frequency occurrence (loss of refresh token).

Alas, despite the recommendation of Grant Management API [by the OIDF](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-611364287) the DSB has seen fit to implement a Frankenstein that seems unlikely to meet the future goals. From here it is a slippery slope if additional features are added without formal and transparent assessment of the security impacts.

**Comment by pcurtisrab** [comment]
For what it's worth, I think the "Confirmation of handover" approach mentioned by @perlboy is preferable to this proposal #219.

**Comment by CDR-API-Stream** [comment]
Hi @pcurtisrab thanks for this it's a good question. This is similar in context to #175.

Broadly speaking we have a few options:
1. accept that there is a risk of losing tokens. Likely to be infrequent, but expected.
2. develop a workaround that allows an ADR to get tokens through other means.
3. adopt a "confirmation of handover" approach that minimises the risk of unintended token loss.

Unless there is any valid feedback why it wouldn't be possible technically or from a security perspective, the pattern in option 3 is the preferred expectation. Confirmation of handover would ensure that refresh tokens are only considered to have been successfully "cycled" when the new refresh token is used to communicate with the DH - this could be via the token endpoint or token introspection endpoint.

This doesn't change the expectations that an ADR should be developing for robustness. ADRs should probably check the status of the DH before commencement of a token request.
* If the DH is not available or has a pending scheduled outage that will likely impact collection of tokens, the ADR should consider delaying the call and/or informing the consumer at the CX level
* Refresh token exchange shouldn't be left to the last 5 mins prior to refresh token expiry
* etc.

**Comment by pcurtisrab** [comment]
Hi @CDR-API-Stream ,
I would also consider option 3 to be preferred. I also agree on the comments regarding robustness. Note however, that an up status of the Data Holder does not guarantee a successful token request, but I think that is already understood.

I rather disagree on the outage point, however. Equally, if not more so, data holders should be developing for robustness, and they should take their token endpoint down if it is likely to be affected by an outage. If a data holder believes that refresh token cycling is worth the added complexity, they need to own the additional costs.

**Comment by brett-frollo** [comment]
Hi @CDR-API-Stream @pcurtisrab, I would like to comment on this issue on behalf of Frollo, one of the current ADRs in the ecosystem.

We are heavily using ongoing consents in production, resulting in refresh token recycling every time data sharing occurs. To date we have made over 1 million API calls. This issue has occurred many times where a new refresh token will be provisioned by a Data Holder but fails to reach us - leaving us unable to perform data sharing for that consent.
In the first week or so of go-live, this occurred due to initial production infrastructure problems (put down to teething issues of the new systems), but as the weeks have gone on we have seen this issue occur many times with multiple DHs for many different reasons. All end up with a mismatch of refresh tokens (the DH has the new refresh token, while the DR still has the old). Of course without a change to the standards, when this occurs there is no recourse but to communicate to the consumer that there has been an issue and ask them to withdraw their consent and start the consent process again. This also triggers a data deletion and results very poor user experience for what is essentially a technical problem.

We support the confirmation of handover suggestion by @perlboy (option 3) as it is clear to us that removing all issues for this not to occur is highly unlikely and impractical.  It is our view that the current refresh token recycling mechanism is flawed without a practical resolution that does not involve withdrawing a consent for a technical reason.

**Comment by perlboy** [comment]
@brett-frollo Thanks for providing some experience from real implementations doing real things. While I don't see another short term path than Option 3 I'll highlight this could be architecturally difficult to implement for IDP vendors and also introduces an attack vector that will need mitigation during testing (ie. it's not just a "quick attribute" change). It's disappointing that [what I predicted in November 2019](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/34#issuecomment-552242694) has now come to pass and is impacting the first customers to the Australian open banking ecosystem.

**Comment by ttranatping** [comment]
Ping Identity has experimented with option #3 and have got it working. Conceptually it is possible.

- How many times will we allow an old RT be used? Without limits, ADR's can ignore RT rolling and renders it irrelevant. We should consider limiting this to reduce the attack vector.
- It’s quite difficult to test with a min 28 day rolling period. Perhaps we should remove this limitation now with this new resilient RT model. Data holders should have the option to roll on every refresh_token grant.
- How do the introspect and revocation endpoints work when provided an old RT?

**Comment by pcurtisrab** [comment]
Hi @ttranatping,

It sounds as though your solution involves checking for old refresh_tokens at the token endpoint. It sounds like you would keep a list of recent refresh_tokens and/or limit the frequency with which new refresh tokens can be issued. Those are the assumptions underlying my responses to these questions.

> How many times will we allow an old RT be used? Without limits, ADR's can ignore RT rolling and renders it irrelevant. We should consider limiting this to reduce the attack vector.

Ideally I think this would be once only. As soon as a data recipient detect successful use of a refresh token, they are able to mark that token as "active"

> It’s quite difficult to test with a min 28 day rolling period. Perhaps we should remove this limitation now with this new resilient RT model. Data holders should have the option to roll on every refresh_token grant.

I think the standards already allow data holders to cycle refresh tokens on every grant.

> How do the introspect and revocation endpoints work when provided an old RT?
> - Response payloads - active, expiry, etc.
> - Should you be able to revoke with an old RT?

Ideally only the "current refresh" token is reported as ACTIVE. This is the essence of confirmation of handover in my mind. While there may be multiple *issued* refresh_tokens, only the latest one successfully used by the client is active. When a client introspects the new refresh token, the old tokens become inactive. When a client revokes any known refresh token, all refresh tokens are revoked.

> Consider deleting the previous RT's if an introspect is called with the new RT. (seems like it already has been)

I think this is the crux of a simpler solution (coming in the next comment).

**Comment by pcurtisrab** [comment]
Inspired by @ttranatping, I would like to offer an alternative simplified confirmation of handover design for consideration by the community:

### Simplified confirmation of handover approach

A confirmation of handover approach needs to be simple to build and ideally reduce the need to track the status of many tokens. It should also minimize size and complexity of changes of standards.

I would therefore propose adapting the Refresh Token section of the standards like this:

> ### Refresh Token
> Refresh Tokens MUST be supported by Data Holders.
> 
> The usage of Refresh Tokens is specified in section 12 of [OIDC].
> 
> The expiration time for a Refresh Token MUST be set by the Data Holder.
> 
> Refresh Token expiration MAY be any length of time greater than 28 days but MUST NOT exceed the end of the duration of sharing consented to by the Consumer.
> 
> Data Holders MAY cycle Refresh Tokens when an Access Token is issued. If Refresh Token cycling is not performed then the Refresh Token MUST NOT expire before the expiration of the sharing consented by the Customer.
> 
> #### Confirmation of handover under refresh token cycling
> 
> When a new refresh token is issued, a Data Holder MUST continue to honour the current refresh token until handover of the new refresh token is confirmed.
> 
> Confirmation of handover is confirmed when either:
> 1. A Data Recipient successfully introspects the last issued refresh token.
> 2. A Data Recipient is issued a new access token using the last issued refresh token as the grant credential.
> 
> ##### Recovery method for lost refresh tokens
> A data recipient may lose track of the current access token under the following conditions:
> 1. A new refresh token is issued by the Data Holder (OP), but not received by the Data Recipient (RP). In this case, the Data Recipient can continue to use the current refresh_token.
> 2. A new refresh token is received by a Data Recipient, but an unknown failure occurs during the confirmation of handover (at either the token or introspection endpoint). In this state either the current token or the new token may be active (but not both), and the Data Recipient can use token introspection on the two candidate refresh tokens to determine which one is active.

Note that the "Confirmation of handover under refresh token cycling" exists to ensure that data recipients can always know one valid refresh token in case the transfer of refresh token fails due to failures outside of the control of a data recipient (e.g. network or policy failures). Mode 1 above is provided to serve the use case where access of data is infrequent and a Data Recipient wants to confirm handover before the old token expires and without starting a session to access data. Mode 2 is provided to serve the case where a data recipient is unable to exclusively rely on Mode 1, and to not introduce further departures from the non-standard requirement on RPs and OPs, namely that that a Data Recipient (RP) must call the OP's introspection endpoint before requesting a new token.

It is worth mentioning the build implications that under this change, especially that both Data Recipients and Data Holders would have an option to not implement these changes:
- Data Holders may choose not to do refresh token cycling, negating the need to build support for this handover method.
- Data Recipients may choose to continue to assume that token refreshes will always be successful and accept the risk of failure.

Under this design, there is only ever one active refresh token, and from general perspective a Data Holder (OP) need not track more than 2 refresh tokens a time. Data Holders (OPs) could approach implementation like this:

When a new refresh_token is issued, it is conceptually staged as the "_next refresh token_", and the current refresh token remains active. The _next refresh token_ becomes active and replaces the current one when either of the following occur:
- The introspection endpoint is called on the _next refresh token_ with valid matching client asserion.
- The token endpoint is called with _next refresh token_ used as the grant credential and valid matching client asserion.

**Comment by perlboy** [comment]
This discussion, partially my own fault, seems to have morphed into a few different discussions in a single thread starting at modifications to Arrangement Management landing at refresh token cycling. It may be worthwhile spitting into "Refresh Token Cycling" and "Recovering Sharing Management access on Token Loss"

On refresh token cycling and loss of tokens, this is an immediate bug that needs at least a temporary solution for the continuity of the ecosystem. This is an inevitable result of distributed communication systems but is (imho) a symptom of an underlying issue (technical consent vs. business consent).. Nonetheless, and despite suggesting it to begin with (while trying to [clarify it](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/34) in the first place), further discussions among a number of learned folk asked an important question **"Why do refresh token cycling at all?"** among _"Handover Confirmation looks complicated"_. The clients are confidential and since it's RT it is ("usually") only presented to the OP's IdP. [Neither infosec analysis](https://consumerdatastandards.gov.au/knowledgecentre/reports/reports-information-security/) done on the CDR makes zero mention of it (although that doesn't mean it's been considered).

On Recovering Sharing Management Access. This is more a subset of the broader question around Sharing Management API (known in some circles as "Consent API" with the Frankenstein name being "CDR Arrangement Management"). If sharing/consent metadata were separated from the tokens (or at least placed in a specified location - like _authorization_details_ or... as part of Grant Management (yep, that again)) it would be possible to implement an asynchronous Sharing Recovery API at the sharing management endpoint allowing organisations to implement, potentially human based, solutions to authorising the reissuance of lost tokens in a way that is low friction to the Consumer but enables a Recipient to continue conducting their business in the face of likely recurrences of token loss (not just the one involving the refresh token) for both technical and potentially business based reasons. 

Unfortunately, now that I've suggested this, we'll probably get some dodgy point solution that is suitably politically expeditious and be raising a fresh set of issues that hadn't been thought of in the post July go-live (with 10x more Holders)...

![image](https://user-images.githubusercontent.com/4291448/91912859-8626fa00-ecf7-11ea-959f-ecc98d4ecb8c.png)

**Comment by pcurtisrab** [comment]
I raised this issue to address "refresh token cycling and loss of tokens". I would be happy to rename it to that.

FWIW, I've posted [a slightly more detailed analysis of the problem and solution I have put forward here](https://gist.github.com/pcurtisrab/e39f853fb639e92c497e0fe34b664d29).

**Comment by spikejump** [comment]
Not trying to muddle the water here.  But would suggest that #175 is considered along with this issue.  Suspect a lot of cause of "loss" of refresh tokens are related to how DHs are implementing when to mark a consent as truly authorised; when a refresh token is truly used.

**Comment by CDR-API-Stream** [comment]
As discussed in the maintenance iteration call [held on 7/10/2020](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-5:-Iteration-Scope-Review:-Agenda-&-Meeting-Notes-(7th-October-2020)), four options were identified and discussed. Each solution has trade-offs however a solution that is both simple and reduces the overall chance of consumer impact is preferred.

**Option 1** 
As per the original change request, treat the ``cdr_arrangement_id`` as a long-lived "secret" and use it as a mechanism to allow ADRs to exchange for a refresh token if/when they lose their refresh token.
* The ``cdr_arrangement_id`` is meant to represent a long-lived identifier potentially spanning multiple 12 month consent authorisations
* This wouldn't make it a practical "secret" and there aren't any current standards for cryptographic proofs over the top

**Option 2**
Tighten up the data standards to be clear that DHs cycling refresh tokens can only set an expiration greater than or equal to 28 days where ``sharing_expires_at`` is >= 28 days; where ``sharing_expires_at`` is < 28 days it must be the duration remaining for the sharing arrangement. Whilst unintended, the current data standards would allow refresh tokens to be cycled every time an access token is requested:  
> Refresh Token expiration MAY be any length of time greater than 28 days but MUST NOT exceed the end of the duration of sharing consented to by the Consumer.

* This may reduce the frequency of the issue occurring but does not resolve the underlying cause that refresh tokens are lost in transit
* It has implementation impacts to at least one DH and a future dated obligation would be required
* DHs would continue to make the decision on an individual basis whether to cycle refresh tokens and at their preferred length

**Option 3**
Don't allow refresh cycling at all: this means that DHs cannot cycle refresh tokens and the refresh token will be bound to the duration of the sharing arrangement.

* This would be the simplest solution and mitigate the risk of loss of the confidential secret used to obtain new access tokens
* Minimises impact to ADRs and consumers
* Refresh token cycling was originally intended for public clients rather than confidential clients which can securely store refresh tokens and the CDR has other security measures which potentially make the need to roll refresh tokens less necessary
* This change would have implementation impacts to at least two DHs

**Option 4**
Continue to allow DHs to support refresh token cycling but where DHs do this, they must support the "confirmation of handover" approach to prevent loss of refresh token and ensure loss of refresh tokens in transit do not impact ADRs.

* This allows DHs to decide whether they support rolling of refresh tokens within the duration of the sharing arrangement but imposes additional support requirements
* Minimises impact to ADRs and consumers
* This would have implementation impacts to at least two DHs and a future dated obligation would be required
* Implementation impact is higher than Option 3 which is more of a configuration rather than customisation required for Option 4

To progress this CR, the DSB would welcome input on the options or alternative options and any impact ADRs are currently observing.

**Comment by CDR-API-Stream** [comment]
Hi @spikejump, 

> Not trying to muddle the water here. But would suggest that #175 is considered along with this issue. Suspect a lot of cause of "loss" of refresh tokens are related to how DHs are implementing when to mark a consent as truly authorised; when a refresh token is truly used.

Although they are related in that they both represent the potential loss in transit of a secret which, if not received by the ADR, would orphan the consumer's consent, the solutions are likely to be different.

This issue is the loss of a token after authorisation however #175 is the loss of the authorization_code during the authorisation flow. This presents other challenges given the authorization_code is short lived (seconds), cannot be re-used and may not be held in storage by the authorisation server after use.

#175 is being consulted on within this current maintenance iteration, so any further considerations and options can be considered to deal with that problem.

**Comment by pcurtisrab** [comment]
Regional Australia Bank supports Option 3. We fear that the implementation of Option 4 would be error prone and so risks replacing one set of problems with another.

**Comment by commbankoss** [comment]
Commonwealth Bank is strongly opposed to options 1 and 2, and are supportive of options 3 and 4, with preference for option 4 as it provides DHs the option to use token cycling if their cybersecurity team recommends doing so.

**Comment by anzbankau** [comment]
ANZ is not supportive of Option 1 and 2. We also agree with RAB that Option 4 seems problematic, and it would introduce new implementation requirements for Data Recipients and some Data Holders.

**Comment by WestpacOpenBanking** [comment]
All options proposed weaken the security of the system. Our preference is to align with the reauthorisation approach of the normative references and we favour the idea of a ‘optimised browser flow’ to minimize the customer friction involved if this is required. 

With regard to the presented options:
* We strongly oppose Option 1 due to security concerns [raised](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/219#issuecomment-632944797) by @perlboy. 
* We oppose Option 2 because it only reduces the severity of the issue and does not address the cause.
* We oppose Option 3, because refresh token cycling is global setting on our identity platform and the use of token cycling is required to keep other uses of this platform secure. 
* We oppose Option 4 as proposed (not invalidating old tokens until new tokens are used) as it is not a supported customization on our identity platform. With build effort, we are able to implement a variant of Option 4 where an invalidated refresh token could be presented to get a new valid refresh token (without an accompanying access token) if a failure occurs. We recommend limiting the lifetime for which old credentials are still usable to the lifetime of an access token to help minimize the introduction of security risks.

**Comment by NationalAustraliaBank** [comment]
NAB is also opposed to options 1 and 2. We are supportive of options 3 and 4. Similar to Commbank's view, we prefer option 4 as it provides flexibility to the data holders with an option to implement token cycling.

**Comment by biza-io** [comment]
Biza.io believes the adoption of Option 3 in the short term provides a tactical solution to the problem at hand. Beyond this solution we strongly recommend that the DSB focus it's efforts on a streamlined reauthorisation mechanism (as indicated by @perlboy) that alleviates this problem more broadly.

**Comment by CDR-API-Stream** [comment]
The outcome the decision record arising from the 5th maintenance iteration for [data standards v1.7.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159) is that a targeted decision proposal consultation will be raised by the DSB for this issue and #175. Because the nature of the changes involves consumer impact, CX considerations and InfoSec considerations it is the preferred avenue to present the options and considerations.

**Comment by biza-io** [comment]
Biza.io would like an update on whether the "targeted decision proposal consultation" has occurred and when the DSB will be providing an update on the outcome?

We are aware of a large swathe (20+) of holders expected to come online November 1 who intend to utilise Refresh Token cycling and do so _for each Access Token issued_ effectively making Refresh Tokens one time use. While Biza.io does not agree with this implementation the Standards do not appear to explicitly disallow it ("MAY"):
> Refresh Token expiration **MAY be any** length of time greater than 28 days but MUST NOT exceed the end of the duration of sharing consented to by the Consumer. Data Holders MAY cycle Refresh Tokens when an Access Token is issued.

Biza.io is concerned that active data recipients are now about to be exposed to far higher levels of token loss due to the brittle nature of such an implementation.

**Comment by nils-work** [comment]
As part of a backlog review in Maintenance Iteration 21, it was [suggested](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-21:-Meeting-notes-(18-September-2024)#issues-that-will-be-closed) that this issue could be closed. 
If there are no further comments, this issue will be closed on 25 October 2024.
