### ISSUE TITLE
Request for Clarification on contents of id_tokens

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#221]
# Request For Clarification
Commonwealth Bank is seeking confirmation on the following:
1. c_hash is only provided in id_tokens from authorization endpoint as per https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken, thus does not need to be provided in id_tokens from token endpoint.
2. As per section 5.2.2 of FAPI-RW, s_hash may be omitted from the ID Token returned from the Token Endpoint when s_hash is present in the ID Token returned from the Authorization Endpoint.

**Comment by commbankoss** [comment]
@CDR-API-Stream, Commonwealth Bank requests this issue be labelled as Urgent.

**Comment by CDR-API-Stream** [comment]
The standards currently state:

> As described under section 5.2.2 of the [FAPI-RW] profile, ID Tokens MUST include the following claims (in addition to the mandatory claims specified in section 2 of the [OIDC] standard) as part of Hybrid Flow authentication:
>
> * nonce: String value used to associate a Client session with an ID Token.
> * s_hash: Hash of the state value.
> * c_hash: Hash of the authorisation_code value.

This statement has been a part of the standard, without alteration, since December 2018 and makes no distinction between an ID Token provided from the Token end point and the Authorization end point. This statement overrides any statements in the underlying normative standards.

The ambiguity raised is noted.  After deliberation within the DSB we can confirm that the conservative interpretation of the standards is that currently the standards require that `nonce`, `c_hash` and `s_hash` must be included in the ID Token from both the Token and Authorization end points.

If there is a valid need for this position to be altered a change request would be path for that outcome to be achieved so it can be fully consulted on and considered. If a change request is raised and needs to be dealt with urgently this should be clearly indicated in the change request.

**Comment by perlboy** [comment]
The `s_hash` cannot be calculated if the `state` parameter is not supplied by the ADR which isn't currently mandated (but is _RECOMMENDED_ by OIDC). I raised this in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/142 in late February and received no response.

The `nonce` is specifically there to prevent replay attacks. Is the expectation that Holders will effectively replay it?

On `c_hash` while this could be stored after generation for replay (because `code`'s should be discarded as they are one use and time bound) it seems strange to do so because it would relate to an authorisation code which, if the call that returns it succeeds, is no longer valid.

**Comment by CDR-API-Stream** [comment]
As per the request from @commbankoss this issue and the corresponding CR #227 have been marked as urgent to address July requirements.

**Comment by CDR-API-Stream** [comment]
The change request resultant from this issue has been adopted in v1.4.0 of the standards. This issue has been answered and it is being closed accordingly.
