### ISSUE TITLE
Consent flow - Question about authorisation scopes

### ISSUE THREAD

**Issue by vongalex** [ConsumerDataStandardsAustralia/standards-maintenance#224]
Hi ACCC team,

I have a question in regards to what cluster we need to display on the data holder side based on what authorisation scope is sent from the data recipient.

CX guideline v1.3 page 19

2 Data Language Standards: Detailed
scope requests
If a scenario requires it, Data Holders and Data Recipients MUST merge and amend Basic and Detailed data cluster and
permission language to show that Detailed scopes include Basic data.
· Data Holders and Data Recipients MUST use the alternative language denoted with an ‘‡’ in Table 1 (rows greyed out for clarity).
Example: A Data Recipient presents the Detailed data cluster in a data request to a consumer, but does not present the
Basic data cluster. The Detailed scope includes Basic data, but this is not apparent to the consumer based on the data
cluster language and permissions used for the Detailed scope.

As an example we can use the customer info.

Is the below aligned with your expectation?

![image](https://user-images.githubusercontent.com/62583522/82965000-47074f80-a00a-11ea-86c0-d8346989d24a.png)

**Comment by CDR-CX-Stream** [comment]
Hi @vongalex,

Thanks for this query. 

The expectation in the technical standards is for the ADR to request basic scopes whenever detailed scopes are requested, as outlined below:

For **bank:accounts:detail:read**, the standards state it _‘is effectively additional authorisation to the Basic Bank Account Data scope. Granting this authorisation only makes sense if the Bank Account Data scope is also authorised. Includes basic account information plus account identifiers and product information.’_

For **common:customer:detail:read**, the standards state it _‘Includes the data available with the Basic Customer Data scope plus contact details.’_

The expected data language to be used by the DH is outlined below:

If the ADR **ONLY** asks for the basic scope (for either customer or accounts), the expectation is for the DH to only display the data language for the basic cluster.

If the ADR **ONLY** asks for the detailed scope (for either customer or accounts), the expectation is for the DH to display the merged language. This is because detailed scopes include basic scope data, and due to the expectation that ADRs will call basic scopes with detailed scopes.

If the ADR asks for **BOTH** basic and detailed scopes (for either customer or accounts), the expectation is for the DH to display the merged language.

**Comment by vongalex** [comment]
Ok thanks for the clarification

**Comment by perlboy** [comment]
@CDR-CX-Stream This answer is contradictory.

> The expectation in the technical standards is for the ADR to request basic scopes whenever detailed scopes are requested, as outlined below:

vs.

> If the ADR ONLY asks for the detailed scope (for either customer or accounts), the expectation is for the DH to display the merged language. This is because detailed scopes include basic scope data, and due to the expectation that ADRs will call basic scopes with detailed scopes.

This is incorrect because the Standards specify things similar to this:
![image](https://user-images.githubusercontent.com/4291448/98897706-beb53200-24f7-11eb-8669-01466b653acd.png)

Essentially, what this response seems to indicate is that a Holder arbitrarily modify an authorisation request **cryptographically signed** by the Recipient.

**Comment by perlboy** [comment]
Further on this, if an OP returns scopes not required by an RP they would fail the FAPI Conformance Suite's RP tests. That is to say, if Basic scopes were automatically added by Holders when only Detailed scopes were requested the Recipient would **never** pass a FAPI validation.

**Comment by nils-work** [comment]
Hi @perlboy 

Re: 
> Basic scopes endpoints do not include Detail scope as an option.

Do you think it would it make sense if the authorisation note associated with each API stated the scopes like -
- for the **basic** APIs, they require either the **basic OR detail scope**
- for the **detail** APIs, they require both the **basic AND detail scope** (ideally both are requested)

**Comment by perlboy** [comment]
> > Basic scopes endpoints do not include Detail scope as an option. 
> Do you think it would it make sense if the authorisation note associated with each API stated the scopes like -
> * for the **basic** APIs, they require either the **basic OR detail scope**
> * for the **detail** APIs, they require both the **basic AND detail scope** (ideally both are requested)

I do think this is the best approach yes as it means that IDP is not involved in altering the auth request and presentation layer (ie. consent flow) can be collapsed based on single scope presentation.

**Comment by commbankoss** [comment]
We agree with comments from @perlboy and we suggest the following way to deal with basic and detail scopes:

**Authorisation Server**
ADR is only granted the scopes requested (or a subset if not all scopes are allowed or supported).

For example:

- If ADR requests bank:accounts:basic:read, only bank:accounts:basic:read is granted.
- If ADR requests bank:accounts:detail:read, only bank:accounts:detail:read is granted.
- If ADR request both, both will be granted.

AS doesn't need to be aware of dependencies between scopes and relevant business logic.

**Resource Server - APIs**
Every API that requires bank:accounts:basic:read scope also to accept bank:accounts:detail:read scope (one or another should be granted).

**User experience / CX**
When ADR requests bank:accounts:detail:read the message should be clear that it includes basic account information too.
If ADR requests both (not recommended), then messages should align to minimise duplication.

**ADRs**
Guidance to ADRs not to request both: bank:accounts:detail:read includes all permissions of bank:accounts:basic:read.

**Comment by CDR-CX-Stream** [comment]
This issue is being discussed on [CDR Support Portal issue 281](https://cdr-support.zendesk.com/agent/tickets/281). A technical response has been added there, along with a CX response that has been adjusted slightly for clarity, as follows:

> The data language standards are structured in a way that allows ADRs and DHs to apply the standards to a range of scenarios, including where an ADR requests scopes that aren't ostensibly useful.
> 
> The intention of the merged language is to make clear to the consumer that authorising detailed scopes may provide access to basic data - not that the DH should include basic scopes on the ADR's behalf.
> 
> The expectation in the technical standards is for the ADR to request basic scopes whenever detailed scopes are requested, as outlined below:
> 
> For bank:accounts:detail:read, the standards state it ‘is effectively additional authorisation to the Basic Bank Account Data scope. Granting this authorisation only makes sense if the Bank Account Data scope is also authorised. Includes basic account information plus account identifiers and product information.’
> 
> For common:customer:detail:read, the standards state it ‘Includes the data available with the Basic Customer Data scope plus contact details.’
> 
> While the above ADR behaviour is expected it isn't mandatory, so the CX language is designed to accommodate a variety of scenarios.
> 
> The expected data language to be used by the DH is outlined below:
> 
> 1. If the ADR **ONLY** asks for the basic scope (for either customer or accounts), the expectation is for the DH to only display the data language for the basic cluster.
> 2. If the ADR **ONLY** asks for the detailed scope (for either customer or accounts), the expectation is for the DH to display the merged language. This is because detailed scopes include basic scope data.
> 3. If the ADR asks for **BOTH** basic and detailed scopes (for either customer or accounts), the expectation is for the DH to display the merged language.
