### ISSUE TITLE
Urgent documentation change required: content of ID Token

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#227]
Commonwealth Bank requests @CDR-API-Stream label this change request, which follows from #221, as Urgent.

**Description:**
The standards currently state:

> As described under section 5.2.2 of the [FAPI-RW] profile, ID Tokens MUST include the following claims (in addition to the mandatory claims specified in section 2 of the [OIDC] standard) as part of Hybrid Flow authentication:
> 
> - nonce: String value used to associate a Client session with an ID Token.
> - s_hash: Hash of the state value.
> - c_hash: Hash of the authorisation_code value.

However, the  s_hash and c_hash claims don't apply at the token endpoint as per https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/221#issue-621410250. 

**Area Affected:**
[Security Profile: Tokens](https://consumerdatastandardsaustralia.github.io/standards/#tokens) 

**Change Proposed:**
That it be clarified in the standards that listed claims do not apply for the token endpoint but they must apply for the authorization endpoint, as per normative references.

**Comment by CDR-API-Stream** [comment]
As per the request from @commbankoss this CR has been marked as urgent to address July requirements. The underlying issue #221 has also been marked as urgent for consistency.

**Comment by WestpacOpenBanking** [comment]
See also our comment in relation to documenting claims on #228.

**Comment by pcurtisrab** [comment]
Regional Australia Bank as a data recipient aligns with the normative standards. We feel that the inclusion of OIDC and FAPI in the standard is sufficient, such that no further statements regarding `nonce`, `s_hash` and `c_hash` are necessary in the Consumer Data Standard.

**Comment by perlboy** [comment]
For what it's worth, alignment with FAPI means that `state` in Request Object is optional. FAPI also doesn't require `c_hash` or `nonce` to be provided (although they are recommended).

These changes were first noted in July 2019 within the [FAPI cds-spec-analysis](https://bitbucket.org/openid/fapi/src/master/cds-spec-analysis/) which was also referenced in the [OIDF letter to the DSB](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/73) that the DSB broadly rejected at the time.

Of specific note is the following bullets within the current analysis document:

> - s_hash support is MANDATORY
> - state and nonce claims are MANDATORY and therefore essential
> - c_hash is REQUIRED in ID Token responses

Perhaps it would be prudent that all participants review the analysis and assess further alignment with the specification. The FAPI WG remains available for consultation by any participant including Data61/DSB who stopped engagement when the previous InfoSec lead left in January 2019.

**Comment by WestpacOpenBanking** [comment]
Westpac supports Commonwealth Bank’s proposed change and have also currently implemented in alignment with the normative references.

**Comment by brett-frollo** [comment]
Frollo have implemented this inline with the normative references, this does not have an impact on us

**Comment by perlboy** [comment]
> Frollo have implemented this inline with the normative references, this does not have an impact on us

If an Accredited Data Recipient have implemented in a way that is divergent to the DSB Standards (versus the FAPI ones), one must ask the question what technical verification the Government is doing when completing accreditation. I should stress here that I'm certainly not opposed to international alignment but the governing spec is the ones published by the DSB.

This situation is precisely the one predicted whereby some (most?) use international libraries for implementation resulting in a "standardisation" which is not documented. This may work for a small number of holders (<4) but becomes an exponentially more difficult problem to fix as more participants come online. It's also precisely what the UK has spent 3 years (and probably 3 years more) fixing retrospectively.

**Comment by CDR-API-Stream** [comment]
Hi all. Thank you to everyone who has provided feedback so far. The DSB held a review session of this issue today with participants that have impacted July 2020 go-live builds. This session included all major banks and ADRs. A summary pack is available [here](https://consumerdatastandards.gov.au/urgent-change-requests-cdr-5th-july-2020/).

The discussion reviewed the implementation of all banks and expected handling by ADRs. It is understood that all banks and ADRs are relying on the normative references and it would be clearer if the statements in the data standards referred back to the normative references.

In other words, banks are correctly returning these claims as part of the Authorisation endpoint response but they are not returning them in the ID Token from the Token endpoint unless the underlying normative references require it. 

## Changes proposed
It is proposed that the data standards be updated to remove the section describing these claims other than to say they are required to be in alignment to the normative references.

Before the DSB provides a recommendation to the chair on this issue it is requested that confirmation be provided by the impacted participants that the change proposed will not adversely impact their ability to implement for July.

^^ @pcurtisrab, @brett-frollo, @WestpacOpenBanking, @commbankoss, @NationalAustraliaBank, @anzbankau

**Comment by anzbankau** [comment]
ANZ aligns to the normative references, so is supportive of the change that leaves these claims optional in scenarios unless specified by the normative references.

**Comment by perlboy** [comment]
How did this become an urgent change when no-one was implementing them in the first place and why was it not considered and accepted when it was raised as part of the [CDS Spec Analysis](https://bitbucket.org/openid/fapi/src/master/cds-spec-analysis/) sent to every member of the Advisory Committee on August 13, 2019? Since the [DSB has chosen to only publish](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/73) it's response here's the original unabridged but email sanitised version:
![image](https://user-images.githubusercontent.com/4291448/83856784-6e25f580-a75d-11ea-865b-d04b8757af03.png)

What other changes have the DSB Standards made to underlying Standards that implementer's have ignored?

**Comment by jogu** [comment]
I personally strongly feel that all text that is merely restating requirements already present in the underlying specs should either be removed, or clearly marked as such - so that participants using products that are conformant with the underlying specs can have clarity as to what the CDR spec requires them to **additionally** do.

The current document appears to contain a mixture of restated and reworded underlying requirements and new CDR specific requirements, it's very hard to figure out which are which. It's especially hard to figure out the intention when the rewording of the underlying spec inadvertently changes the normative meaning.

**Comment by RalphBragg** [comment]
Just a note again on how this was tackled in other jurisdictions. Firstly, Changing or clarifying normative clauses of underlying specifications is done by engaging with those bodies that owns the specs. It’s very hard, if not impossible for AH implementations to get any support from their vendors if a spec suggests breaking requirements from underlying specs so if clarification is needed obtaining it from the body that owns the specification is the way to go.

Secondly, if a profile of an underlying spec needs to be created then just create a small delta document that calls out the clauses that need changing, justification for the change and a new normative example. This would make it much easier for a certification suite to be created and implementors to make their changes.

This would massively speed up delivery time, reduce security risk and equally importantly improve interop for DR who are most adversely going to be affected by differences in banks implementation caused by a mis interpreting the specifications.

Issues around interoperability and alignment with international standards is one of the questions that has been asked on Scott Morrison’s additional review - can we improve how Australia engages with and ensures its spec works internationally to help Australian DRs gain access to a wider market. A way we can help here is to ensure that wherever possible changes are kept small, are clearly identified as a delta from the international spec and that the Australian data community gets the support from international vendors and standards bodies.

Here to help.

**Comment by commbankoss** [comment]
Commonwealth Bank supports @CDR-API-Stream's proposed changes to have ID Token contents aligned with normative standards. This will not adversely impact our ability to implement for July.

**Comment by cdradr** [comment]
We agree with the suggestions that CDR spec should only specify the differences from normative standards and areas not covered by them. This has been very confusing experience for all participants already involved and can be simplified for all new participants coming in.

**Comment by NationalAustraliaBank** [comment]
NAB’s current implementation follows the guidance given by @CDR-API-Stream in Issue 221. We believe the resolution to this issue should be consistent with the proposed resolution to issue 228 by explicitly listing ID Token claims (s_hash, c_hash and nonce) as optional from the token endpoint.

**Comment by CDR-API-Stream** [comment]
A change to the data standards was [approved by the Data Standards Chair for inclusion in v1.4.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/137). 

This issue will be closed accordingly.
