### ISSUE TITLE
Request for clarification on authorization flow challenge

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#230]
# Request For Clarification
Commonwealth Bank is seeking clarification on the following with respect to the authorization flow:

- Is the customer expected to be challenged to log in by the ADH for every authorization?
- If so, is it mandatory for the ADR to supply prompt=login as a parameter to the authorization endpoint?
- If so, what are allowable values for the max_age parameter?

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss, thanks for the questions. 

1. Yes. The current expectation is that consumers must be prompted for login on every authorisation request. This is backed up by the consumer research that identified authentication with the Data Holder as an important element of the experience related to trust.
2. No. The ``prompt`` parameter is optional in the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html). The DH's authorisation server must always request consent and authentication.
3. ``max_age`` is also optional. The presence of ``max_age`` in the authorisation request will have no bearing on the DH because they will always require authentication for any subsequent authorisation request. The client cannot vary the authentication timeframe. Noting also that the related ``auth_time`` claim is already mandatory in the CDS for the ID Token response.

If @commbankoss or others have any views on the ``prompt`` parameter we'd welcome feedback.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
