### ISSUE TITLE
Adequacy of published performance requirements and data quality

### ISSUE THREAD

**Issue by DimitriSty** [ConsumerDataStandardsAustralia/standards-maintenance#233]
Xero has some concerns regarding the Performance Requirements published in the Data Standards section available on GitHub.

As a cloud-based online accounting software provider, timely access to transactional data is critical to the customer experience and is an ingrained customer expectation. Currently Xero makes the majority of customers’ daily transactional data available before 9am the following day.

Based on the published performance requirements, the volume of Xero customer transactions and a potential 4-8 hour processing window, this customer expectation could no longer be met.

Xero has been experiencing performance issues with the UK’s Open Banking APIs and has been working with the OBIE and banks directly for months to ensure we're aligned on customer expectations and minimal performance standards. Xero would welcome a similar conversation with Data61.

Another area of concern is the potential for low-quality data contained in the CDR APIs. Xero’s experience in the UK was that almost all the major banks delivered (and in some cases continue to deliver) a large amount of duplicates, missing transactions and ambiguous data. These issues have persisted for over 18 months.
Since 2019, Xero has seen a material increase in bank-feed related support cases coming through to our customer service team. This is almost entirely related to issues with Open Banking APIs. Again, Xero would welcome the opportunity to discuss our experiences and our customers’ expectations with Data61 and the ACCC.

**Comment by perlboy** [comment]
Is there a reason Xero is only just raising these concerns when [DP21](https://github.com/ConsumerDataStandardsAustralia/standards/issues/21) happened in April 2019?

As someone involved in the process back then, and even as recently as yesterday during the error handling workshop, getting potential Data Recipients (like Xero) to even attend/participate to begin with was a real challenge. Was participation just not a priority then? Why?

**Comment by DimitriSty** [comment]
Participating in multiple data sharing regimes at different levels of implementation means we are continuously building knowledge. As the UK matures, New Zealand develops and others formulate, I am keen to continue sharing knowledge with CDR stakeholders as appropriate. I’m confident this will highlight looming issues, such as those raised, to be managed carefully and proactively. I look forward to continuing to work constructively with you and other stakeholders into the future to together make the implementation of CDR as smooth as possible.

**Comment by perlboy** [comment]
@DimitriSty it's great that you've got involved now and I look forward to the valuable insight Xero can offer.

The main reason I asked is that implementer's have designed for the requirements that have been defined. When it comes to non functional requirements these are often tied to long running equipment purchases (for instance hardware load balancers and WAFs) making it non-trivial to change past a defined scaling point, quite possibly this is why Xero's experience in the UK is the way it is. The UK did not have the benefit of valuable experience like yours it's just a shame it wasn't given some time ago to help Australia avoid the pitfalls through learnings.

Moving the goal posts without any significant data flowing at this stage seems like it would delay delivery rather than help improve consumer outcomes.  I guess the point is that figuratively speaking the Endeavour already set sail some months ago and is about to make landfall but, unlike the original story, we know and embrace the fact the continent already has at least 6 "first nations" organisations and we should be respectful of their land (aka the massive IT build they are on the verge of completing).

**Comment by DimitriSty** [comment]
Hi Stuart,

Xero very much acknowledges and appreciates that any changes to non-functional requirements will require time and effort. We are not advocating for anything to be delayed.

Are you able to arrange a meeting where Xero can discuss our experiences and our customers’ expectations with Data61?

Many thanks,
Dimitri

**Comment by perlboy** [comment]
@DimitriSty You would have to [ask Data61](mailto:contact@consumerdatastandards.gov.au) because I haven't worked for them [since July 2019](https://consumerdatastandardsaustralia.github.io/engineering/updates/20190730_stuart_farewell.html).

As a participant in the ecosystem though I would say **this** location is the place to give your experiences. And by give experiences I mean, real world, statistical experience perhaps coupled with a change request to be put on the backlog not talking about talking about the experience.

Closed door meetings with participants is neither in the spirit of the principles, scalable nor conducive to discovering experienced outcomes across the ecosystem.

**Comment by CDR-API-Stream** [comment]
Hi @DimitriSty, thanks for the points raised above. They are important to consider as the standards evolve and we look a the practical implementation and use of them. With respect to performance and batch processing, the DSB would welcome input and one mechanism is to raise a [change request](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/new/choose).

We will be looking to consult on data quality and implementation consistency of Product Reference Data in future which will also be a useful avenue for consultation.

Further to this you can reach out via the https://consumerdatastandards.gov.au

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
