### ISSUE TITLE
Endpoint Versioning Clarification Needed

### ISSUE THREAD

**Issue by fahadbinrahat** [ConsumerDataStandardsAustralia/standards-maintenance#235]
Hi,

Need further clarification on endpoint versioning.

The endpoint versioning requirement states that "_Each end point will have multiple versions independent of other end points_." 

Trying to understand what is meant by 'independent' here?

If more than one endpoints are sharing a common object in model, for example '**BankingBalance**' is shared between '**/banking/accounts/balances**' and '**/banking/accounts/{accountId}/balance**'' according to published swagger, what is possible here in terms of independence for following scenario:

For example, Is it possible that representation of '**BankingBalance**' (_e.g. number of properties or data types_) in **version "5"** of endpoint '**v1/banking/accounts/balances**' is different from **version "5"** of endpoint '**v1/banking/accounts/{accountId}/balance**' ?

Thanks

**Comment by perlboy** [comment]
@fahadbinrahat Responses are versioned but yes, their composite parts may be the same (or may be different). The way [we have been solving it](https://github.com/bizaio/babelfish/tree/master/babelfish-cdr/src/main/java/io/biza/babelfish/cdr/models/payloads/banking/product) is to version every model all the way down the line while mapping the Response* payload to the Standards version numbers.

We have some [redocs](https://developers.biza.io/biza/_attachments/redocs/dsb-standards.html#operation/getProductDetail) which demonstrate this for V3 whereby the Response is an OpenAPI 3 `oneOf` of `ResponseBankingProductDetailV1`, `ResponseBankingProductDetailV2` or  `ResponseBankingProductDetailV3` which each contain direct references to individually versioned components which themselves then reference individual sub components. By way of simple example:

![image](https://user-images.githubusercontent.com/4291448/84620959-b7740300-af1c-11ea-8152-a0b195d4746d.png)

In this example we describe a V3 response for Get Product Detail which contains a `data` of `BankingProductDetailV3` which itself contains references to `BankingProductAdditionalInformationV1` and `BankingProductCardArtV1`. Each of these objects represent their respective versions across all of the specifications.

**Comment by fahadbinrahat** [comment]
Thanks for that @perlboy :)

Looks like multiple endpoints can safely refer to same object of a model version (looks like you also have these versioned models as a common library?)

I actually wanted to know if a unique version of a model (e.g. BankingBalanceV1) may have more than one implementations under one major version? , if yes, a global/common lib isn't way to go and would need to keep a copy for each endpoint...any thoughts?

**Comment by perlboy** [comment]
> Thanks for that @perlboy :)

Happy to help.

> Looks like multiple endpoints can safely refer to same object of a model version (looks like you also have these versioned models as a common library?)

We have a variety of things. 😄 But to answer your question while multiple endpoints might include overlapping models within their substructure each endpoint is versioned independently (difference between a generic model like `BankingBalanceV#` and `ResponseBankingProductByIdV#` vs. `ResponseBankingProductListV#`).

> I actually wanted to know if a unique version of a model (e.g. BankingBalanceV1) may have more than one implementations under one major version? , if yes, a global/common lib isn't way to go and would need to keep a copy for each endpoint...any thoughts?

Not sure I entirely understand your question but yes, we keep a `Response[Function]V#` per endpoint which then cascades down to versions below. Where the underlying model hasn't changed we don't increment it's version, meaning a certain Response* may recycle an underlying model while using a newly incremented one where it has altered. An example of this is BankingProductV2 which added `cardArt` while the rest remained unchanged. We released a new ResponseBankingProductList ([ResponseBankingProductListV2](https://github.com/bizaio/babelfish/blob/master/babelfish-cdr/src/main/java/io/biza/babelfish/cdr/models/responses/ResponseBankingProductListV2.java)) which linked to [ResponseBankingProductListDataV2](https://github.com/bizaio/babelfish/blob/c584f6ed5bcb92af694875f07262d6cb101e2187/babelfish-cdr/src/main/java/io/biza/babelfish/cdr/models/responses/container/ResponseBankingProductListDataV2.java#L36) which linked to [BankingProductV2](https://github.com/bizaio/babelfish/blob/c584f6ed5bcb92af694875f07262d6cb101e2187/babelfish-cdr/src/main/java/io/biza/babelfish/cdr/models/payloads/banking/product/BankingProductV2.java#L45) which added [BankingProductCardArtV1](https://github.com/bizaio/babelfish/blob/c584f6ed5bcb92af694875f07262d6cb101e2187/babelfish-cdr/src/main/java/io/biza/babelfish/cdr/models/payloads/banking/product/BankingProductCardArtV1.java#L40) (first version of card art) while retaining [BankingProductAdditionalInformationV1](https://github.com/bizaio/babelfish/blob/c584f6ed5bcb92af694875f07262d6cb101e2187/babelfish-cdr/src/main/java/io/biza/babelfish/cdr/models/payloads/banking/product/BankingProductAdditionalInformationV1.java#L39) (prior unchanged version of BankingProductAdditionalInformation).

As for "the way to go", there's always a few ways to solve. We considered using single models with all of the attributes but this introduces ambiguity in error handling ("Is it null because it's null or because it's a previous version"). We also considered a polymorphic response with Jackson subtypes but, while likely to function fine, this has complexities in understanding for newcomers and doesn't "light up" an IDE when there's a model change. In the end we opted with this approach because it allows`@Deprecated` tags to be added to retired models (causing IDE's to generate warnings but code not to bork) while we provide [BabelfishVersioner](https://github.com/bizaio/babelfish/blob/c584f6ed5bcb92af694875f07262d6cb101e2187/babelfish-converter/src/main/java/io/biza/babelfish/converter/support/BabelfishVersioner.java) to upgrade/download payloads between desired versions.

Hope that helps.

_Note: The DSB has, on occasionally, [seen fit to modify existing models](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/66) without incrementing their version. This has been somewhat frustrating to handle as it cascades down to breaking changes for developers using our libraries. Hopefully the DSB will stick with consistent incrementing of versions in the future._

**Comment by CDR-API-Stream** [comment]
Hi @fahadbinrahat thanks for the question.

@perlboy has provided good detail in response.

Regarding endpoint versioning, the intent is to manage the interface contract for each endpoint separately without having to update all endpoints if a given change only modifies one or a few endpoints or the data model change doesn't apply to some endpoints.

If a data model change has an impact to more than one endpoint they would be versioned accordingly. Note that doesn't guarantee that the endpoints would have the same version, just that it would increment versions of the associated endpoints.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
