### ISSUE TITLE
Relationship between BPAY fields and transactions is many to one.

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#24]
# Description
The relationship between BPAY fields and transactions is many to one. In particular a single transaction may be recorded for each day where there are BPAY payments with funds deducted.

# Area Affected
Definition of [BankingTransaction](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransaction) which is used by:

- [Get Transactions For Account](https://consumerdatastandardsaustralia.github.io/standards/#get-transactions-for-account)
- [Get Transaction Detail](https://consumerdatastandardsaustralia.github.io/standards/#get-transaction-detail)

# Change Proposed
We propose an approach that avoids breaking changes to endpoint definitions:

1. An optional **bpay** list is added within **extendedData** in [BankingTransactionDetail](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransactiondetail). Each element of this list would contain billerCode, billerName and crn. This list would contain all BPAY payees.
2. The elements **billerCode**, **billerName** and **crn** in [BankingTransaction](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransaction) should only be populated if there is a single BPAY payee and not be populated if there are 0 or greater than 1 payees.

**Comment by perlboy** [comment]
>     2. The elements **billerCode**, **billerName** and **crn** in [BankingTransaction](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransaction) should only be populated if there is a single BPAY payee and not be populated if there are 0 or greater than 1 payees.

Highlighted from July 15, context of multiple payment providers in (https://github.com/ConsumerDataStandardsAustralia/standards/issues/73#issuecomment-511268647) 

> On BankingTransaction, **overloading of the base object** is occurring rather than using the uType convention followed elsewhere. Specifically of note is that BPAY payments (a trademarked and commercially attached payment provider) have been granted exclusivity over **generically named attributes notably billerCode, billerName and crn**. This precludes an alternate payments provider using these global attributes and arguably provides a commercial advantage to the incumbent. 

I don't see the reason for including any of these attributes in `BankingTransaction` in the first place, uType of `bpay` and any others would be suitable, perhaps with a "default payment detail" in `BankingTransaction`.

**Comment by CDR-API-Stream** [comment]
After following up this issue with the author the problem is understood to be as follows:

* There are multiple distinct BPay transactions that occur in a single dat
* Due to the way these payments are processed they are aggregated and only a single "Daily BPay Transactions" transaction is recorded against the account with the additional detail on the individual transactions held in another system
* This results in a single transaction with no BPay biller that is linked to a series of separate transactions of different values from the same source account

In essence, this is an example of roll up transactions where a single entry is recorded but this is an aggregation of a series of related transactions.  This scenario is common in traditional batch processing scenarios.  Another example could be payroll transactions.

There are potentially many of these scenarios that could be encountered.

In response to this there are two options available that could be considered on which feedback would be welcome.

## Option 1 - Single transaction
In this option only the aggregate transaction is presented.  The BPay biller fields would not be populated and the additional, lower level information, would not be made available.

## Option 2 - Additional detail
This option aligns with the change proposed in the original issue description.  The additional detail would effectively be a list of the sub-transactions using a similar structure to the existing transaction structure.  This would facilitate this scenario but would also facilitate other situations where non-BPay payments are aggregated.

Feedback on these options (or others that could be proposed) are welcome.

**Comment by anzbankau** [comment]
ANZ's preference is Option 1

**Comment by CDR-API-Stream** [comment]
Based on the discussion last Wednesday that generally aligned with ANZ's feedback above the recommendation will be as follows:
- Guidance for aggregated transactions will be added to the standards but no standards change will be made
- A maintenance issue to address aggregated transactions will be added for consideration in a future iteration

**Comment by WestpacOpenBanking** [comment]
Westpac supports either Option 1 or Option 2. We suggest adopting Option 1 now and more fully considering Option 2 in relation to business accounts at a later date.

**Comment by NationalAustraliaBank** [comment]
NAB supports Option 1 for current standards. This issue should be revisited at a later date as more complex businesses and products are introduced into the regime.
