### ISSUE TITLE
'SHOULD' for access token revocation

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#240]
# Description
We request that this change be treated as urgent. Note that significant previous discussion has occurred in relation to this issue through [#197](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/197). Much of the description below is a copy of our comment on that issue.

Presently the data standards require that data holders MUST support access token revocation. Westpac’s implementation is based on JWT access tokens. These are stateless and only checked by the resource server. Use of tokens of this type is currently implied by the CDS standards and the FAPI normative references as [cited](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/197) by @cdswizard. Mandating support for the revocation of access tokens is not aligned with this approach.

RFC7009 [does not mandate support for this reason](https://tools.ietf.org/html/rfc7009#section-2), and discusses this in the [implementation note](https://tools.ietf.org/html/rfc7009#section-3). We suggest that the statement “Revocation of Refresh Tokens and Access Tokens MUST be supported.” Is amended to align with RFC7009 “Implementations MUST support the revocation of refresh tokens and SHOULD support the revocation of access tokens” as an urgent matter.

# Area Affected
Describe the area of the standard that is proposed to be amended.  This could be one or more API end points or a specific section of the information security profile

# Change Proposed
A detailed description of the specific change (or options for change) proposed.  The more specific the proposal the easier investigation and consultation on the issue will be

**Comment by biza-io** [comment]
On the basis of international standards alignment and no apparent extended risk due to short lived access tokens Biza.io supports alignment with RFC7009.

**Comment by biza-io** [comment]
We note with 2 days prior to July 1 this issue was never closed and request the DSB provide an update on the feedback from the ACCC regarding the risk of 10 minute token lifespans as per the [DSB action taken on 7 October 2020](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-5:-Iteration-Scope-Review:-Agenda-&-Meeting-Notes-(7th-October-2020)):

![image](https://user-images.githubusercontent.com/66460446/123745290-6a7a8900-d8f3-11eb-8f69-f213e3ed49ba.png)

We wish to highlight that, despite supporting this change, Biza.io has implemented revocation for it's own JWT's but is aware of implementations which are not currently complying with this part of the specification, likely failing the CTS but also likely being admitted into the ecosystem. 

As the change required to achieve compliance with the Standards is an architectural anamaly we request the DSB provide the above feedback it had an action for and provide guidance on whether _any_ participant should be admitted into the ecosystem when they fail to meet the specification.

**Comment by biza-io** [comment]
As this task has now been moved to Iteration Candidates for DSB Maintenance Iteration 8 we request the DSB provide an update on the feedback from the ACCC regarding the risk of 10 minute token lifespans as per the DSB [action taken on 7 October 2020](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-5:-Iteration-Scope-Review:-Agenda-&-Meeting-Notes-(7th-October-2020)#notes):
![image](https://user-images.githubusercontent.com/66460446/125732696-223aa992-432f-4ec9-af22-e0e7508e9d50.png)

We wish to highlight that, despite supporting this change (above), Biza.io has since implemented revocation for it's own JWT's but is aware of implementations which are not currently complying with this part of the specification and likely failing the CTS particularly around revocation testing scenarios.

As the change required to achieve compliance with the Standards is an architectural anomaly (ie. making stateless JWTs stateful) we request the DSB provide the above feedback it had an action for and provide guidance on whether existing participants are currently active within the ecosystem in non-compliance with the current Standards.

**Comment by CDR-API-Stream** [comment]
Based on feedback and a review of the overall security posture of the CDR regime we do not feel that there is a strong enough case to justify this change and feel retaining a MUST position helps ensure consistency of capability for ADRs building implementations that do not require special handling for subsets of data holders. The DSB also note from the regulator that the majority of data holders have implemented this standard.

In addition, the data standards require the revocation of access tokens as a control to ensure ADRs can invalidate any active access tokens in the event of security concerns to cease data collection. It is noted that [Decision 182](https://github.com/ConsumerDataStandardsAustralia/standards/issues/182#issue-890770691) recommends an Attacker Model be developed for the CDR that will address controls defined in the Information Security profile.

The DSB have verified with the Rules team and regulators that this position is consistent with the security needs of the regime and aligned to policy intent.

**Comment by CDR-API-Stream** [comment]
This change request is not adopted and has been closed at the conclusion of [Maintenance Iteration 8](https://github.com/ConsumerDataStandardsAustralia/standards/issues/202)
