### ISSUE TITLE
Product Data: Overlapping Tiers & additionalValue

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#244]
# Request For Clarification
Some Holders are presenting deposit rates with tiers with time ranges. For instance 48-60 months, 60+ months. However, for 60+ months the `additionalValue` is set to P60M. The challenge with this is that for 60+ months the "time the rate is fixed for" is any timespan larger than 60 months but since it is a mandatory field and [bounded time ranges](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/5#issuecomment-555769600) are not supported the result is this value overlaps.

For example:

```
 {
    "depositRateType": "FIXED",
    "rate": "0.01",
    "calculationFrequency": "P1Y",
    "tiers": [
      {
        "name": "Amount",
        "unitOfMeasure": "DOLLAR",
        "minimumValue": 100000,
        "rateApplicationMethod": "WHOLE_BALANCE"
      },
      {
        "name": "Term",
        "unitOfMeasure": "MONTH",
        "minimumValue": 48,
        "maximumValue": 60
      }
    ],
    "additionalValue": "P60M"
  },
{
    "depositRateType": "FIXED",
    "rate": "0.01",
    "calculationFrequency": "P1Y",
    "tiers": [
      {
        "name": "Amount",
        "unitOfMeasure": "DOLLAR",
        "minimumValue": 100000,
        "rateApplicationMethod": "WHOLE_BALANCE"
      },
      {
        "name": "Term",
        "unitOfMeasure": "MONTH",
        "minimumValue": 60
      }
    ],
    "additionalValue": "P60M"
  },
```

This makes filtering off `additionalValue` result in overlapping data. I suspect this is because `additionalValue` is mandatory.

Should Recipients presenting this data effectively ignore `additionalValue` and use the time based tier when it exists?

**Comment by anzbankau** [comment]
@perlboy ,

A tier for a 'FIXED' `BankingProductDepositRate` that provides the term (with `unitOfMeasure` = ['DAY'|'MONTH'|'YEAR'] and ISO 8601 Durations in the `minimumValue` and (optionally) `maximumValue`) should override the rate's `additionalValue`. But, as you correctly state, this is effectively a mandatory property as it is Conditional due to the 'Use of additionalValue Field' value for the enum.

We can raise a change proposal to append a sentence to the 'Use of additionalValue Field' so that it reads:
___
'The period of time fixed. Formatted according to ISO 8601 Durations. This is not required when a tier provides the qualifying period for the rate e.g. `minimumValue` = 'P3M' and `maximumValue` = 'P6M'.
___

This effectively reverts `BankingProductDepositRate.additionalValue` for a 'FIXED' rate to Conditional.

In the interim, however, some sort of override mechanism will be required. So, yes, in answer to your question.

**Comment by perlboy** [comment]
See #354.
