### ISSUE TITLE
Deferral of PAR obligation date

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#246]
# Description

Commonwealth Bank is fully supportive of the adoption of PAR.
However, we believe it should not be in obligation for November given that:
- PAR doesn’t deliver any additional functionality to CDR  in November;
- PAR is beneficial for future consent changes (e.g. fine-grain consent which will possibly come in next year); 
- Vendors that are currently used by the initial group of the Data Holders don’t currently support PAR and implementing it will require custom built effort; and
- Existing request object can be used to transport sharing_id

# Area Affected
[End Points](https://consumerdatastandardsaustralia.github.io/standards/#end-points)

# Change Proposed
We propose to move the adoption of PAR from November to a future date (e.g. February 2021) to allow enough time for vendors to provide support for PAR and/or Data Holders to properly implement it.
This change will not affect the functionality scoped for November 2020 (e.g. joint accounts or concurrent consent).

**Comment by mperryau** [comment]
Ping Identity supports this proposal and notes that we recommended a similar approach to PAR support [previously](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-611329485).

**Comment by biza-io** [comment]
Biza•io supports this primarily because, noting [it's representatives](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-611373090) support of prior [OIDF submissions](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-611364287), the DSB has not yet clearly articulated a "target state" that considers the long term flexibility required within the ecosystem. 

Once defined the adoption of individual specifications should be one of timing not vice versa.

We have customers (non Big 4) who intend to be first to market and the lack of clarity is introducing unnecessary uncertainty to them achieving their goals.

**Comment by jogu** [comment]
> There is no vendor support for PAR at the moment 

This isn't true. There are multiple vendors with PAR support. 

That said, I can see some reasons in favour of moving the deadline back. (I do acknowledge there are also multiple vendors that don't support PAR right now.)

I think this is probably what's intended already, but any move to delay the deadline should also leave data holders free to add PAR support prior to the new deadline.

**Comment by anzbankau** [comment]
ANZ support Commbanks call for the removal of PAR for the November release. 
We fully support the introduction at a later stage and feel that it has potential to be a great benefit to the CDR but for November we agree that it does not add any functional value that cannot be achieved elsewhere. 
Holding off on this will allow vendors to evolve there offerings to support PAR and also give participants appropriate time to develop solutions. 

We also support the call from Biza.io to see a roadmap articulating a target state for the ecosystem, we are aware that this is constantly changing but calling out some of the major focus items would help our designs and ensure we don’t build in too much tech debt. 
Obviously this isn’t the highest priority right now but something we can do in the future perhaps through some working groups including ADH and ADR participants.

**Comment by commbankoss** [comment]
> > There is no vendor support for PAR at the moment
> 
> This isn't true. There are multiple vendors with PAR support.

Thanks @Jogu. We’ve adjusted our post to say:

"Vendors that are currently used by the initial group of the Data Holders don’t currently support PAR"

**Comment by mark-nienaber** [comment]
ForgeRock supports this proposal for the reasons given.

**Comment by NationalAustraliaBank** [comment]
NAB supports the proposal to defer the PAR requirement from the November release for the reasons outlined above by CBA and ANZ.  We also support the call for a roadmap articulating a consent target state post the November release.  Such a roadmap will not only assist industry participants ‘plan ahead’ designs with confidence but also ensure that there is appropriate consideration of long-term requirements.
Furthermore, assuming PAR requirement is deferred from the November release, then NAB would like to confirm how this would impact the Arrangement ID handling - according to the current CDS v1.3.0, Arrangement ID can only be provided via the PAR endpoint.

**Comment by WestpacOpenBanking** [comment]
Westpac supports the proposal put forward by Commonwealth Bank except that we recommend that the implementation date be tied to the support date of major IAM vendors, rather than an arbitrary implementation date. We are supportive of the eventual adoption of PAR. This position is consistent with our [February](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-587993724) and [April](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-611258759) feedback on concurrent consent including:

* Our statements that it would be unlikely that we would be able to support the use of Pushed Authorisation Requests in November due to a lack of vendor support. 
* The importance of vendor support to minimize security and implementation risks.

The DSB also[ stated in consultation](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-604251809) that they’d welcome feedback from IAM vendors in relation to the supportability. Feedback was provided by vendors including [ForgeRock](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-611320895), [Ping Identity](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-611329485) and [RADIAM](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-604251809) which addressed this issue. Longer term, we [endorse recommendations](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99#issuecomment-611364287) that the DSB collaborate and align with FAPI 2.0 development and staged implementation timeframes.

**Comment by jogu** [comment]
> Westpac supports the proposal put forward by Commonwealth Bank except that we recommend that the implementation date be tied to the support date of major IAM vendors, 

I'm going to be pretty brutal about this, but I'd recommend the opposite position - it is absolutely necessary to pick a relatively arbitrary (but very achievable) date for implementation of PAR. Major vendors can be very reluctant to implement new standards unless given real deadlines, that was clearly seen in the UK ecosystem. 

Again being very brutal about it, If DH's have adopted products that don't have a roadmap for supporting necessary features for CDR (or where the architecture does not allow for individual unsuitable components to be switched out for better suited replacements if that becomes necessary) that is very much a problem for the data holders to solve and must not delay evolution of the entire ecosystem.

The only extra note I'd add is that with new features like PAR it's even more important to ensure that automated testing & certification is available and used prior to DR & DHs putting PAR into production. Debugging & fixing such issues in post-deployment is really not fun. The OpenID Foundation already has some testing for PAR under development. (For the purposes of disclosing potential bias, one of my roles is working in the OIDF Certification Team and I've also worked with several vendors.)

Actually picking a date requires further discussion. I'd say there's general agreement that it should be post-November, and early 2021 as commbankoss proposed is not unreasonable. Data holders should be encouraged to allow optional use of PAR prior to any deadline.

>  Longer term, we endorse recommendations that the DSB collaborate and align with FAPI 2.0 development and staged implementation timeframes.

I 100% agree with this. This kind of collaboration is vital to getting a good result for everyone. I'd also note that the Australian data holders themselves can absolutely participate directly themselves in finalising FAPI 2.0, and should be encouraged to do so.

**Comment by cdradr** [comment]
In case it matters:
it’s much easier to support PAR for the Data Recipients, than for the Data Holders. Just an extra API call with the same parameters.

And it’s easy to support both at the same time: current authorization request and PAR. Just check the server metadata.

@jogu, did you say that PAR testing and certification is already available? If not, when do you think it will be available?

**Comment by jogu** [comment]
> @jogu, did you say that PAR testing and certification is already available? If not, when do you think it will be available?

I'd expect an initial version at least within the next few months.

**Comment by spikejump** [comment]
Intuit supports @commbankoss proposal of deferring the implementation of PAR by both DH and DR by November 2020.

**Comment by mattp-rab** [comment]
> The only extra note I'd add is that with new features like PAR it's even more important to ensure that automated testing & certification is available and used prior to DR & DHs putting PAR into production. Debugging & fixing such issues in post-deployment is really not fun. - @jogu 

+1

While it should be relatively easy enough for us to implement ADR PAR requirements, we would prefer a CTS to first be available before the introduction of new features/standards obligations so as to prevent further time consuming defect management processes.

**Comment by SlatsFR** [comment]
Is there a resolution to this issue? It would be useful to all concerned to have a clear path forward on requirement, as implementation and testing will need to start shortly in order to meet the November deadline if it isn't deferred.

**Comment by CDR-API-Stream** [comment]
Hi @SlatsFR and @mattp-rab, thanks. Data Holders are required to implement PAR by November 2020. This said, [Noting Paper 136 - November 2020 Consent Transition Guidance](https://github.com/ConsumerDataStandardsAustralia/standards/issues/136) describes how ADRs can handle the transition if one or more Data Holders does not support PAR in November timeframes.
