### ISSUE TITLE
ADR Revocation Endpoint

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#247]
As requested in registry [issue #82](https://github.com/cdr-register/register/issues/82#issue-583394152), Commonwealth Bank is  re-posting our proposal with minor updates to focus on ADR revocation endpoint and consent revocation notification.

**Proposal 1 : November Timeframe**

Commonwealth Bank does not believe that either ADRs need to host a token / consent revocation endpoint..

Our preferred approach for consent revocation notification (November Timeframe):

- ADRs are not required to host a token revocation endpoint (or any APIs).
- ADRs MAY call the introspection endpoint when a customer accesses the ADR Dashboard to ensure the correct view of consent status is shown. The alternative is to accept that after an ADR outage, the ADR dashboard may be out of sync until the next time the ADR attempts to use a now revoked Refresh Token.
- ADRs will trigger data deletion / de-identification process upon:
- Error as a result of attempting to use a revoked Refresh Token. Either through token endpoint or introspection endpoint.

_Pros:_
- Same approach is used for short (<7 days) and longer ADR outages current approach only calls for polling for 7 days
- No store and forward mechanisms required. Lower complexity and less edge cases.
- Removal of ADR revocation API removes need to ADRs to host authenticated APIs:
- A better security posture for the ecosystem.
- Less components for current and future ADRs to build and manage.
- Compatible with upcoming consent changes.
- Less components for current and future ADHs to build and manage as no need for store and forward

_Cons:_
- Some ADRs may wish to do an extra check on load of dashboard to ensure consent status is in sync.
- May need to enhance error handling on call to token endpoint to handle RT having been revoked.
- Some ADRs might need to make additional introspections calls if their use case doesn’t require daily refresh.

**Proposal 2 : Future Milestone Timeline**
For a future milestone release, we recommend the addition of these changes:

- In addition to revocation notification mechanisms available above:
- ADH to provide a new endpoint - bulk revoked arrangement API. This endpoint will return a list of revoked arrangements in the last X period (can be called every hour, for example).
- ADR will call the bulk revoked arrangement API
- Periodically (say 1/hr)
- When a customer loads the ADR dashboard

_After Extended ADR Outage:_
- After an outage, an ADR should call the bulk revoked arrangement API to understand which arrangements have been revoked while they were down.

_Pro:_
- In addition to Pros of the option above, additional optimisation is introduced to simplify token revocation for ADRs.

_Cons:_
- DHs need to host an additional API

**Can we please request both DH and ADR feedback on our proposals in order to understand if there are shortcomings we haven't considered.**

**Comment by cdradr** [comment]
For the sake of Data Recipients (and CDR adoption) please remove the requirement for Data Recipients to host APIs. This will also improve overall security (current design is questionable).

**Comment by NationalAustraliaBank** [comment]
NAB supports Proposal 1 (November Timeline) by CommBank above.  We believe this provides a technically simpler, more resilient solution (eg. ADR's would not need to host an authenticated endpoint) compared to the extended DH retry mechanism proposed in [Issue 119](https://github.com/cdr-register/register/issues/119).  
 
The approach proposed by CBA can also assist in simplifying the transition period across July/Nov.
  
Should this proposal not be accepted, then NAB would like to seek clarification on how the transition across the July / Nov cutover period is expected to operate across both ADRs and DH’s.

**Comment by spikejump** [comment]
Intuit supports @commbankoss proposal not having Data Recipients hosting revocation API.

**Comment by anzbankau** [comment]
ANZ supports CommBank's proposal 2 for future milestones and the introduction of a bulk revoked arrangement endpoint.
The design would need to be fleshed out to include things like expected NFRs on the ADH and the length of time data is hosted on the endpoint, but this can be worked through at a later stage.

**Comment by WestpacOpenBanking** [comment]
As outlined above, the future state presented in this proposal has a number of advantages over the status quo:
* Data Recipients don’t need to host token revocation endpoints nor revocation notification endpoints. This simplifies implementations and improves security. 
* Many [complexities](https://github.com/cdr-register/register/issues/82) related to unavailability polling under the current push approach are avoided. This reduces implementation complexity for data holders.
* The approach will more robustly allow from recovery from long outages.
However, there are policy considerations which may affect the viability of the proposal in the short term. For example it is unclear what latency is acceptable for receipt of consent revocation notifications? Note that the data recipient would immediately become aware if they tried to access additional data or when the customer loads their dashboard – depending on the specifics the primary effect of this increased latency from a customer perspective may be a delay in the triggering of deletion and/or deidentification.

Thought is also needed as to how this proposal would apply in the case of joint accounts particularly in relation to the suggested approach for synchronously checking the state of a consent may be inadequate in that case.

**Comment by brett-frollo** [comment]
Frollo supports Proposal 1 and believe this is a good error handling approach to implement regardless. We have currently implemented this logic in our solution today, as a fallback incase the revocation endpoint call is missed somehow.

However, we note that if an ADR does not have a daily refresh mechanism, and instead relies on Consumer activity in their app, it may require frequent polling of all consents in order to delete CDR Data in a timely manner. For example, if an ADR has thousands of consents it would require them to poll the introspection endpoint for each consent every hour (or day, depending on how quickly you want to delete redundant CDR Data).

**Comment by pcurtisrab** [comment]
We seek to clarify why any change is necessary at all. We already have a working solution and we do not see maintaining this endpoint as a signficant cost. There is a significant cost to us and risk to the ecosystem however, in regard to unnecessary changes. We consider that a 7 day outage is very unlikely. With regard to security tisk, we seek clarification as to what example scenarios are considered as high risk in the current state?

With regard to the given proposals we provide the feedback below. If it is a consensus that a change is absolutel needed, we think Proposal 2 seems like a much better overall solution, and rather spend the effort to implement a less than ideal solution now when we already have a working one, we would prefer to aim for Proposal 2 directly.

### Proposal 1

There are some shortcomings:
1. It does not seem like introspection of the refresh token is the best place to understand a revocation state.  The introspection endpoint method proposed does not allow the data recipient to distinguish between a revoked state and a stale state (i.e. where there is no current refresh token but the sharing duration is still in effect - this is possible when refresh token cycling is in effect). Even if the introspection endpoint was augmented to show the status of the arrangement linked to the refresh token, it would not be reliable if a data recipient does not have the current refresh token (due to failed refresh token cycling - see issue #219). Given the arrengement endpoint is the place for revocations going forward, it seems logical for the arragement endpoint to be the source of truth for revocation state.
2. This has potential to limit the timeliness and appropriateness of communications to the consumer (i.e. the data recipient can not know if they should communicate to the customer as if they revoked the consent or if the refresh token simply expired). The revocation endpoint gives ADRs more control over communications.

### Proposal 2

This proposal seems much superior to proposal 1, even though it shares shortcoming 2 above. Note that it would require some change in relation to how client authentication happens at that endpoint. At the moment, the standards say a valid access token should be used, but it rather seems that Client Authentication should be used.

**Comment by WestpacOpenBanking** [comment]
Noting that we are not able to accommodate new build. Westpac supports the proposed approach for November.

We agree that there is an eventual need for a bulk revocation endpoint under this approach. The future state presented in this proposal has a number of advantages over the status quo:

* Data Recipients don’t need to host token revocation endpoints nor revocation notification endpoints. This simplifies implementations and improves security. 
* Many [complexities](https://github.com/cdr-register/register/issues/82) related to unavailability polling under the current push approach are avoided. This reduces implementation complexity for data holders.
* The approach will more robustly allow from recovery from long outages.

We note that there are policy considerations in relation to this proposal. For example it is unclear what latency is acceptable for receipt of consent revocation notifications? Note that the data recipient would immediately become aware if they tried to access additional data or when the customer loads their dashboard – depending on the specifics the primary effect of this increased latency from a customer perspective may be a delay in the triggering of deletion and/or deidentification.

Thought is also needed as to how this proposal would apply in the case of joint accounts particularly in relation to the suggested approach for synchronously checking the state of a consent may be inadequate in that case.

**Comment by commbankoss** [comment]
On a Maintenance Iteration call 15/10/2020 the DSB said there was no wide support for the proposal in #247 ADR Revocation Endpoint.
We are a little confused by this statement as currently issue #247 (specifically the removal of ADR revocation endpoint) has support from the following participants:

- [CDRADR](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/247#issuecomment-648574074)
- [NAB](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/247#issuecomment-649221854)
- [spikejump (Intuit)](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/247#issuecomment-650851461)
- [Westpac](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/247#issuecomment-652773547)
- [brett-frollo (Frollo)](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/247#issuecomment-653269963)

If the proposal is rejected and standard stays as is, we are concerned that the result would be:

- Unnecessary complexity for ADRs (hosting APIs and authenticating API consumers, potentially without dedicated security infrastructure);
- Unnecessary complexity for ADHs (retry patterns, store and forward); and
- Security threats associated with the current design: current ADH to ADR API calls are not protected by FAPI and OAuth Best Current Practices. We are unsure if this flow was included in the last security review - and what the results of that review were.

**Comment by perlboy** [comment]
> On a Maintenance Iteration call 15/10/2020 the ~~DSB~~ _one individual_ said there was no wide support for the proposal in #247 ADR Revocation Endpoint.

For the record, you can add me onto the list of supporters for the proposal.

**Comment by jogu** [comment]
I also support the proposal. There's an awful lot of complexity and I'm pretty unclear as to the security model and assumptions. I'm having trouble following the CDR specs these days, there seems to be increasing number of changes made at speed and batched together - it seems like it would be better to have a public review period where the proposed text is available for review **before** it's added to the published standard.

**Comment by RalphBragg** [comment]
Likewise i support this proposal aside from @jogu's points I'd also like to ask the body to clearly articulate why a different set of security requirements for ADRs should be different from ADHs'. Surely once a ADR has actually received the data if they want to then 'hold' the data and make it subsequently available by their own APIs they are logically therefor a ADH and should be subject to the same security requirements as the original ADH. I would be keen to understand the justification for different security profiles if this is not the case.

**Comment by CDR-API-Stream** [comment]
As discussed during the 5th maintenance iteration the ADR Revocation Endpoint is required to communicate consent withdrawal actions arising via the DH dashboard to the ADR. Also discussed during the iteration is that any consideration to a consent status or consent introspection API hosted by DHs should be raised as a specific change request. This change has not been approved [for inclusion in v1.7.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159). 

This issue will be closed accordingly.
