### ISSUE TITLE
Clarification on Get Product Detail V2 details missing

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#248]
# Request For Clarification
Commonwealth Bank is seeking clarification on Get Product Detail V2.
When Comparing [Get Product Detail V1](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-product-detail-v1.html#get-product-detail-v1) and [Get Product Detail V2](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-product-detail-v2.html#get-product-detail-v2) it seems that V2 is missing the various detailed sections that V1 contains.
We believe this may be a documentation defect. Could this be verified?

**Comment by nils-work** [comment]
Hi @commbankoss 
I can see that V2 is missing the detail in that link for the deprecated version, but if you still need it, I believe all the info is in the [1.2.0 version archive](https://consumerdatastandardsaustralia.github.io/standards/index.html#archives).

**Comment by CDR-API-Stream** [comment]
Thanks @commbankoss this is a documentation defect which will be resolved in the next release.

**Comment by CDR-API-Stream** [comment]
Hi @commbankoss this issue has been prioritised in the v1.4.0 release. A fix has been made to add the missing schema elements in the markdown used to generate the documentation.

**Comment by nils-work** [comment]
Hi @CDR-API-Stream
As was raised in the maintenance call today, this [original issue](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/248#issue-641752012) appeared to have been fixed in 1.4.0 but the link from the obsolete [v2 page](https://consumerdatastandardsaustralia.github.io/standards/includes/obsolete/get-product-detail-v2.html#get-product-detail-v2) to the obsolete v1 page remains broken.

FWIW, the link from the [current version](https://consumerdatastandardsaustralia.github.io/standards/#get-product-detail) (v3) to the obsolete v1 page is fine.

**Comment by CDR-API-Stream** [comment]
This issue has been resolved in v1.4.0
