### ISSUE TITLE
x-fapi-customer-ip-address - What is the expectation for an unauthenticated call?

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#250]
# Request For Clarification

The [specifications](https://consumerdatastandardsaustralia.github.io/standards/#http-headers) state that the _x-fapi-customer-ip-address_ is "**Not to be included for unauthenticated calls.**"

> The customer's original IP address if the customer is currently logged in to the data recipient. The presence of this header indicates that the API is being called in a customer present context. Not to be included for unauthenticated calls.

It does not prefix with the Not to be included with a MUST or SHOULD.

If a TPP makes a call to the Get Product API  and they send the x-fapi-customer-ip-address should this request be rejected or can we lenient to the caller and ignore this IP address and process the request and return the relevant data.

I looked at the Big 4 banks implementation, they are forgiving if we specify the **x-fapi-customer-ip-address** for an "unauthenticated API" such as Get Products.

Appreciate some clarifications.

**Comment by CDR-API-Stream** [comment]
Hi @bmangalaganesh the intent of the ``x-fapi-customer-ip-address`` header is for customer-is-present calls - in other words, the consumer is logged in and is in attendance (using the ADR app) when the call is made.

The presence of the header denotes that the consumer is present when the call is made.

The reason it doesn't apply for unauthenticated endpoints (and the other ``x-fapi`` headers) is because they are public APIs that do not apply to the FAPI profile.

**Comment by bmangalaganesh** [comment]
Thanks.
I am trying to understand the expected behaviour.
If the TPP Software products send the `x-fapi-customer-ip-address`  for  an un-authenticated endpoint, am I well within my rights to reject the request with a  HTTP Status code of `400  Bad Request` based on the 
> Not to be included for unauthenticated calls

**Comment by CDR-API-Stream** [comment]
Hi @bmangalaganesh if the ADR software product sends the header it should be ignored not rejected.
