### ISSUE TITLE
Clarification to NFR public traffic threshold for other ADI's with multiple brands

### ISSUE THREAD

**Issue by DG-TMBL** [ConsumerDataStandardsAustralia/standards-maintenance#264]
# Description
In the standards, NFR Traffic Thresholds state:
For Public traffic (i.e. traffic to unauthenticated end points) the following traffic thresholds will apply:
300 TPS total across all consumers (additive to secure traffic)

At the Data Holder Forum on 9/7/2020 it was confirmed that 300TPS applies to externally facing API links, meaning that for a Data Holder who supports multiple brands with the same backend system, 300TPS for each brand would need to be supported.  

At TMBL, we have 4 brands, each with their own external API link, which means we need to be able to support 1200TPS through the same infrastructure.  Supporting this, may require significantly and costly uplift in Infrastructure, when the performance limit would not reasonably be reached in practice. 

Based on previous feedback from the DSB via the data holder forum, it was recommended that we have links for each brand, to align with what the consumer would expect.

An alternative option for TMBL may be support a single link (at the corporate level). Each brand could be retrieved via the same link using the brand filter, and then only 300TPS would be required. This approach does not support the externally facing brands in terms of discovery and product comparison. We agree with the previous feedback from the DSB, that the links should be for each brand.

Further to this, and not directly of concern to TMBL, is the Customer Owned Banks & Credit Unions who use shared infrastructure, hosted by bureaus. Those hosting provider bureaus will need to support 300TPS for each of their data holder clients, which could very quickly become out of hand. 

# Area Affected
Non Function Requirements - Traffic Thresholds.
For Public traffic (i.e. traffic to unauthenticated end points) the following traffic thresholds will apply:
300 TPS total across all consumers (additive to secure traffic)

# Change Proposed
Delivering multiple external facing brands (to the benefit of consumers in niche markets) is a business decision that should not be impacted by additional traffic threshold requirements.

We seek clarification in the wording of the NFR Traffic Thresholds, so that in our situation with multiple brands we should need to support 300TPS collectively across all brands for public traffic.

**Comment by DG-TMBL** [comment]
For some further context on the above, here is the Q&A from yesterdays Data Holder Forum:

These questions (for data holder forum) are about the performance & traffic threshold NFRs, specifically for the get-products and get-product-details APIs. 

In the GitHub, the applicable NFRs are 1500ms response time for unauthenticated end points, and 300TPS traffic threshold.  It states that the threshold is “total across all consumers”.

From this, we understand that we need to respond within 1500ms and within that 300TPS threshold.  Any queries over 300TPS can have degraded performance, or error 429 Too Many Requests.

Question 1 – Does the 300TPS apply individually to both get-products and get-product-detail, or is it collective?  For example (and I realise this scenario is highly unlikely), if get-product was receiving 299TPS, and get-product-detail was receiving 299TPS –  If the threshold is individual, then we need to provide full performance to all of these requests.  If collective, then we can provide degraded performance, or error code 429 for 298 of these transactions on a first in first out basis.  

Question 2 – If a data holder has multiple brands that all reside on the same core banking system, with the same API backend, does the 300TPS apply individually to each brand, or is it collective across all brands?  For example, if brand #1 is at 299TPS and brand #2 is at 299TPS – If the threshold is applicable to the brand, then we need to provide full performance to all of these requests.  If collective, then we can provide degraded performance, or error code 429 for 298 of these transactions on a first in first out basis. 

As a data holder with 4 brands, answers to these questions will provide clarity on whether we are trying to achieve:
-	300TPS – for both API’s covering all brands.
-	600TPS – 300 for get-products + 300 for get-product-details (i.e. 600 covering all brands).
-	1200TPS – 300 for both API’s, repeated for each brand.
-	2400TPS – 300 for get-products + 300 for get-product-details, (i.e. 600 repeated for each brand).

Note:  We plan to publish specific API endpoints for each brand in-line with the standard, however they will all hit the same APIs on the backend.
-	Brand 1 - TMBL identified this link as suspicious, click here to analyse.brand1/cds-au/v1/banking/products
-	Brand 2 - TMBL identified this link as suspicious, click here to analyse.brand2/cds-au/v1/banking/products
-	Brand 3 - TMBL identified this link as suspicious, click here to analyse.brand3/cds-au/v1/banking/products
-	Brand 4 - TMBL identified this link as suspicious, click here to analyse.brand4/cds-au/v1/banking/products

And the answers provided verbally during the meeting were to this effect:

Firstly, the expectation is that 300TPS is collective, for both Get Products and Get Products Detail we need to serve up only 300TPS.

Secondly, the expectation is that each externally facing brand link, would need to serve up 300TPS as well.

So based on current understanding, we need to serve up:

-	1200TPS – 300 for both API’s, repeated for each of our 4 brands.

Further to this, it was emphasised that these NFRs are currently non-binding.  Until they become binding (which they will in the future) they are only to be used as a best practice guide.  

It was recommended that we load a change request, so that the above is clarified.

**Comment by mattp-rab** [comment]
This might help: [https://github.com/ConsumerDataStandardsAustralia/standards/issues/101](https://github.com/ConsumerDataStandardsAustralia/standards/issues/101)

> The intent of the thresholds is not to require holders to demonstrate that they can support that level of traffic, it is to give an upper bound above which holders can reject traffic.
> 
> For traffic levels below the threshold there is an expectation that requests will be successfully responded to so infrastructure should be planned to accommodate that outcome based on the size of the ADI's customer base.

That is, data holders will need to support the performance SLAs for their CDR traffic _up to_ the NFR threshold. Any Australian Data Holder brand will be doing well to see CDR traffic exceed that of current screen scraping requests and indeed the NFR of 300 TPS, particularly in the early days/years. :-)

FWIW, I wouldn't expect infrastructure to support this requirement be an issue for mutuals compared to other challenges

**Comment by CDR-API-Stream** [comment]
Hi @DG-TMBL, thanks for the context. Major brands, as you have described in the original issue, would not count cumulatively to one set of NFRs. Each would have its own distinct set of Base URIs in the CDR Register and a separate set of obligations (including reporting, outages and so forth). The intent of the brand attributes for PRD and NFRs is to support sub-brands of a single DH, not major brands.

### Major brands
As each brand is separately known to consumers in the market, these secondary brands should be configuired in the register such that data recipients are able to present the brand as a distinct data holder when they are asked to share their data.

As far as the ADR and the consumer is concerned the second brand would appear and act as an independent data holder for the purposes of data sharing under the CDR

### Sub-brand / distribution brand
Many banks actively separate different groups of products for specific market segments. For instance, they may separate their retail products ("Everyday Banking") from their business products ("Your Business").  Sometimes they invest in these labels to the point that they are a sub-brand in their own right.

Another example is in the business space where banks will sometimes create industry specific product lines, such as agribusiness or small business, and these products are connected using a sub-brand.

The standards provided an optional mechanism in product reference data (the brand field) to accommodate these scenarios.  It was not intended to be used for master brands or white-labelling.

### NFRs and infrastructure right-sizing in relation to major brands
In that case UniBank, TMB, Health Professionals Bank and Firefighters Mutual Bank would all have separate Base URIs and separate NFR obligations. 

As @mattp-rab rightly points out, the TPS thresholds are upper bounds. It is not an expectation of infrastructure sizing. If a DH does not have a the customer base that would necessitate those loads, it would architect its solution according to its size but would have relief at the upper TPS thresholds. NFRs are currently not binding and the intention is to review these with industry once all banks have been live with consumer data sharing for a reasonable period of time.

### Changes to make
At this time a change to the standards to separate NFRs for sub-brands or to pool NFRs for major brands would not be supported because this is not the intent of the standards.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [decided by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/161#issue-806886083) that no change to standards will be made.

This issue will be closed accordingly.
