### ISSUE TITLE
Increment BankingAccountDetail Version

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#265]
# Description
BankingAccountDetail references BankingProductLendingRate (which is actually BankingProductLendingRateV2) which as of Version 3 of Get Products was altered to introduce `repaymentType`, `loanPurpose` and rate tier changes. Consequently the payload for BankingAccountDetail has now changed.

Given go-live July 1 it is unclear whether the DSB expects Holders to introduce a new `x-v` for Get Account Detail or upgrade in place. At this point we are assuming that it is an in-place update but this will not work beyond this next version.

# Area Affected
`ResponseBankingAccountDetail` and child structures.

# Change Proposed
Either:
1) Increment BankingAccountDetail version
2) (or) Reference BankingProductLendingRateV1 within BankingAccountDetail (back-port change) and clearly label BankingProductLendingRateV2 as such.

Additionally, clarify versioning approach as there is now code being written to deliver multiple payload versions. This has been raised numerous times in #61 #41 #66 among others.

**Comment by CDR-API-Stream** [comment]
Thanks @perlboy this issue is being reviewed as part of Maintenance Iteration 4.

**Comment by NationalAustraliaBank** [comment]
NAB supports the merging of this change into the existing version of the API.

**Comment by perlboy** [comment]
@CDR-API-Stream This is the only ticket left in [iteration 4](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/projects/3) project, I'm going to assume it is moving to [iteration 5](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/projects/4).

**Comment by CDR-API-Stream** [comment]
Thanks @perlboy this has been moved into iteration 5

**Comment by CDR-API-Stream** [comment]
No change will be adopted for this issue. The decision is to leave the current versioning of BankingAccountDetail as-is. Because Get Account Detail was not a required API for July 2020 Phase 1 data sharing, changes to this API were done under the same model version and API endpoint version.

Since this change, further clarification has been provided by the DSB on changes to the schema models going forwards. Changes that result in a breaking change to one or more affected end points will result in the schema dependencies being versioned.

This position was [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159). 

This issue will be closed accordingly.
