### ISSUE TITLE
ID Permanence requirements for ADR Software Products

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#269]
# Request For Clarification
In the CDR Register call 15/07/2020 a question was asked regarding the bounded context of resource identifiers (e.g. customer, account and transaction resource identifiers) and ID Permanence. 

* Is the bounded context the Accredited Data Recipient or the ADR's Software Product?
* Similarly, what is the bounded context for Pairwise Pseudonymous Identifiers (PPIDs)?

# Answer

Relevant sections of the ACDS:
1. [CDR Federation](https://consumerdatastandardsaustralia.github.io/standards/#cdr-federation)
2. [ID Permanence](https://consumerdatastandardsaustralia.github.io/standards/#id-permanence)
3. [Pairwise Pseudonymous Identifier (PPID)](https://consumerdatastandardsaustralia.github.io/standards/#identifiers-and-subject-types)

To summarise, identifiers are bound to the software product where they are covered by ID Permanence or Pairwise Pseudonymous Identifier (PPID) requirements. As such, resource identifiers must be the same for all concurrent consents for the same consumer _within_ the same ADR software product. The resource identifiers are not transferable across an ADR's suite of software products and cannot be correlated across ADR software products, consumers, Data Holders or ADRs.

**ADR Software Product**
In the ACDS documentation, a Data Recipient is defined as:

> **Data Recipient**
>
> A Data Recipient (DR) is a system entity that is authorised by a Data Holder to access consumer resources (APIs). A Data Recipient MUST capture consumer consent prior to commencing an authorisation process with a Data Holder.
>
> A Data Recipient MUST be accredited in order to participate in the CDR Federation. Accreditation rules for Data Recipients are beyond the scope of this artifact.
> 
> A Data Recipient assumes the role of an [OIDC] Relying Party (Client).
> 
> For the purposes of this standard a single accredited organisation may be represented via the Register as multiple separate Data Recipients to support multiple applications or services.

In this context, a Data Recipient is an Accredited Data Recipient Software Product.

**Pairwise Pseudonymous Identifier (PPID)**
PPID uniqueness is defined per the underlying OIDC standard. PPIDs are unique to the software client (identified by the ``client_id`` which is issued as part of Dynamic Client Registration). As such, PPIDs are also bound to the software product because the ACDS has a 1:1 mapping between a software product and an [OIDC](https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes) client.

> [**8.  Subject Identifier Types**](https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes)
> ``pairwise``
> This provides a different ``sub`` value to each Client, so as not to enable Clients to correlate the End-User's activities without permission.

**Comment by kdatafs** [comment]
The ACDS documentation seems to be inconsistent with the legislation, as the legislation does not include system entities in
it's definitions. It would be good for ACDS documentation to reflect legislation.

The legislation defines an an accredited data recipient is defined as follows:
--------------------------------------------------------------------------------------------------------------------------------------------
https://www.accc.gov.au/system/files/CDR%20-%20Consultation%20draft%20rules.pdf
A number of expressions used in this instrument **are defined in the Act,** including the following: 
…
accredited data recipient;
…

Note: The term “accredited data recipient” is defined in the Act: see section 56AK of the Act. Subrule (2) deals with the usage of this term in these rules. accredited person request service has the meaning given by subrule 1.13(3). **Act means the Competition and Consumer Act 2010.**

https://www.legislation.gov.au/Details/C2020C00205   (The Act)
56AK  Meaning of accredited data recipient
		A person is an accredited data recipient, of CDR data, if:
	(a)    the person is an accredited person; and
	(b)    the CDR data is held by (or on behalf of) the person; and
	(c)    the CDR data, or any other CDR data from which it was directly or indirectly derived, was disclosed to the person under the consumer data rules; and
	(d)    the person is neither a data holder, nor a designated gateway, for the first‑mentioned CDR data.
Note:    For paragraph (d), the person will be a data holder of that CDR data if subsection 56AJ(4) applies.
--------------------------------------------------------------------------------------------------------------------------------------------

The practical consequence is that ADRs are incentivised by the ACDS interpretation to ask the consumer for as much
data as possible in one app that does everything, in order to avoid disconnected data due to different permanence id's applied.  This is not good for the consumer nor for the ADR.

**Comment by bmangalaganesh** [comment]
@kdatafs 

> The practical consequence is that ADRs are incentivised by the ACDS interpretation to ask the consumer for as much
> data as possible in one app that does everything, in order to avoid disconnected data due to different permanence id's applied. This is not good for the consumer nor for the ADR.

My interpretation is that they (ADRs/ADR Software Products) can't ask the consumer for any data. The ADRs are subjected to "_data minimisation principle_". If the ADR software product is providing a service where it really requires all the data then it is well within its rights to collect the data and use it for the ADR software product's functionality to provide goods/services to the consumer.

Source: ACCC CDR Rules - Final - 6 February 2020.pdf (pages 9 and 10)

- The data minimisation principle _limits the CDR data_ that an accredited person can collect, and also limits the uses that the accredited person can make of collected CDR data.

- An accredited person _complies with the data minimisation principle_ if:
(a) when making a consumer data request on behalf of a CDR consumer, it does not seek to collect:
(i) _more CDR data than is reasonably needed;_ or
(ii) CDR data that relates to a longer time period than is reasonably needed;
in order to provide the goods or services requested by the CDR consumer; and

**Comment by CDR-API-Stream** [comment]
Hi @kdatafs, system entities are defined in the CDR Register: https://cdr-register.github.io/register/#ecosystem-entities

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
