### ISSUE TITLE
Customer Present for Unauthenticated APIs

### ISSUE THREAD

**Issue by bmangalaganesh** [ConsumerDataStandardsAustralia/standards-maintenance#274]
# Request For Clarification

Looking at the performance tiers, trying to comprehend the usage of a "Customer Present" to an un-authenticated API (e.g Get Status and Get Outages)

Both of these APIs are tagged as "This operation does not require authentication".

I had [raised a query](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/250) on how to treat "_x-fapi-customer-ip-address_" when a request is sent to an un-authenticated end point and the guidance was to  ignore this field.

Now that I re-read the specifications on NFR, it appears the expectation is to not ignore this field for these two un-authenticated APIs (Get status and Get Outages) and serve these APIs on a priority tier (as high priority API requests) contrast to other unauthenticated APIs.

Would love to hear thoughts and advice. 

Would also like to hear from the Big4 on how they have interpreted this.

**Comment by perlboy** [comment]
![image](https://user-images.githubusercontent.com/4291448/88058388-c21e5980-cba6-11ea-898a-f91ee8c51955.png)
@bmangalaganesh as you have observed it does appear this is ambiguously written as Get Status and Get Outages are unauthenticated endpoints.

**Comment by nils-work** [comment]
Hi @bmangalaganesh 

I think there's a few different things in play here and another interesting point you've raised.

1. 'Customer Present' may not equal 'Authenticated' (like requests to unauthenticated endpoints while the customer is not logged in?)
2. 'Authenticated' may not equal 'Customer Present' (calls can be Unattended)
3. An unauthenticated endpoint can be accessed with authentication (Customer Present or not)
4. An unauthenticated endpoint can be accessed by the public (putting the request in the Unauthenticated tier)
5. An unauthenticated endpoint can be accessed in a Customer Present state (putting it in the High Priority tier)

The CDS response to your first post was to ignore the header, rather than reject calls to unauthenticated endpoints when the header was present. For example; type 1, 3 and 5 above.

I think the main concern you've raised now is not about ignoring it, but whether it would actually be present for calls to those endpoints -

- **x-fapi-customer-ip-address ... Not to be included for unauthenticated calls.**

Maybe that should say "Not to be included when customer not present."?

If the header is not expected when Get Status and Get Outages are called, how would those requests be assigned to that performance tier? 
When it's not present, it seems like those endpoints would fall into the Unattended tier -

- Unattended **4000ms** Unattended calls to High Priority or Low Priority end points.

**Comment by CDR-API-Stream** [comment]
Hi @bmangalaganesh, @perlboy and @nils-work thanks for these questions and feedback.

You are correct this is a documentation issue. The Get Status and Get Outages endpoints are considered high priority but the presence of the customer is not the condition. 

The correct fix for this is to correctly define the treatment of unauthenticated endpoints

> **Unauthenticated**
> All unauthenticated end points not otherwise specified in a separate threshold.
>
> **High Priority**
> The following unauthenticated end points:
> * Get Status
> * Get Outages
> 
> Customer Present calls to the following end points:
> * InfoSec end points
> * Get Accounts
> * Get Customer
> * Get Customer Detail

**Comment by nils-work** [comment]
Thanks @CDR-API-Stream 

I understand the intention, but there is still this statement regarding the **High Priority** tier in the [Unattended group](https://consumerdatastandardsaustralia.github.io/standards/index.html#performance-requirements) 
![image](https://user-images.githubusercontent.com/60594671/89490697-caa2a100-d7f0-11ea-844a-71228d47ffb5.png)

Should the description read -
"Unattended calls to High Priority or Low Priority **authenticated** end points."  ?

as the unauthenticated end points could otherwise be considered as equivalent to 'Unattended' due to the absence of `x-fapi-customer-ip-address`

**Comment by CDR-API-Stream** [comment]
Thanks @nils-work, you are correct, that should also be clarified by an update to the language to remove ambiguity.

**Comment by nils-work** [comment]
Thanks @CDR-API-Stream, I just noticed there is also an [older issue](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/147) related to the tiers.

**Comment by CDR-API-Stream** [comment]
This issue looks to be resolved.  If this question is still applicable, it would be appreciated if you could raise your request on the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us) as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
