### ISSUE TITLE
DELETE payload requirement for CDR Arrangement Endpoint

### ISSUE THREAD

**Issue by ttranatping** [ConsumerDataStandardsAustralia/standards-maintenance#278]
# Request For Clarification

I have found the following items as mutually exclusive:
- The CDR Arrangement Endpoint (https://consumerdatastandardsaustralia.github.io/standards/#end-points) requires HTTP Method: DELETE. 
- The CDR security profile also requires JWT Profile (rfc7523) for Client Authentication for the same endpoint. 
- The JWT profile requires the client assertion sent as a x-www-form-urlencoded payload.

Although RFC-7231 allows for payloads to be sent with a DELETE method, it also cautions us with:
https://tools.ietf.org/html/rfc7231#section-4.3.5
   A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.

Question: Should we proceed with the specification as is?

**Comment by ttranatping** [comment]
Apache HTTP Client as an example (a very common example) does not provide the ability to set a payload/entity for the DELETE method.
- https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/methods/HttpDelete.html

Possible options:
- Adjust the CDR Arrangement endpoint to be performed over POST (much like the OAuth2 revocation endpoint).
- Adjust the CDR Arrangement endpoint to accept a bearer token instead.

**Comment by CDR-API-Stream** [comment]
Hi @ttranatping this is a valid issue and has been considered within [Decision Proposal 135 - November 2020 Consent Obligations: fixes and clarifications](https://github.com/ConsumerDataStandardsAustralia/standards/issues/135) to fix this.

To allow Client Authentication to work, the recommendation is to change the revocation end point to be performed over POST.

Changing to bearer token would be a challenge because there are no scopes defined for the end point so this would be an issue for existing consents.

**Comment by CDR-API-Stream** [comment]
This issue has been addressed in the resultant Decision Proposal 135 and this issue is being closed accordingly.
