### ISSUE TITLE
Seeking clarification on how to inform ADR about consent update (joint account has been revoked from Consent)

### ISSUE THREAD

**Issue by SongqingGu** [ConsumerDataStandardsAustralia/standards-maintenance#279]
# Request For Clarification
Seeking clarification on how to inform ADR about consent update.  Revocation endpoint exposed by ADR is for Data Holder to inform consent withdrawal, rather than consent update. Is there a way to inform ADR  that consent has been updated? 

A typical use case is when a joint account has been revoked from data sharing arrangement from Data Holder side. Data Holder needs to remove the joint account from the relevant Consent, and also inform relevant ADR about this change. Questions from Data Holder: 
1. How to inform ADR this change to the Consent? 
2. How to response ADR when ADR queries data from this revoked joint account? 

The concern here is without acknowledgement of joint account revocation ADR keeps seeking this joint account data from relevant Data Holder.

**Comment by bmangalaganesh** [comment]
The association between a consent and an account can change due to a number of reason(s), few are listed below :

1. Joint account election - This is the scenario that you have described.
2. Account is marked as Vulnerable flag/Fraud Lock.

The Specs do not provide a way to communicate this disassociation  between consent and account. 

if the ADR makes a request to the election revoked joint account, then the Data Holder will decline the request with a 422 response.

@perlboy had mentioned about a similar scenario (not exactly the same as you have mentioned) [here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/133) where he has suggested that 422 be used to return errors where the request is valid however the Data Holder is not able to disclose the CDR data.

In the case of Joint account election revocation, it makes sense to provide the reason however for fraud lock scenarios, it is highly likely that  the Data Holder MUST NOT disclose that information (account has a fraud lock) to the ADR app. 

Keen to see and hear the view points of other experts.

Note: There were some interesting discussion in this space earlier. Refer to Issue(s):

1. [Issue 131](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/131)


 
https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/131

**Comment by CDR-API-Stream** [comment]
Hi @SongqingGu at this stage there is no notification of account-level changes to consent from the DH side. As @bmangalaganesh correctly notes, an ADR will know that a joint account is not available because a call to an endpoint to get the joint account data will return an error. 

The ADR can also use Get Accounts to obtain the list of available accounts.

**Comment by CDR-API-Stream** [comment]
This issue has been answered and it is being closed accordingly.
