### ISSUE TITLE
Product Reference Data - major inconsistencies in Residential Mortgages

### ISSUE THREAD

**Issue by aj-mozo** [ConsumerDataStandardsAustralia/standards-maintenance#282]
There seem to be a number of issues with the way various data holders have implemented the standards for Product Reference Data, especially in mortgages.

This makes life hard for those of us who want to compare things!

1. No standard way of dealing with the different rates applicable to repayment type, borrower type, etc. By placing this information in free text fields, comparison becomes unnecessarily difficult and prone to error.

2. No standard approach to disaggregation of products into multiple records. For example, NAB represents its Tailored Home Loan in a single product record with 87 different rate variants; ANZ breaks its equivalent product set into 4 records of up to 28 variants; CBA has 12 records with 4 variants each, and so on. Variants include those flagged by text fields as mention in point 1, and also fixed rate and packaged variants which have their own inconsistencies. Refer to attached summary file.

3. No way to identify if disaggregated product records belong to the same product or not. Disaggregation may work fine for an individual customer scenario but does not facilitate the creation of a whole-of-product summary.

[inconsistencies_in_cdr_get_product_details_HL.pdf](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/files/5004441/inconsistencies_in_cdr_get_product_details_HL.pdf)

**Comment by nils-work** [comment]
Hi @aj-mozo 

I acknowledge that this is an older issue and that implementations may have changed by now, but I'd like to provide a reply to your findings and see if you have any further concerns or suggestions to provide.

Re: your points -

> 1. No standard way of dealing with the different rates applicable to repayment type, borrower type, etc. By placing this information in free text fields, comparison becomes unnecessarily difficult and prone to error.
> 2. No standard approach to disaggregation of products into multiple records. For example, NAB represents its Tailored Home Loan in a single product record with 87 different rate variants; ANZ breaks its equivalent product set into 4 records of up to 28 variants; CBA has 12 records with 4 variants each, and so on. Variants include those flagged by text fields as mention in point 1, and also fixed rate and packaged variants which have their own inconsistencies. Refer to attached summary file.
> 3. No way to identify if disaggregated product records belong to the same product or not. Disaggregation may work fine for an individual customer scenario but does not facilitate the creation of a whole-of-product summary.
> 

1. Guidance to data holders has indicated that where applicable, structured fields (like enums and specific objects) should always be used in preference to free-text fields. You may find this situation has improved since this issue was raised and should also improve over time with further guidance being provided and [greater awareness of these concerns](https://www.accc.gov.au/about-us/publications/serial-publications/the-consumer-data-right-compliance-audits-and-targeted-compliance-reviews/data-quality-in-the-consumer-data-right-findings-from-stakeholder-consultation).

2. The aggregation or disaggregation of products is at the discretion of data holders and may be done in a way that most accurately describes the respective products. As you've noted, the lendingRates structure allows for a variety of rate types to be provided in a single 'product', but each product can only include a single set of features, constraints, eligibility, and fees, among other things. If any of those aspects are different for a variant of a product, that difference may necessitate an additional product record to cater for it. Alternatively, multiple product records may simply correspond to different product codes from backend systems, even if the product detail is near identical.

3. I think this issue may relate to the previous points. 
   - Whether products are aggregated or not, structured data should be used to provide a clear distinction between the variants/options available (for example; owner-occupied/investor, principal and interest/interest only, LVR ranges). 
   - As the decision (or ability) to aggregate or disaggregate is at the discretion of the data holder and may be based on differences in the product content, a 'whole-of-product' summary may only be appropriate at the level of 'product' as defined by the data holder. 
   - If an option was to allow the data holder to provide a key to re-aggregate variants of a 'product', there may then be concerns with identifying which fees, features and other detail were common to the 'core' product record, and which were unique to a variant record (with the intention of avoiding duplication). There could be solutions to this though, so if participants feel this is worth considering, please provide further comments.

**Comment by nils-work** [comment]
As part of a backlog review in Maintenance Iteration 21, it was [suggested](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-21:-Meeting-notes-(18-September-2024)#issues-that-will-be-closed) that this issue could be closed. 
If there are no further comments, this issue will be closed on 25 October 2024.
