### ISSUE TITLE
Account owners added after authorisation

### ISSUE THREAD

**Issue by Susan-CDR** [ConsumerDataStandardsAustralia/standards-maintenance#297]
For accounts (typically businesses) an account owner can be added after an account has been opened. If a data sharing consent has been established when only one owner was on the account and subsequently an additional owner was added does the data holder need to stop sharing the data on that account (Phase 1 only single account holder) or pause sharing until the second holder has provided authorisation (Phase 2)

If a third owner is added should disclosure of that account then be stopped and the account become ineligible to share.

**Comment by nils-work** [comment]
Hi @Susan-CDR 

Just some thoughts since you've had no other replies yet :)

I would think that the new joint account holder's election would not match the existing account holders joint election (if there was any at all) so sharing would stop when the other holder was added (because you must then have their authorisations matching.)

When a third owner is added the account would no longer be eligible as it has >2 holders and you most likely wouldn't support election across 3 holders.

**Comment by CDR-API-Stream** [comment]
The DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  If this question is still applicable, it would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.
