### ISSUE TITLE
paymentsRemaining cannot currently be 0

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#309]
# Description

`paymentsRemaining` is marked as a _PositiveInteger_ but the examples show an example value of 0 (which _PositiveInteger_ cannot be) and it seems logical that `paymentsRemaining` can be 0 (ie. completed scheduled payments):

![image](https://user-images.githubusercontent.com/4291448/91631726-1d056500-ea1f-11ea-8d37-f16923d7f190.png)

Definition of PositiveInteger:
![image](https://user-images.githubusercontent.com/4291448/91631734-2bec1780-ea1f-11ea-8550-ca6b05478f58.png)

# Area Affected
`BankingScheduledPaymentRecurrenceIntervalSchedule` and `BankingScheduledPaymentRecurrenceLastWeekDay` which is used in all scheduled payment calls.

# Change Proposed

Either:
1) Change `paymentsRemaining` to `NaturalNumber` type
2) Change examples to show 1 on the basis that `paymentsRemaining` cannot be 0 (which seems unlikely)

**Comment by CDR-API-Stream** [comment]
Hi @perlboy / all, this issue was discussed in the recent [maintenance iteration](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-5:-Iteration-Checkpoint:-Agenda-&-Meeting-Notes-(15th-October-2020)).

``paymentsRemaining`` in the PaymentScheduledPaymentSet wasn't intended to be historical. The proposed change, which was supported on the call, is to adopt Option 2: update the non-normative example to be "1".

If DHs see benefit to allow historical scheduled payments, this could be included as a future change provided there is clear need and benefit.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair for inclusion in v1.7.0](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159). A change to the data standards was recommended.

This issue will be closed accordingly.
