### ISSUE TITLE
[1.4.0] BankingProductFee feeType adds Variable which is a new payload version

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#310]
# Description
`BankingProductFee` had the enumeration of `feeType` altered to include `VARIABLE` as per the changelog:
![image](https://user-images.githubusercontent.com/4291448/91648540-50da9c00-eaac-11ea-9fc4-ce2e28bac017.png)

As a consequence, `BankingProductDetail` (V4) and `BankingAccountDetail` (V2) are now a new payload version resulting in a new payload version for `Get Account Detail` and `Get Product Detail`.

# Area Affected
`Get Account Detail`, `Get Product Detail`, `BankingProductDetail`, `BankingAccountDetail`, `ResponseBankingProductById`, `ResponseBankingAccountById`.

# Change Proposed

Increment the payload versions of the endpoints affected, increment downstream payloads and responses.

**Comment by CDR-API-Stream** [comment]
No change will be adopted for this issue. The decision is not to change the payload versions or increment the API endpoint versions. Because the change affected a future dated release of the associated endpoints, the change was incorporated into Get Product Details V3 and Get Account Details V2. This is consistent with the approach the DSB has taken in the past where a change to the model for a version of an endpoint that is not yet an obligation for data holders would not result in a versioning of the affected endpoint.

Since this change, further clarification has been provided by the DSB on changes to the schema models going forwards. Changes that result in a breaking change to one or more affected end points will result in the schema dependencies being versioned.

This position was [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/159). 

This issue will be closed accordingly.
