### ISSUE TITLE
Obligation date-based standards

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#315]
While we recognize the the efforts made by the regime to improve the engagement process, including the introduction of regular working groups, workshops, detailed minutes, and most recently the support portal, it has become quite difficult to interpret which parts of the standards have what obligation dates.

To mitigate these difficulties, we propose the standards be split into different files, each describing the obligations for a specific date/milestone.

**Comment by perlboy** [comment]
How is this possible when there are inline changes tied to existing obligation dates? This is related to the request to improve how documentation is published that was "being looked at" at the start of the year in #56. Since then changes have continued to involve [diffs in excess of 100,000+ lines](https://github.com/bizaio/dsb-standards-upstream/pulls?q=is%3Apr+is%3Aclosed) and as of this afternoon the engineering team is "looking at options" although there doesn't appear to have been any formal kick off of requirements analysis so I guess "DSB knows best" is still ringing true.

In an effort to make it easier for participants to **focus on delivering real things**, Biza.io has started maintaining a [redocs version](https://bizaio.github.io/dsb-standards/) of the Standards which while focusing (at this stage) on endpoint changes provides much smaller diffs, [structurally tagged](https://github.com/bizaio/dsb-standards/tags), that are [2% the size of the upstream](https://github.com/bizaio/dsb-standards/compare/v1.3.1...v1.4.0) along with OpenAPI 3 support (and Swagger backport), [versioned schema](https://bizaio.github.io/dsb-standards/#section/BankingProductDetail), [documented enumerations](https://bizaio.github.io/dsb-standards/#section/EnumBankingProductEligibilityType) and, where possible, [bounded value ranges](https://bizaio.github.io/dsb-standards/#section/AdminAvailabilityMetrics/AdminAvailabilityMetricsV1).

Realistically, in the absence of an approach that **understands** the software engineering process, perhaps a more detailed obligation date table would suffice? For instance, something (very and definitely inaccurate!) roughly like this:

| Endpoint | Version | Introduction Date | Mandatory Delivery Date | Deprecation Date | Retirement Date |
|-|-|-|-|-|-|
| /products | V1 | 2020-01-01 | 2020-07-01 | 2020-09-01 | 2020-10-01 |
| /products | V2 | 2020-06-01 | 2020-10-01 | N/A | N/A |
| /products | V3 | 2020-09-01 | 2020-02-01 | N/A | N/A |
| /product/{productId} | V1 | 2020-01-01 | 2020-07-01 | 2020-09-01 | 2020-10-01 |
| /product/{productId} | V2 | 2020-06-01 | 2020-10-01 | N/A | N/A |
| /product/{productId} | V3 | 2020-09-01 | 2020-02-01 | N/A | N/A |
| InfoSec Profile | 1.3.1 | 2020-01-01 | 2020-11-01 | N/A | N/A |
| InfoSec Profile | 1.4.0 | 2020-10-01 | 2020-02-01 | N/A | N/A |

Of course, this doesn't protect against undocumented and inline version changes (of which there have been quite a few in successive versions) but at least a dev lead can give an update the project manager can get onboard with.

**Comment by perlboy** [comment]
Further on this, the [PR for 1.5.0](https://github.com/bizaio/dsb-standards-upstream/pull/13/commits) changes is 112,822 additions, 2,240 removals. Not withstanding the infosec changes the actual payload endpoint changes is [167 additions, 128 removals](https://github.com/bizaio/dsb-standards/compare/v1.4.0...v1.5.0) representing a 99.74% reduction.

**Comment by perlboy** [comment]
There has been some related commentary on this at #328

**Comment by WestpacOpenBanking** [comment]
Westpac is supportive of the approach mentioned by Commonwealth Bank, but the use of endpoint versions significantly complicates an approach of this type. We are supportive of a more detailed obligation date table. We would also be supportive of allowing a review period for new standards versions in entirety prior to releases – this would help to ensure that documentation errors are avoided in future.

**Comment by CDR-API-Stream** [comment]
Thanks all, as discussed on the maintenance iteration call [held on 7/10/2020](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-5:-Iteration-Scope-Review:-Agenda-&-Meeting-Notes-(7th-October-2020)) this issue should not be considered in isolation and the recommendations proposed in #328 warrant consideration as a holistic solution.

The core issue at the heart of the change request is to have greater certainty on obligations for each compliance milestone. In the context of a more comprehensive obligations table, the DSB would first like to elicit requirements and what dimensions (along with an agreed definition) should be expressed e.g Rules section/version, earliest implementation date, etc. @perlboy has provided a number of dimensions:

1. Endpoint or Section of the data standards
2. Section Version
3. Introduction Date
3. Mandatory Obligation Date
4. Deprecation Date (if applicable)
5. Retirement Date

@perlboy,
* is "Introduction Date" the date this was first introduced in the data standards or an optional "go early implementation date"?
* how do you consider "Deprecation Date" and "Retirement Date" are different?

**Comment by perlboy** [comment]
Hi @CDR-API-Stream,

> * is "Introduction Date" the date this was first introduced in the data standards or an optional "go early implementation date"?

Introduced into Data Standards is probably most appropriate. I'm not aware of any requirement to limit the time by which a holder can go live (ie. "Next Day" would be great - if it was possible!).

> * how do you consider "Deprecation Date" and "Retirement Date" are different?

Deprecation Date refers to when it was declared in the Standards as scheduled for Retirement. Retirement Date is the "last date of support" for Recipients. For Babelfish we immediately mark methods with a @Deprecated tag, which starts doing strikethrough in IDEs giving developers an indicator of work to do but not breaking the code itself, and then drop the method entirely post retirement whereby compile errors would ensue.

**Comment by CDR-API-Stream** [comment]
Several changes have been made, or are planned to be made for v1.7.0, based on feedback to this issue and other similar issues related to the DSB's publishing processes:  
1. The DSB has recently published a noting paper regarding DSB's standards promotion process. The DSB is now trialling a new staging area for standards so that changes can be drafted before they are formally adopted into the Consumer Data Standards.
2. The DSB is also reviewing its publishing tools and has recently trialled using redoc for publication of standards.
3. The DSB has launched a more interactive site for Consumer Experience guidelines: https://www.notion.so/Consumer-Experience-Standards-and-Guidelines-dffe42d39d4942c5b4f2c7612ba4f6e0.
4. The DSB has ported the Consumer Experience Data Standards from the previous PDF format
to the Technical Data Standards page to be released as part of v1.7.0
5. The Future Dated Obligations table in the standards is being enhanced based on feedback
arising from Change Request #315.

This change request will be kept open so that further feedback can be tracked. The original poster may wish to close this issue or create a separate issue that specifically targets other areas for consideration as they see fit.

**Comment by nils-work** [comment]
As noted in the [comment above](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/315#issuecomment-778863233), a number of changes in respect to this issue have been made since it was raised, including these items introduced in v1.17.0 - 
- [Obligation highlighting](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/158)
- [Obligation milestone windows](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/159)
- [Navigation for diffs and code examples](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/157)

If there are no further comments or feedback on this issue, I propose it be closed on 30 June 2023.
