### ISSUE TITLE
financialInstitution should be marked as conditionally required

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#342]
# Description
In the `BankingAuthorisedEntity` [schema](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingauthorisedentity), `financialInstitution` is currently specified as **optional** but the description includes a condition - 

> Name of the financial institution through which the direct debit will be executed. **_Is required unless the payment is made via a credit card scheme_**

Some conflicting background to this documentation is [here](https://github.com/ConsumerDataStandardsAustralia/standards/issues/52#issuecomment-487252822) ("will remain mandatory")  and [here](https://github.com/ConsumerDataStandardsAustralia/standards/issues/79#issuecomment-517122905) ("would not be known").

# Area Affected
`BankingAuthorisedEntity` [schema](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingauthorisedentity)

# Change Proposed
Clarify whether current documentation is correct and if so, specify `financialInstitution` as **conditional**.

Consider including a boolean field in the `BankingAuthorisedEntity` schema, [similar to other schemas](https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingscheduledpaymentset) that have conditional properties and update the Description field for `financialInstitution`.

Name | Type | Required | Restrictions | Description
--|--|--|--|--
financialInstitution | string | conditional | none | Name of the financial institution through which the direct debit will be executed. **_Mandatory unless the isCardSchemeDirectDebit field is set to true._**
isCardSchemeDirectDebit|Boolean|optional|none|Flag indicating whether the payment is made with a credit card scheme. If absent then false is assumed.

**Comment by CDR-API-Stream** [comment]
Thanks @nils-work, the change you have proposed would be consistent with the design choices in the standards however it would give rise to a breaking change where DHs would be required to implement a new field where the payment is made via a card scheme. 

Given that the only condition imposed on this field for optionally omitting it is due to payments via card scheme, would it suffice to update the requirement of this field to `conditional`? This would retain the implicit inference that the absence of the `financialInstitution` value means it is a card scheme payment however it would not create a breaking change: it would be a documentation fix to correctly highlight the conditional nature of the field value. Admittedly this is not an explicit indicator like your proposal.

Any community feedback would be welcomed to progress this issue.

**Comment by CDR-API-Stream** [comment]
The recent [maintenance iteration call](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-7:-Agenda-&-Meeting-Notes-(10th-June-2021)#notes) discussed this issue. Treating the value as conditional was supported.

* A community member raised an upcoming change from Visa will provide greater visibility on merchant details so this information may become more accessible even for card schemes
* It was suggested that the `financialInsitution` should be provided where possible for card schemes thus the proposed `isCardSchemeDirectDebit` approach wouldn't be the ideal way to deal with the issue
* The statement in the standards _"Is required unless the payment is made via a credit card scheme"_ would still apply because there will be no value for historical card payments and may be limited early support for additional merchant details via card schemes. Where there is, the standards would require the population of the value because it is not optional from the perspective that it is at the discretion of the DH to provide.

Based on this feedback, it is recommended that the required statement be correctly fixed to `conditional` but no further changes. Where the value of `financialInsitution` is available for a direct debit via card, it would need to be provided in the response from the DH.

**Comment by CDR-API-Stream** [comment]
The changes have been drafted in standards staging for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.0...maintenance/342

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/178#issue-868429903) and is included in v1.11.0. The proposed change to the data standards was not recommended however a correction to the field was made to mark it as conditional.

This issue will be closed accordingly.
