### ISSUE TITLE
Clarification on transaction times

### ISSUE THREAD

**Issue by jakubvozarik** [ConsumerDataStandardsAustralia/standards-maintenance#347]
As per the standards, the schema for BankingTransaction states that postingDateTime, valueDateTime and executionDateTime are expected to be DateTimeString. Further to that, the description for postingDateTime states:

The time the transaction was posted. This field is Mandatory if the transaction has status POSTED. **This is the time that appears on a standard statement**

We would like to understand what is the expectation for a case where a DH does not have the time of transaction available and it is not presented to customers in online banking or on statements (date is still shown)?

Similarly, what about a case when a transaction time is captured as a system time on infrastructure which does not sit in AU?

On a slight different note but relating to transaction API - is the expectation that the list of transactions shared via this API is mirroring what a customer would see on their online banking at a given time?

Thank you

**Comment by CDR-API-Stream** [comment]
Hi @jakubvozarik,
The DSB are now responding to requests for clarification via the CDR Support Portal.  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by CDR-API-Stream** [comment]
This issue has been answered via the CDR support portal: [Clarification on transaction times](https://cdr-support.zendesk.com/hc/en-us/articles/900003470146-Clarification-on-transaction-times) and [Correspondence between transactions listed by API and by Internet banking applications](https://cdr-support.zendesk.com/hc/en-us/articles/900004384663-Correspondence-between-transactions-listed-by-API-and-by-Internet-banking-applications). Accordingly, the issue is closed.
