### ISSUE TITLE
Travel Money Card Balance

### ISSUE THREAD

**Issue by commbankoss** [ConsumerDataStandardsAustralia/standards-maintenance#357]
# Description
The Standard for ResponseBankingAccountsbalanceById requires Current Balance and Available Balance fields as mandatory for the response to Get Account Balance.

Commonwealth Bank's Travel Money Card (TMC) does not have a single account current balance or available balance, but rather the product itself has multiple purses with varying types of currency.

These currencies have fluctuating exchange rates, and so if Commonwealth Bank was to convert these values to populate the mandatory current balance and available balance, there is a high likelihood this calculation will not be a correct reflection of the actual value amount.

# Area Affected
ResponseBankingAccountsBalanceById

# Change Proposed
For Commonwealth Bank to provide accurate data, we are requesting that Current and Available Balance fields are changed to conditional, not mandatory. This way we don't require to calculate Current Balance and Available balance, and still have the ability to return the array of purses with each individual purse balance.

**Comment by nils-work** [comment]
Hi @commbankoss 

Does [this guidance](https://cdr-support.zendesk.com/hc/en-us/articles/900004041986-Travel-Money-Card-Balance) provide an appropriate solution to this issue?

It states that rather than having to calculate the current and available balance from a mix of currencies, you would provide the balance values only for the default currency, then the separate amounts of each currency, including the default, in the `purses` array.

**Comment by nils-work** [comment]
As part of a backlog review in Maintenance Iteration 21, it was [suggested](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-21:-Meeting-notes-(18-September-2024)#issues-that-will-be-closed) that this issue could be closed. 
If there are no further comments, this issue will be closed on 25 October 2024.
