### ISSUE TITLE
API Error Schema Clarification

### ISSUE THREAD

**Issue by kaveenr** [ConsumerDataStandardsAustralia/standards-maintenance#36]
Greetings all, 

Upon looking at the [OpenAPI Schema given for the CDS v1 API](https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.yaml) it shows that the current error model `ResponseErrorList_errors` only support a single error type.

It is for the `422 Unprocessable entity` exceptions of the POST calls in the API, this is further justified with the description `Must be one of the following: 0001 – Account not able to be found`.

**Any considerations for introducing different error codes for HTTP bad request, Internal Server Error, etc?**
With this, we are able to give textual descriptions in case of a missing attribute bad request as an example.

**If only a single type of code is allowed why not make the OpenAPI schema `code` attribute an enumeration?**  

**In the case of a GET request to /banking/accounts/{accountId} with an invalid accountID can the same `0001 – Account not able to be found` be used as a response?** 

Cheers,

**Comment by kaveenr** [comment]
Further as an example,
I'm talking about something like how OBIE UK (PSD2 Open Banking) has handled the error codes.

In the namespaced enumerations  specification (in specific [`OBErrorResponseError1Code`](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1000571919/Namespaced+Enumerations+-+v3.1.1))

Codes such as `UK.OBIE.Field.Invalid`(400), `UK.OBIE.UnexpectedError` (5xx), etc are given for implmenters.

**Comment by CDR-API-Stream** [comment]
There is currently an open thread on the main standards site related to more extended error handling with the intent of collecting from implementers the error scenarios that would like to see represented.  This can be found at https://github.com/ConsumerDataStandardsAustralia/standards/issues/68

Please comment there on any additional error scenarios or mechanisms that should be considered for addition to the standards.  The DSB intended to manage error handling through a decision proposal rather than the maintenance stream to accommodate the possibility of changes to the overarching standards to accommodate better error handling.
