### ISSUE TITLE
Request for clarification. Expectations on how PRD endpoints should be discovered, and PRD base uri

### ISSUE THREAD

**Issue by VladPNBank** [ConsumerDataStandardsAustralia/standards-maintenance#365]
Hello,
Acknowledging the question asked on Zen desk in regards to Get Outages and Get Status, and the answer that DSB expect a single unauthenticated baseURI, could you please clarify what is the expectation for a consumer to discover the base uri for PRD? Is it DH website?
Is it acceptable for base uri for PRD endpoints to be different to unauthenticated base uri for Get Status and Get Outages.
Thank you,
Vlad

**Comment by TT-Frollo** [comment]
With a single unauthenticated end point that combines Get Status and Get outage details for both unauthenticated and authenticated API's consideration should be given to the consumers of Product Reference Data. These consumers have no access to to the authenticated banking API's yet are given details about their status/outage. These details are irrelevant to consumers of Product Reference Data an therefore combining the data is unnecessary. Is there a basic issue being solved with the single publicbaseuri?

Unless I am mistaken, where 2 vendors are used, the standards would require the PRD solution baseuri to be the publicbaseuri in the registry and therefore require the PRD Get status and Get outages to combine the banking api status/outage details. Not the other way round. Which seems the wrong way round in practice.

**Comment by perlboy** [comment]
I believe the Get Status and Get Outage endpoints are intended to be a global representation of the Holder's availability for both PRD and CDR API endpoints and the expectation was that banking endpoint availability should be in the public domain not limited to recipients. There is/was some grounds to consider whether non-repudiation of this information would be useful but [that's a discussion for a different time](https://github.com/ConsumerDataStandardsAustralia/standards/issues/65#issuecomment-489319440).

The CDR Register spec specifically states the published uri should be used for all non-authenticated endpoints. I guess technically the use of the word **should** means doing so is not mandatory:

> Base URI for the Consumer Data Standard public endpoints. This should encompass all endpoints not requiring authentication

https://cdr-register.github.io/register/#participant-endpoints

**Comment by VladPNBank** [comment]
Thank you @perlboy, just seeking clarification from @CDR-API-Stream if the following configuration example is acceptable:
PRD base uri https://**ob-api**.pnbank.com.au/cds-au/v1/banking/products
CDR Public base uri https://**cdr-api**.pnbank.com.au/cds-au/v1/discovery
Resource Base uri and others https://**cdr-api**.pnbank.com.au/cds-au/v1/banking/...

**Comment by VladPNBank** [comment]
Issue has been raised in CDR Support Portal

**Comment by CDR-API-Stream** [comment]
Hi @VladPNBank,

> could you please clarify what is the expectation for a consumer to discover the base uri for PRD? Is it DH website?

The ACCC has provided this previous guidance:

> _Under rule 1.12 of the Competition and Consumer (Consumer Data Right) Rules 2020, a data holder is required to provide an online service that can be used to make product data requests to be disclosed in machine readable format and in accordance with the data standards. In this regard, the consumer data standards require the provision of unauthenticated API end points which are publicly available._
> 
> _We understand that there may have been different interpretations of what making the PRD API publicly available constituted in practice.  To avoid doubt, we consider that providing this information on a data holder’s website ensures the publicly available requirement of the standards is unequivocally met._   
> 

ADRs can determine the location of unauthenticated APIs via the PublicBaseURI via the CDR Register APIs. Because public endpoints are accessible to API consumers beyond ADRs, public consumers that are not ADIs benefit from DHs proactively advertising the location of these APIs on their website. DHs are also encouraged to submit their PRD endpoints the the public repository of PRD data maintained by the DSB: https://github.com/ConsumerDataStandardsAustralia/banking-products-comparator/blob/master/public/datasources.json

> Is it acceptable for base uri for PRD endpoints to be different to unauthenticated base uri for Get Status and Get Outages.

It is expected that all public endpoints are accessible via the PublicBaseURI meaning Get Status, Get Outages and PRD endpoints are available via the same PublicBaseURI.

@perlboy is correct in that the Get Status and Get Outages APIs represent the holistic implementation of the Data Holder's CDR implementation including InfoSec endpoints.

Please note that the DSB are now responding to requests for clarification via the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).  It would be appreciated if you could raise your request there as it will likely be responded to in a more timely fashion and the resulting answer can be turned into an article for others with the same question.

**Comment by VladPNBank** [comment]
@CDR-API-Stream thank you very much.

**Comment by TT-Frollo** [comment]
A suggestion I have is to have an OperationsBaseUri and separate this type of information away from baseuri's that deliver product or customer data.
