### ISSUE TITLE
MTLS and Client authentication requirements for PAR endpoint

### ISSUE THREAD

**Issue by deboraelkin2** [ConsumerDataStandardsAustralia/standards-maintenance#374]
# Description
The [CDS specification](https://consumerdatastandardsaustralia.github.io/standards/#end-points) for PAR endpoint specifies that MTLS and client authentication are required.
The next step in the OIDC hybrid flow with PAR is to invoke the authorisation endpoint. However the specification for this endpoint does not require neither MTLS nor client authentication.
It seems contradictory that these security requirements are enforced in the first step, but not in the second.

# Area Affected
PAR and Authorisation Endpoints

# Change Proposed
Unify MTLS and Client Authentication requirements for both endpoints.
I think the right way to do this would be to enforce MTLS and client authentication in the authorisation endpoint as well

**Comment by perlboy** [comment]
This is exactly what PAR is designed to do (a verified backchannel method prior to client browser hand off). If Authorisation endpoint had MTLS then every consumer would need to have a client certificate.

**Comment by deboraelkin2** [comment]
All I'm saying is that in the 3 steps that a client needs to execute during the authentication/authorisation flow, the first  (PAR) and third steps (token) are MTLS, whereas the second step (authorise) is 1-way TLS. It seems a bit odd...

**Comment by perlboy** [comment]
The second step is the one where the Consumer (user-agent) needs to load a web page to complete consent and is the _only_ one where the Consumer is directly involved. It seems entirely logical to enforce ADR (Client) -> DH comms with 2 factor (MTLS + Client Assertion) while ensuring Consumer's browsers work as expected. The only way of aligning all 3 while not breaking every browser would be to not require MTLS for `/token` and `/par` which would be impossible because certificate bound tokens are required.

**Comment by CDR-API-Stream** [comment]
@deboraelkin2, @perlboy has addressed this question. Accordingly it has been labelled as "answer provided".

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [decided by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/161#issue-806886083) that no change to standards will be made.

This issue will be closed accordingly.
