### ISSUE TITLE
Clarify alignment of lastUpdateTime in CommonPerson schema and updated_at claim

### ISSUE THREAD

**Issue by nils-work** [ConsumerDataStandardsAustralia/standards-maintenance#377]
# Description
The second answer on [this support article](https://cdr-support.zendesk.com/hc/en-us/articles/900003338566-Profile-related-Scope-and-Claims) suggests that the `updated_at` claim should align to the "`lastUpdateTime` field in the payload returned from the customer end point".

The `lastUpdateTime` [property](https://consumerdatastandardsaustralia.github.io/standards/#tocScommonperson) is currently specified as optional, but the description states -

> If no update has occurred then this date **should reflect the initial creation date for the data**

which seems to imply that a value may be mandatory. 

It would seem a valid time ("a JSON number representing the number of seconds") is also required for an `updated_at` claim response.

# Area Affected
The optional `lastUpdateTime` property in the [CommonPerson schema](https://consumerdatastandardsaustralia.github.io/standards/#tocScommonperson) and the `updated_at` claim value.

# Change Proposed
Clarify whether `lastUpdateTime` is optional and any relationship to the `updated_at` claim value.

**Comment by CDR-API-Stream** [comment]
Hi @nils-work, the `lastUpdateTime` field and `updated_at` claim should align. In other words, the same value should be responded to when the Data Holder has an update time or can infer a creation time for the customer information.

Regarding optional vs mandatory requirements for `lastUpdateTime`, at the time of initial consultation, several Data Holders indicated that they did not have a last update time and weren't able to derive the creation date.

Since the optional definition in the CDS means if you have the data you must supply it then it will be effectively mandatory unless a Data Holder doesn't hold update or creation time.

Unless there has been a change to this position and those data holders support a change to make this mandatory, `lastUpdateTime` will remain optional.

**Comment by CDR-API-Stream** [comment]
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/178#issue-868429903). No change was recommended or required.

This issue will be closed accordingly.
