### ISSUE TITLE
[1.11.0] Token endpoint description not updated after removal of item from future dated obligation table[Descriptive Issue Title]

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#403]
# Description
The v1.10.0 and earlier versions of the data standards included the following item in the future dated obligation table:

Section | Description | Applicable Date
-- | -- | --
[Token Revocation End Point](https://consumerdatastandardsaustralia.github.io/standards/archive/standards-1.10.0/docs/#token-revocation-end-point)| Data recipients may obsolete this   end point from February 1st 2021.   Data holders may obsolete consent revocation via this end point from February   1st 2021, however they must still support oAuth token revocation. Data   recipients must upgrade their implementations to use the Data Holder CDR   Arrangement Revocation End Point by this time. | February 1st 2021

However, there are still subsections in v1.11.0 suggesting that data recipients must implement a token revocation endpoint.

# Area Affected
[Token Revocation End Point section](https://consumerdatastandardsaustralia.github.io/standards/archive/standards-1.10.0/docs/#token-revocation-end-point)

# Change Proposed
Remove wording which is no longer relevant.

**Comment by CDR-API-Stream** [comment]
Hi @WestpacOpenBanking, thank you for raising this change. This is a documentation bug and will be prioritised for v1.11.1. This change is now staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.11.1...maintenance/394

The change removes the legacy standards documentation. Because it is a documentation bug, this change is intended for release v1.11.1.
