### ISSUE TITLE
Meaning of breaking change not defined

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#41]
# Description
Defining ‘breaking change’ explicitly and allowing for non-breaking changes to be incorporated without incrementing endpoint versions will support [Principle 4: APIs provide a good developer experience](https://consumerdatastandardsaustralia.github.io/standards/#principle-4-apis-provide-a-good-developer-experience) by:

* Informing developers of coding practises which are best suited to support for newer versions with minimal effort.
* Avoiding potential eco-system churn as legacy versions are depreciated.
* Reducing the burden created by a need to maintain code for many endpoint versions within a code base.

# Area Affected
* [Principle 4: APIs provide a good developer experience](https://consumerdatastandardsaustralia.github.io/standards/#principle-4-apis-provide-a-good-developer-experience)
* [Principle 11: APIs are version controlled and backwards compatible](https://consumerdatastandardsaustralia.github.io/standards/#principle-11-apis-are-version-controlled-and-backwards-compatible)
* [Versioning](https://consumerdatastandardsaustralia.github.io/standards/#versioning)

# Change Proposed

* New section under Versioning defining the meaning of breaking and non-breaking changes within the standards. Suggested wording to the effect of: 
  * The following are non-breaking changes: 
    * Addition of a new endpoint
    * Addition of a new optional request parameter (query, body or header) 
      * Note: Servers must ignore request parameters that they do not understand.
    * Addition of a new response header, field or entity, where the meanings of existing headers, fields and entities are not changed. 
      * Note: Clients should ignore response headers, fields or entities that they do not understand. 
    * Addition of a new error code , where the meaning of existing error code and HTTP status codes have NOT changed. 
      * Note: Clients should catch-all behaviour for unrecognised 4xx and 5xx series HTTP status codes
    * Change of a mandatory request parameter (query, body or header) to optional or conditional.
    * Addition of new enumerated values for existing fields, where the meanings of existing enumerated values are not changed. 
      * Note: Clients should ignore enumerated values that they do not understand.
  * The following are breaking changes: 
    * A new mandatory request parameter (query, body or header)
    * Addition of a new HTTP status code that does not meet the criteria for introduction in a non-breaking way.
    * Removal or change of field or entity data types or object types in request or response
    * Removal or change of existing enumerated values in request or response
    * Removal or rename of existing endpoint URIs
    * Removal or changed meaning of existing response HTTP status codes.
    * Removal or changed meaning of existing error codes, messages or descriptions
    * Change of HTTP verb (e.g. GET to POST)
* Version part \<bug fix\> is renamed to \<non breaking\>. Description is updated to say “Changes which are non-breaking.” With a cross reference to a definition as in the previous point.

**Comment by perlboy** [comment]
V1.1.0 was released and appears to have inconsistently approached breaking changes as evidenced by #60 #66 #61

**Comment by nils-work** [comment]
Hi @WestpacOpenBanking 

Rather than being prescriptive and embedding details such as you've proposed into the Standards themselves, the approach of the DSB has been to assess endpoint versioning in the context of change on a case-by-case basis. This is intended to allow for consultation and flexibility as needed. Although it depends on the circumstances, the decision to increment may generally be favoured to provide certainty to participants. 

With that in mind though, two new labels - '**Breaking change**' and '**Non-breaking change**' have been created to apply to Change Requests in this repository to encourage consultation on that particular aspect through the Maintenance Iteration process.

Issues with the labels currently applied can be found in the following views -
- **Breaking changes** [(list view](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues?q=is%3Aissue+is%3Aopen+label%3A%22Breaking+change%22) | [board view)](https://github.com/orgs/ConsumerDataStandardsAustralia/projects/19/views/17)
- **Non-breaking changes** [(list view](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues?q=is%3Aissue+is%3Aopen+label%3A%22Non-breaking+change%22) | [board view)](https://github.com/orgs/ConsumerDataStandardsAustralia/projects/19/views/16)

The utility of these labels can be reviewed in the current and future iterations.

As there is no change to the Standards expected as an outcome of this Change Request, it will be considered as acknowledged but scheduled to be closed on 25 August 2023.

Thanks

**Comment by nils-work** [comment]
Closing this issue with no impact to the Standards, as noted in the [previous comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/41#issuecomment-1637736339). 
The impact of future changes will be determined by consultation through Decision Proposals and Maintenance Iteration meetings.
