### ISSUE TITLE
Proposal to change specific error codes from MUSTs to SHOULDs

### ISSUE THREAD

**Issue by anzbankau** [ConsumerDataStandardsAustralia/standards-maintenance#412]
# Description
Currently the error codes:
•	urn:au-cds:error:cds-all:Field/Missing
•	urn:au-cds:error:cds-all:Field/Invalid

Are MUST requirements for Data Holders to support. This can be problematic for certain data holders depending on their implementation.

# Area Affected
Error codes standards: https://consumerdatastandardsaustralia.github.io/standards/#error-codes

# Change Proposed
Change the error codes:
•	urn:au-cds:error:cds-all:Field/Missing
•	urn:au-cds:error:cds-all:Field/Invalid

To be SHOULD requirements for Data Holders to support. As per RFC2119 (http://tools.ietf.org/html/rfc2119), a SHOULD will still mean Data Holders are recommended to implement these codes unless there are valid reasons in particular circumstances to not do so.

**Comment by nils-work** [comment]
This issue was discussed in the Maintenance Iteration (MI) call on [9 Aug 2023](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-16-Agenda-&-Minutes).

Two aspects were covered - 
- Whether specific errors are difficult to implement depending on where in the implementation stack they are identified.
  - The participant was requested to provide further details for consideration.
- Potential ambiguity around which error to return in certain circumstances. 
  - The participant was requested to raise a separate issue if interpretation remained unclear.

**Comment by anzbankau** [comment]
ANZ would like to clarify that this can be an issue for Data Holders who have API Security implemented at their WAF. In these cases, the product capabilities may not always allow for extensive customisations. We propose that these error codes are changed from a MUST to a SHOULD to allow for these cases. Changing the requirement to a SHOULD still upholds a high bar for reasons to not adhere to providing these error codes

**Comment by jimbasiq** [comment]
I need to challenge this one. I am concerned that this change could cause complacency in some Data Holders WRT error messages they provide. I would like DH to provide a exception reasoning rather than having the option to not comply with a standard.

I also do not believe it will increase or decrease the load on ACCC. Current situation if a DH is not providing a detailed error message is an ADR could raise a CDR Jira ticket, the DH would respond with reasoning as to why it is not possible to have greater error message granularity. The ADR will either accept the explanation or challenge, with possible escalation to ACCC.

This scenario will be exactly the same if the requirement is a SHOULD rather than a MUST.

**Comment by nils-work** [comment]
Hi @anzbankau 

Could you suggest what may be returned where the current MUST requirement cannot be met?
I think it was suggested in a recent MI call that rather than one of these - 
- `400 Bad Request` with `urn:au-cds:error:cds-all:Field/Missing`
- `400 Bad Request` with `urn:au-cds:error:cds-all:Field/Invalid`

it may be -
- `400 Bad Request` with `urn:au-cds:error:cds-all:GeneralError/Expected`

is that what you would expect, or could the alternative be quite different?

**Comment by CDR-API-Stream** [comment]
This issue was included in Maintenance Iteration 16, 17 and 18 and did not appear to maintain support for the change proposed.
Please add a comment if there are further concerns, or this issue will be closed on 31 May 2024.

Thank you
