### ISSUE TITLE
Standards break on mobile browser

### ISSUE THREAD

**Issue by Hiphopopotamous** [ConsumerDataStandardsAustralia/standards-maintenance#429]
# Description
The standards webpage fails to render

# Area Affected
All of it
Fails on mobile Safari and Chrome iOS

# Change Proposed

**Comment by CDR-API-Stream** [comment]
The issue has been moved to [standards staging issue #63](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/63) because it represents an issue with the formatting of the standards and the supporting build code for generating the standards. It is not an issue pertaining to the data standards itself.
