### ISSUE TITLE
[CDS Spec documentation bug- Is x-fapi-auth-date header mandatory or optional]

### ISSUE THREAD

**Issue by AnantVijay-Cuscal** [ConsumerDataStandardsAustralia/standards-maintenance#430]
# Description
On CDS API specs x-fapi-auth-date is Optional for Banking and Common APIs. However, the description says "Required for all resource calls (customer present and unattended). Not to be included for unauthenticated calls." https://consumerdatastandardsaustralia.github.io/standards/#banking-apis 
Could you please update the Required and Description column to align with each other.

# Area Affected
Required column in Parameter section of CDS API specifications for Banking and Common APIs. Also the swaggers for these APIs

# Change Proposed
On CDS API specs x-fapi-auth-date is Optional for Banking and Common APIs. However, the description says "Required for all resource calls (customer present and unattended). Not to be included for unauthenticated calls." https://consumerdatastan
![x-fapi-auth-date](https://user-images.githubusercontent.com/94022858/141024835-26220fd1-3fa4-4c81-9f7a-a228b4777190.JPG)
dardsaustralia.github.io/standards/#banking-apis 
Could you please update the Required and Description column to align with each other.

**Comment by CDR-API-Stream** [comment]
Hi @AnantVijay-Cuscal,
 
This is a documentation error. "x-fapi-auth-date" is mandatory for all authenticated resource endpoints but not the unauthenticated endpoints as described in the [HTTP Headers section](https://consumerdatastandardsaustralia.github.io/standards/index.html#http-headers).
 
In the resource endpoint descriptions, we have "Optional" in the required column (see [Get Accounts](https://consumerdatastandardsaustralia.github.io/standards/index.html#get-accounts)). This is a documentation error and it should read "Mandatory".
 
This issue will be fixed in the next version of the standards.

**Comment by CDR-API-Stream** [comment]
These changes have been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.15.0...maintenance/430

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/22) for further details.
