### ISSUE TITLE
CDR Register OpenID Configuration does not specify token signing algorithm support

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#440]
# Description
This issue has been raised to track [CDR Register issue 169](https://github.com/ConsumerDataStandardsAustralia/register/issues/169) through the standards maintenance process.

Please refer to [CDR Register issue 169](https://github.com/ConsumerDataStandardsAustralia/register/issues/169) for details

**Comment by perlboy** [comment]
The Standards do not specify that a Holder is _required_ to use the Register discovery document in the first place, in fact if memory serves the documentation of its existence is a (relatively) recent addition. 

Perhaps it should because then it would be possible to avoid needlessly redefining upstream specifications under the auspices of "Client Authentication".

**Comment by CDR-API-Stream** [comment]
This change was incorporated into [release v1.15.0](https://consumerdatastandardsaustralia.github.io/standards/includes/releasenotes/releasenotes.1.15.0.html#v1-15-0-release-notes). Refer to [Decision 212](https://github.com/ConsumerDataStandardsAustralia/standards/issues/22) for further details.

**Comment by CDR-API-Stream** [comment]
@perlboy Thanks for your comments. 

Feature negotiation and change management are topics we will focus on early this year. Setting expectations on change management with the CDR Register discovery endpoint would be a relevant topic to include in this discussion.

I will provide a link once this decision proposal is created.

**Comment by CDR-API-Stream** [comment]
Closing as complete
