### ISSUE TITLE
CORS typos in CDR

### ISSUE THREAD

**Issue by chrisdlangton** [ConsumerDataStandardsAustralia/standards-maintenance#447]
# Description
I'm told fixing typos requires this to be created first

# Area Affected
CORS

# Change Proposed
The PR is https://github.com/ConsumerDataStandardsAustralia/standards/pull/224

# DSB Proposed Solution
The current DSB proposal for this issue is in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/447#issuecomment-1217417737).

**Comment by CDR-API-Stream** [comment]
The DSB proposal is to simply fix this typo

**Comment by CDR-API-Stream** [comment]
This issue was discussed in the [maintenance iteration call](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(17-August-2022)#meeting-minutes) held on 17/08/2022. 

The consensus feedback from participants was to fix the typo but not include the additional information suggestions because they do not consider MTLS protections and will cause conflicts if the statements are adopted for all endpoints.

This change has been staged for review: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.19.0...maintenance/447

**Comment by CDR-API-Stream** [comment]
This change has been updated to target v1.20.0: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.20.0...maintenance/447
