### ISSUE TITLE
Encryption algorithm for ID tokens is not specified

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/standards-maintenance#45]
# Request For Clarification
The Tokens section of the information security profile specifies that ID tokens must be encrypted. However the type of encryption (symmetric or asymmetric) and choice encryption algorithm has not been defined. Please specify which encryption type should be used from the available options in the [OIDC Core](https://openid.net/specs/openid-connect-core-1_0.html#encryption) normative reference and outline the mechanism of key exchange for this encryption method. 

Additionally, we have these questions:
1.	What are the algorithms that data holders and recipients must support for ID token encryption? (i.e. which asymmetric or symmetric algorithms)
2.	How will the encryption algorithms be exchanged between parties and configured?
    1. Statically by referencing appropriate algorithms and encodings in the standards
    2. Dynamically by requesting ACCC add id_token_encrypted_response_alg and, optionally, id_token_encrypted_response_enc to the [dynamic client registration request jwt](https://cdr-register.github.io/register/#registration-request-using-jwt). 

Westpac recommends asymmetric ID token encryption where the mechanism for key exchange is as per [OIDC Core](https://openid.net/specs/openid-connect-core-1_0.html#encryption). That is, the data holder will reference the authorised data recipient’s JWKS endpoint and select an encryption public key for an algorithm it supports. 

Notwithstanding the above, we also query as to if the encryption requirement for ID tokens should be removed entirely from the standard? Given, the complexity of the above, the fact this issue has not yet been dealt with in the standards and the fact that no PII is exchanged in the ID token (refer to this issue), this appears a viable option.

**Comment by anzbankau** [comment]
ANZ support the need for further clarification on this topic.

**Comment by CDR-API-Stream** [comment]
This issue is largely a duplicate of issue https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/12.

As responded in that issue the normative standards referenced by the CDR standards apply.

This includes OIDC and FAPI R/W. OIDC describes how the implemented algorithm is communicated and how key exchange should occur.  FAPI R/W gives further detail and constrains the algorithms available.

**Comment by WestpacOpenBanking** [comment]
This issue is still unresolved. Open ID Connect Core states in [section 3.1.3.7](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.3.7) that the keys and algorithms used for ID token are specified during client registration but these are not exchanged in the current [dynamic client registration specification](https://cdr-register.github.io/register/#client-registration). There are two options to resolve this issue:
 
1.	Remove ID token encryption and any PII claims from the data standards.
2.	Add these details to the dynamic client registration specification. 
 
We believe that Option 1 is the most pragmatic approach in support of February implementation.
 
We will also raise an issue in the register repository.

**Comment by pcurtisrab** [comment]
Regional Australia Bank provides our reading of the standard in our hope to clarify the detail.

[Section 10.2 in OIDC](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.10.2) which clarified this for us.

![image](https://user-images.githubusercontent.com/50900464/70583350-918a4080-1c11-11ea-9568-7e837d1264c4.png)

From this we gather the understanding as follows:

1. The Data Holder (as the encrypting party in this scenario), must choose an encryption key from our JWKS and apply the process in OIDC 10.2 in order to encrypt the signed JWT.
2. In the absence of any other mechanism for the DR to define which encryption enc and alg values are supported, the Data Holder needs to infer these from the JWKs available in the JWK Set, and the Data Recipient needs to be able to decrypt using any of the those JWKs.
3. In case the `id_token_encryption_enc_values_supported` and `id_token_encryption_alg_values_supported` from OIDC Discovery section 3 are not supplied by the OP, it is assumed that all values are supported.
4. Where the `id_token_encryption_enc_values_supported` and/or `id_token_encryption_alg_values_supported` are specified, the Data Recipient must ensure that they publish corresponding keys and support the content encryption algorithms.
5. Symmetric encryption is not possible, since `client_secret` is not used for client authentication.

We note that due to the lack of any mandatory algorithms in the JWA specification (see section [4.1](https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-4.1)), there is no general guarantee that participants in the ecosystem will be able to communicate, even if they are fully standards compliant.
