### ISSUE TITLE
NFR Binding on Dynamic Client Registration(DCR) Response Time

### ISSUE THREAD

**Issue by Dinushi** [ConsumerDataStandardsAustralia/standards-maintenance#451]
# Description
According to the Decision Proposal[ 208](https://github.com/ConsumerDataStandardsAustralia/standards/issues/208) - Binding NFRs,  the Data Standard has currently set 1000ms as the response time threshold for the Dynamic Client Registration (DCR) API.

But the DCR registration request involves few external calls (1. Registration validation by ADR, 2. SSA validation, 3. Sector identifier) whereas the performance on those external endpoints is beyond the control of the data holder.

It is not reasonable to factor these external dependencies outside of the Data Holders sphere of control into this 1000ms overall response time threshold defined for the DCR API.

I am posting this on behalf of WSO2.

# Area Affected
Dynamic Client Registration, NFR

# Change Proposed

In the current standard, a response time of 4 milliseconds is defined for unattended traffic. Similarly, increase the response time threshold for the DCR requests to allow some fragment for external requests.

The same change as proposed by [NAB](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/409)

**Comment by Dinushi** [comment]
Could you please provide the DSB's response for this issue ?

**Comment by CDR-API-Stream** [comment]
Hi @Dinushi, Maintenance Iteration 10 commences next Wednesday. This issue has been added to the backlog. The first meeting will involve discussion of which change requests should be prioritised for consultation this iteration. I'd encourage you to participate in that backlog grooming and prioritisation process.

**Comment by nils-work** [comment]
As this change refers to "The same change as proposed by [NAB](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/409)", and that referenced issue has since been closed with a summary provided in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/409#issuecomment-1231064892), with a subsequent issue raised for further review [here](https://github.com/ConsumerDataStandardsAustralia/future-plan/issues/94), I propose this issue be closed on 30 June 2023 unless there are further comments.
