### ISSUE TITLE
Distributor needed for EnergyPlan.geography object

### ISSUE THREAD

**Issue by joe-aer** [ConsumerDataStandardsAustralia/standards-maintenance#512]
# Description
When the energy standards was in draft, the geography object contained a distributor string field (child of the supply area object) that identified the distributors that operated in the postcodes where a plan was available.

When the energy standards went live, the supply area, including the distributor field was removed.

See DP190: https://github.com/ConsumerDataStandardsAustralia/standards/issues/190 for background.

Whilst the removal of the supply area object was the correct decision, the removal of the distributor was not.

In the context of a price comparator, e.g. Energy Made Easy, the distributor is important criterion for identifying the plans that are relevant for a consumer when more than one distributor operates in their postcode. Without the distributor being selected, comparator results may contain plans that are unavailable and irrelevant for a consumer by virtue of their property not being on a distributor's network.

By way of example, the postcode of Tarban NSW 2372 is serviced by both Ergon and Essential Energy.

We feel that without the distributor data being available, price comparators would be unable to provide consumers with a quality service.

# Area Affected
The `EnergyPlan.geography` object schema.

# Change Proposed
The addition of a `EnergyPlan.geography.distributors[]` string array field.

While an array is proposed, there is typically only one distributor per product but it is important to offer the flexibility for any exceptions to this.

**Comment by CDR-API-Stream** [comment]
As per action raised in [MI11 session](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-11:-Agenda-&-Meeting-Notes-(25-May-2022)) on 25th May to assess and re-prioritise energy items, the DSB is including this CR in MI11 for consultation.

@joe-aer, do you propose the `EnergyPlan.geography.distributors[]` array field to be mandatory?  The assumption here is that this value is also held by Retailers.

Feedback from other participants is welcome.

**Comment by joe-aer** [comment]
> @joe-aer, do you propose the `EnergyPlan.geography.distributors[]` array field to be mandatory? The assumption here is that this value is also held by Retailers.

Yes, I am proposing that the distributors array field should be both mandatory and contain at least one item. It would also be my assumption that retailers would know that distributors that operate in their retail areas.

The challenge that I foresee with this field is ensuring consistency across DHs of the string content of the array items. One solution could be for DHs to manually reference the distributor names published on the [AER's website](https://www.aer.gov.au/consumers/who-is-my-distributor).

**Comment by CDR-API-Stream** [comment]
This issue was discussed during the Energy MI call on 14th June.

Feedback during the call suggested that whilst including the `distributors` array would be ok, it should be optional.  However, @joe-aer makes good [point](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/512#issuecomment-1146953447), there appears to be no scenario where a distributor for a given account/plan would not be known to a retailer.  

As mentioned during the call, if a DH holds value for an optional field they are required to provide it as per [CDR standards ](https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions)(i.e. they are not optionally implementable by the DH).  The DH will have to share the value of `distributors` if they have it even if it is optional.

The DSB is seeking feedback to understand if there are any scenarios where an active account/plan can exist without a distributor? If there is no such case, the DSB proposes to take @joe-aer's recommendation and add `EnergyPlan.geography.distributors[]` as a mandatory array.

**Comment by perlboy** [comment]
On review of the existing payloads `EnergyPlan` isn't actually used anywhere other than Get Generic Plans and Get Generic Plan Details? On this basis a DH would only be supplying this value voluntarily as EME is the only body mandated to supply it?

**Comment by joe-aer** [comment]
Splitting hairs I know, but if a DH voluntarily provisions the Get Generic Plans and Get Generic Plan Detail endpoints then it becomes mandatory for them to provide the `EnergyPlan.geography.distributors[]` field/value. And yes, both the AER and DELWP systems can provide the distributor field/value.
