### ISSUE TITLE
BankingProduct productId should not include & or / or other characters that can't be in a URI

### ISSUE THREAD

**Issue by ajduncanson** [ConsumerDataStandardsAustralia/standards-maintenance#523]
# Description
Several Banking Data Holders are using characters in their productId strings that make it impossible to use them in a call to Get Product Details.

# Area Affected
Schema

# Change Proposed
Change schema for BankingProduct to ensure that productId does not contain characters that can't be used in the URI of a call to the Get Product Details endpoint.

**Comment by ajduncanson** [comment]
Specifically:
- BankVic (&)
- MOVE Bank (&)
- Goulburn Murray Credit Union (/)

**Comment by CDR-API-Stream** [comment]
@ajduncanson, IDs in the CDR standards are open with regards to characters that are able to be used.  The expectation for IDs that are included in URLs as path parameters (like ProductID, AccountId, ServicePointID, etc) are that they should be URL encoded.  For example a / should be replaced with %2F.

If the banks do not respond successfully to a URL encoded ID provided as a path parameter then they would already be considered non-standards compliant.  They have provided a product ID which cannot be used to obtain the associated product detail.

**Comment by perlboy** [comment]
Looks like 2 of the 3 listed above have fixed this issue. @ajduncanson it is a specific core banking vendor who has _very_ poor input/output control on results. It allows printing of unescapted `productId` but doesn't deescape it when requested directly.

**Comment by nils-work** [comment]
As the [comment above](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/523#issuecomment-1195351697) notes, this issue is not expected to result in a change to the Standards.
Unless there are further comments, this issue will be closed on 30 June 2023.

The [comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/523#issuecomment-1196432703) regarding the operation of the Product Comparator demo will be reviewed.

For any further assistance with compliance and data quality issues, the ACCC recently published [Clarification of specific Data Quality obligations](https://cdr-support.zendesk.com/hc/en-us/articles/7044968934799-Clarification-of-specific-Data-Quality-obligations) which includes a section on **Reporting Data Quality Issues**.

**Comment by nils-work** [comment]
Hi @ajduncanson, @perlboy 
Thanks for raising this issue. The [Product Comparator (demo)](https://consumerdatastandardsaustralia.github.io/product-comparator-demo/) now encodes the `productId` path parameter in a request to **Get Product Detail**.
