### ISSUE TITLE
Fix spelling, grammar and punctuation errors across the API specification

### ISSUE THREAD

**Issue by johnjenkman** [ConsumerDataStandardsAustralia/standards-maintenance#527]
# Description
_Brief description of the issue that is leading to the change being required_
There are numerous spelling, grammar and punctuation errors throughout OpenAPI specification in the standards. These errors cascade down into projects that rely on the standards when using code generation. This issue has been raised to correct _some_ of those errors.

# Area Affected
_Describe the area of the standard that is proposed to be amended._ 

- [cds_admin.json](https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/swagger-gen/api/cds_admin.json)
- [cds_banking.json](https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/swagger-gen/api/cds_banking.json)
- [cds_common.json](https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/swagger-gen/api/cds_common.json)
- [cds_energy.json](https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/swagger-gen/api/cds_energy.json)
- [cds_energy_sdh.json](https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/swagger-gen/api/cds_energy_sdh.json)
- [cds_register.json](https://github.com/ConsumerDataStandardsAustralia/standards/blob/master/swagger-gen/api/cds_register.json)

# Change Proposed
_A detailed description of the specific change (or options for change) proposed. The more specific the proposal the easier investigation and consultation on the issue will be._

Following standard operating procedures of a Git repo, I could have raised a simple pull request on the [standards](https://github.com/ConsumerDataStandardsAustralia/standards) repo to quickly correct this, but the rules of engagement for that repository state that pull requests are not allowed :|

> Please refrain from initiating new issues or pull requests in this repository due to the need for formal approval of all aspects of the standards

The new issue template in this repository asks for:
> A detailed description of the specific change (or options for change) proposed. The more specific the proposal the easier investigation and consultation on the issue will be.

In line with that request, I have attached a git diff that provides the detailed and specific changes that will correct some of these issues.

[fix-spelling-mistakes-diff.txt](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/files/9024295/fix-spelling-mistakes-diff.txt)

**Comment by nils-work** [comment]
Thanks @johnjenkman 
Some of the more common issues you've identified appear to be -
- changing `end points` to one word `endpoints`
- standardising `post codes` to `postcodes`
- using only single spaces between sentences in description text
- changing `Array of valid Australian post codes that are included from the plan.` to something more like `Array of valid Australian postcodes that are eligible for the plan.`
- remove the repeated `are` in the text `If the contents are are otherwise sensitive` in two places
- Add a full-stop to the end of description sentences, such as `ID of the account to get transactions for. Must have previously been returned by one of the account list end points`
- correct typo `accross`
- correct typo `smooting` in two places

**Comment by CDR-API-Stream** [comment]
The following issues will be addressed as part of MI14:

- standardising `post codes` to `postcodes`
- remove the repeated `are` in the text `If the contents are are otherwise sensitive in two places`
- correct typo `accross`
- correct typo `smooting` in two places

`end points` will be standardised to `endpoints` at a later stage as it is a large change.

**Comment by nils-work** [comment]
Initial set of staged changes are outlined in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/565#issuecomment-1517331126).

**Comment by nils-work** [comment]
As noted in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/411#issuecomment-2313825817) related to [above](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/527#issuecomment-1517318902), part of this change was incorporated in version Standards 1.32.0.

Staging issue [#431 - Fix spelling, grammar and punctuation](https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/431) will be a continuation of these changes.
