### ISSUE TITLE
Update SSA and Client Registration standards for JARM and Authorization Code Flow

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#547]
# Description
To support Phase 3 FAPI 1.0 migration, update the DCR APIs to specify JARM and Authorization Code Flow support.

# Area Affected
Dynamic Client Registration APIs
response_types enumeration

# Change Proposed
* Add "code" to the valid response_types enumeration values in the "Registration Request using JWT"
* Update DCR Registration Request JWT to support JARM:
  * `authorization_signed_response_alg`
  * `authorization_encrypted_response_alg`
  * `authorization_encrypted_response_enc`

# DSB Proposed Solution

The DSB proposed solution is presented [here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/547#issuecomment-1306592697).

**Comment by CDR-API-Stream** [comment]
See https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/458 and [comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/458#issuecomment-1228086160) for further information.

**Comment by CDR-API-Stream** [comment]
This issue was discussed in the last MI call. The DSB Proposed Solution has been updated as follows:

1. Add "code" to the valid response_types enumeration values in the "Registration Request using JWT"  
  > Array of the OAuth 2.0 response type strings that the client can use at the authorization endpoint. **Permitted values: [`code`, `code id_token`]** representing Authorization Code Flow and OpenID Connect Hybrid Flow respectively.

2. Add the following claims to the RegistrationProperties for Dynamic Client Registration APIs (PUT and POST for requests, and the GET response):

Claim | Required | Description
-- | -- | --
authorization_signed_response_alg | Conditional | The signing algorithm to use for JWT Secured Authorization Response Mode (JARM). Required when JARM is used for Authorization Code Flow: where response_type value `code` in conjunction with the response_mode value `jwt` (or variant) is used. 
authorization_encrypted_response_alg | Conditional | The JWE `alg` algorithm to use for encrypting authorization responses in JWT Secured Authorization Response Mode (JARM). Required if `authorization_encrypted_response_enc` is provided.
authorization_encrypted_response_enc | Conditional | The JWE `enc` algorithm to use for encrypting authorization responses in JWT Secured Authorization Response Mode (JARM). When `authorization_encrypted_response_enc` is included, `authorization_encrypted_response_alg` **MUST** also be provided. Required if the Data Holder specifies response encryption algorithms in accordance with JARM. If both signing and encryption are requested, the response will be signed then encrypted, with the result being a Nested JWT, as defined in JWT [RFC7519]. The default, if omitted, is that no encryption is performed. 


3. Update the "OpenID Provider Configuration End Point" section in accordance with #479 such that the following parameters are included:
  * `authorization_signing_alg_values_supported`: CONDITIONAL. The list of JWS algorithms for signing the authorization response in accordance with [JARM]. Required when supporting Authorization Code Flow and [JARM].
  * `authorization_encryption_alg_values_supported`: OPTIONAL. The list of JWE `alg` algorithms for encrypting the authorization response in accordance with [JARM]. Required if `authorization_encrypted_response_enc` algorithms are offered.
  * `authorization_encryption_enc_values_supported`: OPTIONAL. The list of JWE `enc` algorithms for signing the authorization response in accordance with [JARM]. The default, if omitted, is that no encryption is performed.

4. The changes would have an obligation date of April 7th 2023 in alignment with the FAPI 1.0 Phase 3 migration obligation date.

**Comment by CDR-API-Stream** [comment]
The Data Standard's Chair has approved this issue be treated as urgent in combination with #479.

**Comment by markverstege** [comment]
Last maintenance iteration call we discussed defining the error scenarios for registration and negotiation when using JARM for the Authorization Code Flow. The following scenarios are presented below with proposed behaviour. If there are any other error scenarios that need to be considered, please propose them in the comments.

It's worth providing some context and a set of solution design questions that will help frame the responses to each scenario.

## Context

### OIDC Hybrid Flow
This flow uses `response_type` "code id_token" and requires the use of the ID Token as a detached signature. As such, `id_token_encryption_alg_values_supported` and `id_token_encryption_enc_values_supported` are required to be published in the Data Holder's OIDD.

Data Holders may continue to support OIDC Hybrid Flow after the 7th of April 2023. If they do so, they need to continue supporting these negotiation parameters and ID Token signing and encryption.


### Authorization Code Flow

This flow uses `response_type` "code" and in accordance with [FAPI 1.0 Advanced](https://openid.net/specs/openid-financial-api-part-2-1_0-final.html#jarm), requires the use of JARM for message signing. A such, `authorization_signing_alg_values_supported` must be used and the Data Holder may support response encryption using `authorization_encryption_alg_values_supported` and `authorization_encryption_enc_values_supported`.

The algorithmic requirements are consulted on in [Issue 547: Clarification on Minimum Algorithm Required for JARM](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/479).

Data Holders must support this flow no later than the 7th of April 2023.

### Solution Questions

1. The [JARM spec](https://bitbucket.org/openid/fapi/src/master/oauth-v2-jarm.md) is ambigious when the client omits the `authorization_encrypted_response_alg` client metadata value. The JARM specification states that "The default, if omitted, is that no encryption is performed". Should Data Holders support no response encryption when this value is omitted, _even if the Data Holder supports encryption and offers "RSA-OAEP" and/or "RSA-OAEP-256"_? The quoted statement in the JARM spec could be interpreted as:

    * Option 1a: Always allow a "no response encryption" option for the client
    * Option 1b: If the Data Holder advertises one or more "alg" algorithms, the client MUST use one of the valid algorithms (that is, "no response encrytpion"). The Data Holder will return an error response if the `authorization_encrypted_response_alg` is omitted when the Data Holder advertises "alg" algorithm support.

2. Should a Data Holder that no longer supports OIDC Hybrid Flow reject response_type "code id_token" being included in the client registration (e.g. if `"response_types": ["code", "code id_token"]` is presented  ?
    * Option 2a: Ignore "code id_token" and constrain only to "code"
    * Option 2b: reject the registration request with an applicable oAuth error (i.e. "invalid_client_metadata")

3. Should a Data Holder that no longer supports OIDC Hybrid Flow ignore `id_token_signed_response_alg`, `id_token_encrypted_response_alg`, `id_token_encrypted_response_enc`

    * Option 3a: Ignore the parameters for client registration when OIDC Hybrid Flow is not supported: onus is on the Data Holder to ignore these parameters to minimise impact to ADRs 
    * Option 3b: Return an error if any of these parameters are present when OIDC Hybrid Flow is not supported: All Data Holders return an error and the onus is on the ADR to handle this
    * Option 3c: At the discretion of the Data Holder: onus is on the ADR to handle errors

### Proposed JARM support

If the Data Holder does not support response encryption they may do so by providing an empty array for the associated parameters or omit them from their OIDD. ADRs should be capable of handling both.

```
"authorization_encryption_alg_values_supported": [],
"authorization_encryption_enc_values_supported": []

# is equivalent to

"authorization_encryption_alg_values_supported": null,
"authorization_encryption_enc_values_supported": null
```

The parameters may be omitted from the OIDD. This is the equivalent of the empty arrays.

JARM states that for client metadata `authorization_encrypted_response_alg`:

> The default, if omitted, is that no encryption is performed.

JARM also states that for `authorization_encrypted_response_enc`:

> If `authorization_encrypted_response_alg` is specified, the default for this value is `A128CBC-HS256`

In other words, if a value for `authorization_encrypted_response_alg` is specified and `authorization_encrypted_response_enc` is not specified then the default `enc` algorithm is `A128CBC-HS256`. This value is permitted by the CDS. See https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/479.


## Client Metadata Negotiation Scenarios

The following scenarios consider incorrect values passed by the ADR during registration of their client with the Data Holder. This may include new registrations as well as updates to existing registrations.

| \# | Scenario |  Pre-Conditions | Assertion(s) | Result |
| -- | -- | -- | -- | -- |
| 1 | Invalid `authorization_signed_response_alg` client metadata value | <ul><li>Data Holders correctly supports JARM and Authorization Code Flow</li><li>ADR is attempting the register for Authorization Code Flow with JARM</li></ul> | Where `authorization_signed_response_alg` is <br><ul><li>null, or</li><li>empty string (""), or</li><li>not ("PS256" or "ES256")</li></ul> | oAuth error response (`error` value): "invalid_client_metadata" |
| 2 | Invalid <code>authorization_encrypted_response_alg</code> client metadata value | <ul><li>Data Holder correctly supports JARM and Authorization Code Flow</li><li>Data Holder advertises response encryption</li></ul> | <p>Where <code>authorization_encrypted_response_alg</code> is </p><ul><li>not null, and</li><li>empty string (&quot;&quot;), or</li><li>not (&quot;RSA-OAEP&quot; or &quot;RSA-OAEP-256&quot;)</li></ul> | <p>oAuth error response (<code>error</code> value): &quot;invalid_client_metadata&quot;</p> |
| 3 | Omitted <code>authorization_encrypted_response_alg</code> client metadata value | <ul><li>Data Holders correctly supports JARM and Authorization Code Flow</li><li>Data Holder advertises response encryption</li></ul> | <p>Where <code>authorization_encrypted_response_alg</code> is </p><ul><li>null</li></ul> | <ul><li>Successful client registration</li><li>No response encryption is performed</li></ul> |
| 4 | Invalid <code>authorization_encrypted_response_enc</code> client metadata value | <ul><li>Data Holders correctly supports JARM and Authorization Code Flow</li><li>Data Holder requires response encryption</li></ul> | <p>Where <code>authorization_encrypted_response_enc</code> is </p><ul><li>not null, and</li><li>empty string (&quot;&quot;), or</li><li>not (&quot;A256GCM&quot; or &quot;A128CBC-HS256&quot;)</li></ul> | <p>oAuth error response (<code>error</code> value): &quot;invalid_client_metadata&quot;</p> |
| 5 | Omitted <code>authorization_encrypted_response_enc</code> client metadata value | <ul><li>Data Holders correctly supports JARM and Authorization Code Flow</li><li>Data Holder requires response encryption</li></ul> | <p>Where <code>authorization_encrypted_response_enc</code> is </p><ul><li>null</li></ul>| <ul><li>Successful client registration</li><li>Response encryption is performed</li><li><code>authorization_encrypted_response_enc</code> defaults to<code>A128CBC-HS256</code></li></ul>|
| 6 | Valid <code>authorization_encrypted_response_enc</code> and missing <code>authorization_encrypted_response_alg</code> client metadata value | <ul><li>Data Holders correctly supports JARM and Authorization Code Flow</li><li>Data Holder requires response encryption</li><li>ADR client registration includes a valid <code>authorization_encrypted_response_enc</code> value</li></ul> | <p>Where </p><ul><li><code>authorization_encrypted_response_enc</code> is in (&quot;A256GCM&quot; or &quot;A128CBC-HS256&quot;)</li><li><code>authorization_encrypted_response_alg</code> is null</li></ul> | <p>oAuth error response (<code>error</code> value): &quot;invalid_client_metadata&quot;</p> |


## Transition Negotiation Scenarios - Existing Client

These scenarios consider the transition of the Data Holder supporting OIDC Hybrid Flow, Authorization Code Flow and the retirement of OIDC Hybrid Flow. These scenarios also consider what happens if the Data Holder requires response encryption or retires response encryption.

In all of these scenarios there remains a responsibility on the ADR to monitor each Data Holder's OIDD to discover changes that may impact their client registrations.

Assumptions: 
- the existing client is registered for OIDC Hybrid Flow
- the existing client is updating its registration to use Authorization Code Flow with JARM
- the existing client is registering a new client or updating its existing client registration to use Authorization Code Flow with JARM
- the ADR may register a client to use both OIDC Hybrid Flow and Authorization Code Flow if the Data Holder supports both
- if the ADR is registered to support both OIDC Hybrid Flow and Authorization Code Flow and the Data Holder removes support for OIDC Hybrid Flow, the existing client registration will be unaffected but the ADR can no longer use OIDC Hybrid Flow to establish authorisations.

| \# | Scenario |  Pre-Conditions | Assertion(s) | Result |
| -- | -- | -- | -- | -- |
| 7 | Authorization Code Flow + JARM and <em>no</em> response encryption | <ul><li>Data Holder supports Authorization Code Flow in accordance with FAPI 1.0 and CDS 1.20.0</li><li>Data Holder advertises &quot;code&quot; as a supported <code>response_types_supported</code> value ({ ... &quot;response_types_supported&quot;: [&quot;code&quot;,...]})</li><li>Data Holder advertises JARM as supported ({ ... &quot;response_modes_supported&quot;: [&quot;jwt&quot;,...], &quot;authorization_signing_alg_values_supported&quot;: [&quot;PS256&quot;, &quot;ES256&quot;]})</li><li>Data Holder <strong>does not</strong> support JARM response encryption. That is, <ul><li>the Data Holder <strong>does not</strong> advertise <code>authorization_encryption_alg_values_supported</code> and <code>authorization_encryption_enc_values_supported</code> in their OIDD, or</li><li>the Data Holder advertises empty arrays</li></ul> | <ul><li>The ADR verifies that the Data Holder supports Authorization Code Flow with JARM</li><li>The ADR updates its client registration such that,<ul><li>response_type &quot;code&quot;</li><li>&quot;response_mode&quot; &quot;jwt&quot;</li><li><code>authorization_signed_response_alg</code> is in (&quot;PS256&quot;, &quot;ES256&quot;)</li><li><code>authorization_encrypted_response_alg</code> is null or omitted</li><li><code>authorization_encrypted_response_enc</code> is null or omitted</li></ul> | <ul><li>Successful client registration (create or update)</li><li>No response encryption is performed</li><li>Client may continue to be registered for OIDC Hybrid Flow if that is supported by the Data Holder and requested by the Data Recipient</li></ul>|
| 8 | Authorization Code Flow with JARM and response encryption | <ul><li>Data Holder supports Authorization Code Flow in accordance with FAPI 1.0 and CDS 1.20.0</li><li>Data Holder advertises &quot;code&quot; as a supported <code>response_types_supported</code> value ({ ... &quot;response_types_supported&quot;: [&quot;code&quot;,...]})</li><li>Data Holder advertises JARM as supported ({ ... &quot;response_modes_supported&quot;: [&quot;jwt&quot;,...], &quot;authorization_signing_alg_values_supported&quot;: [&quot;PS256&quot;, &quot;ES256&quot;]})</li><li>Data Holder advertises <code>authorization_encryption_alg_values_supported</code> and <code>authorization_encryption_enc_values_supported</code> in their OIDD</li></ul> | <ul><li>The ADR verifies that the Data Holder supports Authorization Code Flow with JARM</li><li><p>The ADR updates its client registration such that,</p><ul><li>response_type &quot;code&quot;</li><li>&quot;response_mode&quot; &quot;jwt&quot;</li><li><code>authorization_signed_response_alg</code> is in (&quot;PS256&quot;, &quot;ES256&quot;)</li></ul></ul><p><strong>Assertion A:</strong></p><ul><li><code>authorization_encrypted_response_alg</code> is null or omitted</li></ul><p><strong>Assertion B:</strong></p><ul><li><code>authorization_encrypted_response_alg</code> is in <code>authorization_encryption_alg_values_supported</code> list (&quot;RSA-OAEP&quot; or &quot;RSA-OAEP-256&quot;)</li><li><code>authorization_encrypted_response_enc</code> is in <code>authorization_encryption_enc_values_supported</code> list (&quot;A256GCM &quot; or &quot;A128CBC-HS256&quot;)</li></ul><p><strong>Assertion C:</strong></p><ul><li><code>authorization_encrypted_response_alg</code> is in <code>authorization_encryption_alg_values_supported</code> list (&quot;RSA-OAEP&quot; or &quot;RSA-OAEP-256&quot;)</li><li><code>authorization_encrypted_response_enc</code> is null or omitted</li></ul> | <p><strong>Result A:</strong></p><ul><li>Successful client registration (create or update)</li><li>No response encryption is performed</li><li>Client may continue to be registered for OIDC Hybrid Flow if that is supported by the Data Holder and requested by the Data Recipient</li></ul><p><strong>Result B</strong></p><ul><li>Successful client registration (create or update)</li><li>Response encryption is performed using the selected algorithms</li><li>Client may continue to be registered for OIDC Hybrid Flow if that is supported by the Data Holder and requested by the Data Recipient</li></ul><p><strong>Result C</strong></p><ul><li>Successful client registration (create or update)</li><li>`authorization_encrypted_response_enc` is defaulted to `A128CBC-HS256` by the Data Holder</li><li>Response encryption is performed</li><li>Client may continue to be registered for OIDC Hybrid Flow if that is supported by the Data Holder and requested by the Data Recipient</li></ul> |
| 9 |DH switches on response encryption | <p>A Data Holder has supported JARM without response encryption. The Data Holder changes to support response encryption. </p><p><strong>Pre-Conditions</strong></p><ul><li>ADR has an existing valid client registration</li><li>Data Holder does not support response encryption</li><li>Data Holder changes its OIDD to advertise response encryption support</li></ul> |<p><strong>Assertion A:</strong> If Solution Question 1a is supported, the client continues to work as-is without a registration update and no response encryption is performed</p><p><strong>Assertion B:</strong> If Solution Question 1b is supported, the client MUST update their registration to use a suitable encryption algorithm set. Until such time, the client cannot perform any new authorisation requests successfully. Existing authorisations will continue to work correctly.</p><p><strong>Assertion C:</strong> If the ADR updates to use response encryption, the client must register a suitable encryption algorithm set</p> | <ul><li>Existing authorisations will continue to work.</li><li>For Assertion B and C, new authorisations will be rejected by the DH unless the ADR updates their client registration</li></ul> |
| 10 | DH switches off response encryption | <p>This requires the ADR to monitor the Data Holder&#39;s OIDD endpoint and identify the change to remove response encryption support. In this case, the ADR should update their client registration to remove any encryption algorithms. The Data Holder must ignore the encryption algorithms so they can continue to support ADR clients establishing new authorisation requests without breaking.</p><p>ADRs should be developed so they are resilient and able to identify that the response is not encrypted and cater for this.</p><p><strong>Pre-Conditions</strong></p><ul><li>ADR has an existing valid client registration</li><li>Data Holder supports response encryption</li><li>Data Holder changes its OIDD to remove response encryption support</li></ul>| <ul><li>Data Holder updates its OIDD and removes <code>authorization_encryption_alg_values_supported</code> and <code>authorization_encryption_enc_values_supported</code>.</li><li>ADR polls Data Holder OIDD endpoint to discover the change</li><li>ADR updates its client registration to stop using response encryption</li></ul> | Successful client registration update.<br/><ul><li>If the ADR does not poll the Data Holder and attempts to perform response encryption validation it should see that the response is not encrypted and verify this is correct in accordance with the OIDD of the Data Holder and complete the authorisation successfully.</li><li>The ADR will still have a client registered with a previously chosen response encryption algorithm - the ADR should update their client registration as soon as possible, but the Data Holder can ignore the registered encryption algorithm because they no longer support response encryption.</li></ul> |
| 11 | Client registration supports OIDC Hybrid Flow and Authorization Code Flow | <ul><li>ADR has an existing valid client registration with OIDC Hybrid Flow</li><li>Data Holder supports Authorization Code Flow and JARM</li></ul> | <ul><li>ADR polls Data Holder OIDD endpoint to discover the change</li><li>ADR updates its client registration to support both OIDC Hybrid Flow and Authorization Code Flow</li><li>ADR provides a registration request where <ul><li><code>response_types</code> = [&quot;code&quot;, &quot;code id_token&quot;]</li><li><code>id_token_signed_response_alg</code> is a valid value</li><li><code>id_token_encrypted_response_alg</code> is a valid value</li><li><code>id_token_encrypted_response_enc</code> is a valid value</li><li><code>authorization_signed_response_alg</code> is a valid value</li><li><code>authorization_encrypted_response_alg</code> is a valid value</li><li><code>authorization_encrypted_response_enc</code> is a valid value</li></ul></li></ul> | Successful client registration update for both OIDC Hybrid Flow and Authorization Code Flow |
| 12 | Data Holder removes OIDC Hybrid Flow support, client is already registered for Authorization Code Flow| <ul><li>ADR has an existing valid client registration with OIDC Hybrid Flow AND Authorization Code Flow</li><li>Data Holder supports Authorization Code Flow</li></ul>|<ul><li>Data Holder removes support for OIDC Hybrid Flow</li></ul> |<ul><li>ADR must only use Authorization Code Flow with JARM</li><li>ADR should update their client registration to remove OIDC Hybrid Flow </li><li>A Data Holder may remove OIDC Hybrid Flow support for all clients without a registration update</li><li>Any attempt by the ADR to initiate an authorisation request using `response_type` "code id_token" would be rejected</li></ul> |
| 13 |Data Holder removes OIDC Hybrid Flow, client is not registered for Authorization Code Flow | <ul><li>ADR has an existing valid client registration with only OIDC Hybrid Flow</li><li>Data Holder supports Authorization Code Flow</li></ul>|<ul><li>Data Holder removes support for OIDC Hybrid Flow</li><li>ADR performs a client registration update to register the client for Authorization Code Flow and JARM</li><li>ADR provides a registration request where <ul><li><code>response_types</code> = [&quot;code&quot;]</li><li><code>authorization_signed_response_alg</code> is a valid value</li><li><code>authorization_encrypted_response_alg</code> is a valid value</li><li><code>authorization_encrypted_response_enc</code> is a valid value</li></ul></li><li>ADR removes OIDC Hybrid Flow support<ul><li><code>response_types</code> = [&quot;code id_token&quot;] is not permitted</li><li><code>id_token_signed_response_alg</code> is not permitted</li><li><code>id_token_encrypted_response_alg</code> is not permitted</li><li><code>id_token_encrypted_response_enc</code> is not permitted</li></ul></li></ul> |<ul><li>ADR MUST only use Authorization Code Flow with JARM</li><li><p>ADR MUST update their client registration to register for Authorization Code Flow</p></li><li><p>A Data Holder may remove OIDC Hybrid Flow support for all clients without a registration update</p></li><li>Any attempt by the ADR to initiate an authorisation request using `response_type` "code id_token" would be rejected</li></ul> |

### Invalid Data Holder configuration
**If the Data Holder still supports OIDC Hybrid Flow:**

The Data Holder is in an invalid state. The ADR should not update thier client registration to use ACF because the Data Holder is non-compliant and does not support JARM with Authorization Code Flow.

The ADR continues to use their current registration. 

ADRs creating new client registrations should continue to use OIDC Hybrid Flow with the ID Token acting as the detached signature in accordance with [FAPI 1.0 Advanced s5.2.3.1](https://openid.net/specs/openid-financial-api-part-2-1_0-final.html#id-token-as-detached-signature-2)

**If the Data Holder does not support OIDC Hybrid Flow:**

Assuming the Data Holder has dropped support for OIDC Hybrid Flow and advertises they support ACF but doesn't support JARM, the Data Holder is non-compliant.

In this scenario, the ADR cannot perform any new authorisation requests successfully. Existing authorisations will continue to work as they only require the exchange of the existing refresh token for a short-lived access token.

**Comment by AG-IAM** [comment]
> 3. Should a Data Holder that no longer supports OIDC Hybrid Flow ignore `id_token_signed_response_alg`, `id_token_encrypted_response_alg`, `id_token_encrypted_response_enc`
>    
>    * Option 3a: Ignore the parameters for client registration when OIDC Hybrid Flow is not supported: onus is on the Data Holder to ignore these parameters to minimise impact to ADRs
>    * Option 3b: Return an error if any of these parameters are present when OIDC Hybrid Flow is not supported: All Data Holders return an error and the onus is on the ADR to handle this
>    * Option 3c: At the discretion of the Data Holder: onus is on the ADR to handle errors
> 
Since "openid" scope is mandatory in request object, shouldn't atleast the "id_token_signed_response_alg" be passed in the DCR call, as the id_token will be returned from token endpoint.

**Comment by tinagroark** [comment]
Clarification for decision write-up please - point 13 seems to indicate id_token encryption is not allowed for ACF.

My understanding is that DCR client metadata does not allow the ADR to differentiate id_token encryption for each flow, therefore the standard must support id_token encryption for ACF where the ADR is registered for both Hybrid Flow and ACF.

Can you clarify please if id_token encryption is OPTIONAL or NOT ALLOWED for ADRs who register solely for ACF?

**Comment by nils-work** [comment]
This change request was incorporated through https://github.com/ConsumerDataStandardsAustralia/standards/issues/282#issue-1486041781
