### ISSUE TITLE
Home Loan Revert rate and product is not available 

### ISSUE THREAD

**Issue by AdamGrockeSherlok** [ConsumerDataStandardsAustralia/standards-maintenance#569]
# Description
We currently don't have data on the post expiry home loan product. EG: if a loan is fixed and expires on 1/1/2023 it will automatically convert to a variable rate on 2/2/2023 and the variable interest rate that the customer pays is calculated based off a pre-determined discount that the customer is contracted to with that lender. If we contact the lender directly we can obtain this information so it does exist within their systems. 

This information is critical for consumers knowing what their product will convert to so they can make informed decisions prior to the expiry event. 

The current gaps we for home loans are..

1. "repaymentType" as 'Interest Only' that expires and converts to Principle and Interest
2. "lendingRateType" as FIXED' that expires but there is no data that is being made available that states that the repayment type will automatically convert to.
3. the loan product may also be a honeymoon rate that reverts from a low 2 or 3 year interest rate to a higher revert interest rate at the expiry date. 

# Area Affected
Describe the area of the standard that is proposed to be amended.  This could be one or more API end points or a specific section of the information security profile

# Change Proposed
We're proposing that a "revert" key be made available under "accounts". This will display all the 'accounts' data post fixed rate or interest only expiry date. Please note that other product will have similar revert requirements EG: personal loans, interest free credit card transfer periods etc.

 The "revert" key should include all the 'accounts' key data but post expiry.

you should also include the following data fields that are currently missing and would be useful
'revertstartdate' the day the revert account starts
'revertenddate' the day the revery account end
'revertdiscountrate' the discount being applied to the revert lending rate

**Comment by ShaneDoolanAdatree** [comment]
Adatree supports his change request. This is an example of feedback from industry experts now actively participating in CDR and finding critical gaps that are preventing one of the most important use cases from being realised.

**Comment by cuctrangsb** [comment]
If I understand it correctly, the intention of the lendingRates array is for this purpose and use case.
Although the description of the lendingRates in the standard for Get Account Detail appears to be incorrect (Fully described **deposit rates** for this account based on the equivalent structure in Product Reference), the response can be applicable to grandfathered product.

It might be a possibility to look at expanding or providing further rules and/or Enumerations on this lendingRates array instead of building new key under the Get Account Detail.
The below information that is applicable to the account should be stored in the bank's system whether the product is currently for sale or not.
Below is an example of the response for the revert rate that can be explored.

  "lendingRateType": "REVERT_RATE", (new enum)
      "rate": "string", (the rate that the account will revert to at the end of the fixed rate or interest only or introductory period. This is the rate that will be used to calculate the interest payable being applied to the lending balances as it stands at the time of the API call)
      "comparisonRate": "string", (should be null as existing accounts don't have comparison rates. We don't have and don't store this in our core banking system for existing accounts. This is applicable to PRD only)
      "calculationFrequency": "string",
      "applicationFrequency": "string",
      "interestPaymentDue": "IN_ARREARS",
      "repaymentType": "PRINCIPAL_AND_INTEREST",
      "loanPurpose": "INVESTMENT",
      "tiers": [
        {
          "name": "string",
          "unitOfMeasure": "DAY",
          "minimumValue": 0,
          "maximumValue": 0,
          "rateApplicationMethod": "WHOLE_BALANCE",
          "applicabilityConditions": {
            "additionalInfo": "string",
            "additionalInfoUri": "string"
          },
          "additionalInfo": "string",
          "additionalInfoUri": "string"
        }
      ],
      "additionalValue": "string",
      "additionalInfo": "string",
      "additionalInfoUri": "string"

The part that can be expanded is to include the below:

'revertstartdate' the day the revert account starts - I agree this is useful and should be included.
'revertenddate' the day the revery account end - I don't see the value of this field. Normally once the loan is reverted from Fixed rate, Interest only or Intro rate, the revert end date will be the Loan end date. For credit card and savings, we don't have this value so it should be set as conditional or optional.
'revertdiscountrate' the discount being applied to the revert lending rate - I think this adds little value to the customers. What they care about is the net rate that will be used to calculate the interest and the repayment on their loan. From my experience, customers rarely asked how much my discount is but how much my rate will be. It will also add little value if we don't supply the reference rate.

**Comment by nils-work** [comment]
A sample payload incorporating details from this issue has been posted in [this comment in issue 567](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/567#issuecomment-1459158602).

**Comment by AdamGrockeSherlok** [comment]
Agree that Nett rate should also be included however, that would be the Nett interest rate if it converted today. You can't forecast the Nett rate and DH will have an issue with this. 

We'd still want to see Discount included as that is important for our use case and will be known by the DH.

**Comment by nils-work** [comment]
Closing this maintenance issue, consultation will continue through [Decision Proposal 306](https://github.com/ConsumerDataStandardsAustralia/standards/issues/306).
