### ISSUE TITLE
CovaU VIC is presenting GreenPower amount values in cents, not dollars

### ISSUE THREAD

**Issue by garychapman** [ConsumerDataStandardsAustralia/standards-maintenance#571]
# Description
CovaU is currently presenting GreenPower `amount` values in cents, not dollars, in their VIC plans.

This can be observed in https://cdr.energymadeeasy.gov.au/covau/cds-au/v1/energy/plans/COV405797SS@VEC where 1.1c/kWh is represented as "1.10" when it should be "0.011".

Contrast with https://cdr.energymadeeasy.gov.au/covau/cds-au/v1/energy/plans/COV480391MRE2@EME where the same amount is correctly represented as "0.011"

# Change Proposed
GreenPower `amount` values should be universally presented in dollars.

**Comment by DannyDuong** [comment]
@garychapman Thanks for identifying this data issue.

This looks like a data entry issue by CovaU. In the manual we state the amount should be in dollars. Their description mentions c/kWh but the amount is entered in dollars, not cents (e.g. 1.1000 instead of 0.0110). 

This is not a CDR issue but an offer/ plan maintenance issue.
We will correspond with the retailer and get this rectified.

As such, please close off this change request

**Comment by garychapman** [comment]
@DannyDuong Thanks for taking action on this. For future reference, where is the best place to report these kinds of issues?
