### ISSUE TITLE
Where is the spec for the schema ResponseMetricsV4

### ISSUE THREAD

**Issue by jcthalys** [ConsumerDataStandardsAustralia/standards-maintenance#609]
# Description

Please I would like to find out the standard spec, which includes the schema **ResponseMetricsV4**.

- the current standard version 1.26.0:
  - https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_admin.yaml
  - Here the schema version is ResponseMetricsListV5
- the previous version 1.25.0:
  - https://consumerdatastandardsaustralia.github.io/standards-archives/standards-1.25.0/includes/swagger/cds_admin.yaml
  - Here the schema version is also ResponseMetricsListV5
- and this previous one 1.24.0:
  - https://consumerdatastandardsaustralia.github.io/standards-archives/standards-1.24.0/includes/swagger/cds_admin.yaml
  - Here the schema version is ResponseMetricsListV3, which is the one we need to support until May 2024.
  
Any information on that would be great
Thank you

**Comment by nils-work** [comment]
Hi @jcthalys 

You're correct that a Swagger/OAS file for Get Metrics v4 has not been published.

This is because only the 'latest' version is published, which was **v3 in v1.24.0** and **v5 in 1.25.0**. 
**v4** was essentially an interim version between those.

If you require a v4 file specifically, a suggestion may be to modify the v5 file from 1.26.0 to produce your own 'downgraded' version.

I hope that makes sense,
Thanks

**Comment by nils-work** [comment]
Hi @jcthalys 

Thanks for your question, if there are no further comments or changes to the Data Standards expected, this issue will be closed on 27 October 2023.
