### ISSUE TITLE
AuthorisationMetricsV2 abandonmentsByStage property descriptions and CDS Guide

### ISSUE THREAD

**Issue by anzbankau** [ConsumerDataStandardsAustralia/standards-maintenance#626]
# Description
There have been numerous questions (and DSB answers) about properties in the `abandonmentsByStage` object in Get Metrics. The following proposes minor refinements to property descriptions and a new 'Authorisations' section in the relevant CDS Guide page.

# Area Affected
 [Get Metrics](https://consumerdatastandardsaustralia.github.io/standards/#get-metrics) > [AuthorisationMetricsV2](https://consumerdatastandardsaustralia.github.io/standards/#tocSauthorisationmetricsv2)

# Change Proposed
1. Description fields in `abandonmentsByStage` object:
    Note: Bold italics are only used to highlight the proposed changes
    Before: The number of authorisations where the customer actively rejected the authorisation rather than abandoning the process
    After: The number of authorisations where the customer actively rejected/denied the authorisation **_at the final stage of the consent process_** rather than abandon~~ing~~ **_ed_** the process **_or experienced an interruption at an earlier stage_**
2. Additional 'Authorisations' section in CDS Guide page [CDR metrics and reporting by Data Holders](https://cdr-support.zendesk.com/hc/en-us/articles/6461435303823-CDR-metrics-and-reporting-by-Data-Holders) to clarify the terms 'abandon' and 'reject'. The final screen in the consent flow (allowing consumers to 'confirm' or 'deny' data sharing) has explicit actions, whereas a 'Cancel' on earlier screens should not be considered a 'rejection' but an 'abandonment' - along with time-out and technical interruptions.

# Reference
 1. Tickets #2125.2 and #2170 in Q&A section of [CDR Implementation call minutes of 7/12/23](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-7th-of-December-2023)

# DSB Proposed Solution
The proposed solution can be found in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/626#issuecomment-2044487918).

**Comment by nils-work** [comment]
Hi @anzbankau

For reference, this guidance was recently published and I think aligns to your proposal - [Get Metrics V5 abandonment by stages](https://cdr-support.zendesk.com/hc/en-us/articles/8485633822735-Get-Metrics-V5-abandonment-by-stages).

**Comment by nils-work** [comment]
To summarise, this issue proposes the following change to the description of the `rejected` property of [AuthorisationMetrics](https://consumerdatastandardsaustralia.github.io/standards/index.html?examples#cdr-admin-api_schemas_tocSauthorisationmetricsv2) - 

**Current**
> The number of authorisations where the customer actively rejected the authorisation rather than abandoning the process

**Proposed**
> The number of authorisations where the customer actively rejected/denied the authorisation at the final stage of the consent process rather than abandoned the process or experienced an interruption at an earlier stage

**Comment by anzbankau** [comment]
Thanks Nils.

That's the appropriate property and the revised description provides additional information that will be helpful to participants.

**Comment by perlboy** [comment]
As discussed in the call we don't believe the proposal as it stands is really in the interests of the Consumer and we raised this during the [definition of the endpoint](https://github.com/ConsumerDataStandardsAustralia/standards/issues/288#issuecomment-1516078621) in the first place. 

In addition, given this endpoint has already shipped we do not agree this is a minor clarification and as such request, if the DSB makes this change (which we don't agree with), that there be a suitable FDO that gives sufficient time to implement.

**Comment by nils-work** [comment]
This issue was discussed in the [20th March Maintenance Iteration call](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-18-Agenda-&-Minutes).

- One attendee requested that the [proposed change](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/626#issuecomment-1953781214) to the description of the `rejected` field be treated as a breaking change and an FDO provided to cater for differences in previous interpretations (but not to accommodate a new endpoint version). It was suggested that it may be possible to meet an [FDO](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#obligation-dates-schedule) within six months, but feedback from participants on a potential milestone would be valuable. Options could be **Y24 <span>#</span>4** (09/09/2024) or **Y24 <span>#</span>5** (11/11/2024).
- There was a concern raised in relation to the benefit to consumers from making this change.
- There was discussion around the granularity of potential reasons and terminology for abandonment, exiting, cancelling, and rejecting and whether these are active or passive, and whether they could be better distinguished in future versions if necessary.
- There was a question as to whether there was also a potential gap in the consistency of delivered CX in this flow (related to the availability and terminology used in navigation options provided by different Data Holders) and if there is potential to better define and pass more standardised detail back to ADRs via the oAuth error response where possible.
- It was noted that there could be a relationship between the issues described above and the intent of [#628 - Addition of a DH-side endpoint for querying the status of a consent establishment flow](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/628#issue-2038997000).

**Comment by biza-io** [comment]
As stated by @perlboy we believe the proposed description change is a breaking change requiring an FDO and request this be Y24 #5 to align with other FDOs proposed in this MI.

At a more holistic level Biza.io has formed the opinion that the proposed change is in fact detrimental to the value of the data being collected. Resolution of this issue may be best served through a more detailed consultation on another new version of Get Metrics that encapsulates abandonment throughout the stages of the consent flow.

**Comment by nils-work** [comment]
This issue will be reviewed again in Maintenance Iteration 19.

**Comment by nils-work** [comment]
**Update:** Based on discussion and feedback in [MI18](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-18-Agenda-&-Minutes), it is proposed that this change not be made. 

The DSB has provided [guidance](https://cdr-support.zendesk.com/hc/en-us/articles/8485633822735-Get-Metrics-V5-abandonment-by-stages) in relation to abandonment by stages, which can be referred to by Data Holders, however it is accepted that different interpretations of abandonment and rejection metrics have been inferred which will result in differing metrics being reported via Get Metrics v5.

This issue may continue to be considered in the context of issue [#628 - Addition of a DH-side endpoint for querying the status of a consent establishment flow](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/628), or other potential changes to authentication process requirements [in future](https://github.com/ConsumerDataStandardsAustralia/future-plan/issues/175).

**Comment by perlboy** [comment]
![image](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/assets/4291448/c86a2ca0-bedf-4db2-b847-d90f484c875a)

Can the guidance be updated to omit the suggestion of Cancel as well please. The description in the Standards is:

> The number of authorisations where the customer **actively rejected** the authorisation rather than abandoning the process

I don't think anyone would dispute clicking a Cancel button is an active rejection so omit'ing the suggestion ensures guidance is not seen as conflicting with the Standard while leaving the alternate interpretation (as per the original poster) open.

**Comment by nils-work** [comment]
Hi @perlboy 
As we will be proposing that the Standards do not change as a result of this request, we consider the guidance should remain unchanged for the time being as well.

**Comment by anzbankau** [comment]
@perlboy

The "clicking 'Cancel'" item in the list under the preIdentification, preAuthentication, preAccountSelection and preAuthentication count classifications relates to properties within the `abandonmentsByStage` object in [GetMetrics.AuthorisationMetricsV2](https://consumerdatastandardsaustralia.github.io/standards/#cdr-admin-api_schemas_tocSauthorisationmetricsv2) (with Description '*Customer abandonment count per stage of the consent flow*'), rather than the `rejected object for which you provided the Description.

We agree that clicking a Cancel button at any of these points (i.e., at any step prior to the final accept/confirm/deny stage) is an abandonment, not an active rejection, which is why it's listed in the actions/events that could cause the abandonment sub-count to be incremented in the diagram in the CDS Guide article. We believe this is consistent with the data standards so do not agree with your proposed change.

Our position (as stated in the MI18 call when this was last discussed) is that anything that results in a user not proceeding to the next step in a multi-step process (prior to the last) should be considered an 'abandonment' for the purposes of the metrics. While the term could be interpreted as an active choice made by the consumer (e.g., click the 'Cancel' button), an agreed purpose of the metrics is what's necessary for consistency and metrics aggregation accuracy. The list of causes for incrementing the sub-counts in the current diagram in the CDS Guide article provides this. Whether the consumer pressed cancel because they can't be bothered at that particular time or they have to catch a bus, or their session timed out or they experienced a technical interruption is not pertinent to the required metrics (as they are currently formulated).

**Comment by nils-work** [comment]
This issue was discussed in MI18, but no changes to the Standards were made. The closing position is described in [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/626#issuecomment-2044487918) and [this comment](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/626#issuecomment-2058501838).
