### ISSUE TITLE
New Enums for Voluntary disclosure of additional service overlays

### ISSUE THREAD

**Issue by NationalAustraliaBank** [ConsumerDataStandardsAustralia/standards-maintenance#664]
# Description
As per the Consumer Data Standard, the Service attribute within the Get Transaction Detail API has an Enum value of X2P1.01.
https://consumerdatastandardsaustralia.github.io/standards/#tocSbankingtransactiondetail
•	OSKO (X2P1) is the main overlay service offered under the New Payments Platform. 
•	The business service version (eg X2P1.XX) has incremented since original release and is currently operating under version four (eg X2P1.04). 
•	At an industry level, there’s an average of 100m transactions cleared/settled per month. 
o	This would translate to 200m transaction records per month that are restricted as a result of the current Open Banking schema.
o	Transaction growth is averaging +6.5% MoM increase
•	We can also refer to the published [RBA statistics](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.rba.gov.au%2Fstatistics%2Ftables%2F&data=05%7C02%7CYash.Luthra1%40nab.com.au%7Cff7b67eadf5f4ada8f2c08dcd3b2126e%7C48d6943f580e40b1a0e1c07fa3707873%7C0%7C0%7C638618008995340938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=OinADpc9fAzK8H04sghxJksSa%2Bk5etsCYwWejBqAsXc%3D&reserved=0) ([Direct Entry and NPP – Original Series – C6.1](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.rba.gov.au%2Fstatistics%2Ftables%2Fxls%2Fc06-1-hist.xlsx%3Fv%3D2024-08-09-17-39-58&data=05%7C02%7CYash.Luthra1%40nab.com.au%7Cff7b67eadf5f4ada8f2c08dcd3b2126e%7C48d6943f580e40b1a0e1c07fa3707873%7C0%7C0%7C638618008995362446%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=HxQaKXenruQCLTYjiiDVM%2BopbI0qiBnkoSOq4%2FMcAL0%3D&reserved=0)) for historic statistics
o	This shows us (per CCDEPNPPON) that since inception, the industry has processed there has been 3.95b OSKO payments and currently accounts for 75% of total reported payments cleared under NPP
o	This would be similarly multiplied for the context of Open Banking as 7.9b transaction records could not be shared as a result of schema failing to keep pace with the payment clearing stream
	This issue would also be observed for the ‘more recent’ business services, including:
SCTXBRDR - International payments cleared/settled via NPP (as an alternative to RTGS)
CATSCT - Salary, tax and superannuation payments 

This has been raised in Github previously (see references below), the standard has not been updated to reflect that SCT and X2P1 Enum values are all valid service types under NPP (and all the current / historical versions eg. X2P1.01, X2P1.02, X2P1.03, X2P1.04, SCT.04 etc).
https://github.com/ConsumerDataStandardsAustralia/standards/issues/28
https://github.com/ConsumerDataStandardsAustralia/standards/issues/41
[Service field in the Get Transaction Details API · Issue #229 · ConsumerDataStandardsAustralia/standards-maintenance · GitHub](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/229)

Please Note: Additional Enums should not cause any disruption to he current implementation of the other data holders as these Enums should be considered as voluntary data disclosure.

# Intention and Value of Change
Currently, the most recent relevant transactions ERI of value $8b are not available in the CDR ecosystem. These could go a long way in improved transaction classification and reconciliation. this change will make this valuable data to be potentially available to the ADRs while not impacting the current implementation for the data holders.

# Area Affected
x2p101Payload object under GetTransactionDetails

# Change Proposed
NAB proposes to offer additional Enums for the newer service overlays which could be considered as voluntary disclosures by those data holders who choose to share this information and the current implementation of other data holders should have no impact.
In [BankingTransactionDetails](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fconsumerdatastandardsaustralia.github.io%2Fstandards%2F%23cdr-banking-api_schemas_tocSbankingtransactiondetail&data=05%7C02%7CYash.Luthra1%40nab.com.au%7C422764507b174dd424c808dcd3ae5f4f%7C48d6943f580e40b1a0e1c07fa3707873%7C0%7C0%7C638617993105247959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=fL8wzY2%2Bo3I8HAx98WSoMwJb6%2FA%2FzGxepldP4LV5qEg%3D&reserved=0)
•	extensionUType enum value to be updated from “x2p101Payload” to “overlayServicePayload”
•	x2p101Payload object name to be renamed to “overlayServicePayload”
•	service enum to be uplifted to cover all the services and versions, e.g. X2P1.01, X2P1.02, X2P1.03, X2P1.04, SCT.04 etc.

# DSB Proposed Solution

The current DSB proposal for this issue is in https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/664#issuecomment-2415625607

**Comment by markskript** [comment]
Skript supports this change, with the added benefit in that it will bring some DHs into alignment with the standards where they have already started providing these enum's. That will allow us to remove custom DH-specific workaround code from our solution.

**Comment by CDR-API-Stream** [comment]
Hi @NationalAustraliaBank this is an important change to progress so thank you for raising it. 

Given that transaction data is designated in the CDR rules, this would be a mandatory binding standard, not a voluntary standard.

Schedule 3, section 1.3 (3) defines transaction data as required data.
> transaction data, in relation to a particular transaction
>      (a) means information that identifies or describes the characteristics of the transaction; and
>      (b) includes:
>               (i) the date on which the transaction occurred; and
>               (ii) any identifier for the counter-party to the transaction; and
>               (iii) if the counter-party is a merchant—any information that was provided by the merchant in relation to the transaction; and
>               (iv) the amount debited or credited pursuant to the transaction; and
>               (v) any description of the transaction; and
>               (vi) the “simple categorisation” of the transaction (for example, whether the transaction is a debit, a credit, a fee or interest).

**Comment by CDR-API-Stream** [comment]
Further to the identified service overlay types raised by @NationalAustraliaBank, the DSB has analysed the NPP service overlays in additional detail.

## NPP Service Overlays
The NPP architecture supports service “overlays” that can be provided on top of the NPP basic infrastructure. These overlay services define the data and messaging formats specific to the overlay.
As noted by @NationalAustraliaBank this change proposal, considers:
* Extending support for newer versions of the Osko / X2P1 service overlay
* Supporting the Single Credit Transfer (SCT) service overlay
* Supporting Category Purpose Payments
* Supporting the International Funds Transfer Instructions (IFTI) service overlay

### X2P1 versions to support
The Osko service overlay is currently incremented to version 5. These versions are updated when there are breaking changes to the NPP API interface contract. No changes to the X2P1 payment instruction have been identified, and thus no changes to ResponseBankingTransactionById extendedData schema are anticipated apart from the change in version of the X2P1 service. 

The way that extended transaction data is currently represented in the Data Standards is to represent the combination of service overlay and overlay version as a separate object structure denoted by unique union types. Given there is no change to the X2P1 payload across the five versions of the X2P1 service and given all service overlays inherit from the same core payment initiation notification structure (based on ISO20022), a simplification of the extended payload structure is proposed.

### New service overlays for consideration

**Basic Single Credit Transfers (BSCTs)**

Basic SCTs is the basic NPP business service that allows NPP participants to send payments over the NPP without an overlay. It is an individual transaction that will be cleared then settled. 
Because of the high degree of business service overlap between the SCT and X2P1 business services, Australian Payments Plus (AP+), who now operate the NPP, have earmarked the future augmentation of both the SCT and X2P1 services into a single overlay. This is likely to be the inclusion of SCT into the X2P1 business service. Whilst no future date has yet been set, the CDR rules have a requirement for banking Data Holders to share up to the previous seven (7) years of transaction history. As such, allowing Data Holders to share this transaction data remains relevant to the CDR.

**Category Purpose Payments**

NPP supports categorised payments for super, tax and payroll payments. These are largely similar to the other overlays in terms of data fields, however there are special usage and data requirements. This service helps third parties to instruct financial institutions on the purpose of the payment and priority. 
These payments are denoted by a specific purpose code and NPP guidance for representing additional information and additional reference information in the payment message, which can be presented to the payee. This can include more structured data elements or extended commentary in the payment from the employer, for example, “Adjustment pay for week ending 20/1/19” or “Commission payment for Quarter 1”, up to date details of hours paid, superannuation contributions or details relevant to the employee payslip.

For some category purpose payments like superannuation, these include additional consumer information including the superannuation provider identifier:

* **Superannuation identifier**: For superannuation category payments, the unique identification (USI) as assigned by the superannuation provider to a superannuation scheme. Specifies a character string with a maximum length of 35 characters

**International Funds Transfers Instructions (IFTIs)**

IFTIs are payments sent between an Australian bank and an overseas financial institution. They may pass through multiple Australian and overseas intermediary institutions on the way. An NPP payment may be used as the final leg of an 'inward' IFTI - that is, a payment originating overseas, sent through an NPP participant as an intermediary on the way to another NPP participant as the final destination. These payments are distinct from basic SCTs in that they incur additional obligations on the payer and payee participants and are defined by a separate service overlay.

**Previous consultations and considerations**

Previously banks have proposed extending transaction detail to cover more fidelity with respect to BPAY payments, particularly in respect to [transactions on business accounts](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/24#issuecomment-557942291). 

Presently it only supports detailed information for Osko payments. Changes raised, include:
* Moving the BPAY information to its own extendedData object and cater more multiple BPAY biller payees
[Change Request 24: Relationship between BPAY fields and transactions is many to one](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/24), and
[Comment to Standards consultation 73](https://github.com/ConsumerDataStandardsAustralia/standards/issues/73#issuecomment-511268647)

* Extending transaction detail to support:
  * Traditional payments such as BSB and Account Number,
  * International payments including routing codes, payment instructions, intermediaries etc.,
  * Extending NPP schema perhaps with a sub-object and NPPuType,
  * Internal Transfers including source/destination account,
  * Generic ISO20022 Payments.

See [Comment to Standards consultation 73](https://github.com/ConsumerDataStandardsAustralia/standards/issues/73#issuecomment-511268647).

* Extend transaction detail to support transaction aggregation and the support for sub-transaction information, particularly for business scenarios.

See [option considerations](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/24#issuecomment-550129041) and comment [here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/24#issuecomment-557942291).

* Normalisation of NPP extended data to the ISO20022 format and extending transaction detail support beyond just the NPP 
  * [Change Request 181: Addition of enums for extensionUType and service in extendedData - BankingTransactionDetail](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/181)
  * Including feedback to CR 181: [comment 1](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/181#issuecomment-674666917) and [comment 2](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/181#issuecomment-868291361).

Data Holders might achieve further utility of the extendedData schema if they could extend it for their own transaction service overlay schemes. These might be based on NPP basic infrastructure, but alternatively, they may be bespoke to the Data Holder’s services: for example, a digital wallet might offer rich extended data within their closed payment system.

## Representation of new service overlays (and versions) in the standards

Service overlays like Osko are represented by service overlay codes and the associated version of service overlay.
e.g. X2P1.01 … X2P1.05
BSCT.01 … BSCT.05
CATSCT.01 
IFTI.01 

Identified Options
------------------

The following changes are proposed to Get Transaction Detail to accommodate the newer versions of the X2P1 service and the additional service overlays identified in this proposal. Two options are presented for how to represent the NPP service overlays.

### Schema representation for new overlay services

**Option 1: Support NPP overlays using a sub-object and NPP overlay union  **

This option extends the current pattern by defining a new payload object for each overlay service and version combination. This has the benefit that each service+version is easily distinguishable and it accounts for changes to the field members. The downside is that this approach results in a high degree of duplication.

In this option, extendedData might be represented as follows:

**Enumerated Values**

| **Property**  | **Value** |
| --- | --- |
| extensionUType  |<ul><li>x2p101Payload</li><li>x2p102Payload</li><li>x2p103Payload</li><li>x2p104Payload</li><li>x2p105Payload</li><li>bsct01Payload </li><li>bsct02Payload </li><li>bsct03Payload </li><li>bsct04Payload </li><li>bsct05Payload </li><li>catsct01Payload </li><li>ifti01Payload</li></ul> |
| service | <ul><li>X2P1.01 … X2P1.05</li><li>BSCT.01 … BSCT.05</li><li>CATSCT.01 </li><li>IFTI.01</li></ul> |

Example
```
"extendedData": {
    "payer": "string",
    "payee": "string",
    "extensionUType": "x2p105Payload",
    "x2p105Payload": {
      "extendedDescription": "string",
      "endToEndId": "string",
      "purposeCode": "string"
    },
    "service": "X2P1.05"
  }
```

With this option, extendedData could also be extended to non-NPP extended data included Data Holder defined extensions.

**Option 2: Change extended data to accommodate an inheritance model with a general structure [DSB RECOMMENDED]**

Rather than introduce a new union object for each NPP service overlay and version, a common extended message format is defined. Whilst the NPP service overlays different in message requirements and purpose, the fields themselves are mostly common across the overlay types. With this option, the fields in the existing x2p101Payload are extracted out into a common nppPayload object which includes:

* Overlay service code
* Overlay service version
* Any specialisations for a specific overlay service as required

The benefit of this option is that is harmonises all NPP overlay services.

In this option, extendedData might be represented as follows:
| **Property**  | **Value** |
| --- | --- |
| extensionUType  | nppPayload |
| service  |<ul><li>X2P1</li><li>BSCT</li><li>CATSCT</li><li>IFTI</li></ul> |
|serviceVersion |ExternalRef -- Version as defined by NPP |

Example
```
"extendedData": {
    "payer": "string",
    "payee": "string",
    "extensionUType": "nppPayload",
    "nppPayload": {
      "extendedDescription": "string",
      "endToEndId": "string",
      "purposeCode": "string"
      "service": "IFTI",
      "serviceVersion": "01"
    }
  }
```

With this option, extendedData could also be extended to non-NPP extended data included Data Holder defined extensions.

### Data Language Standards

No Data Language standards are proposed. Banking transaction data language is currently defined by the Transactions data cluster[[1]](applewebdata://99B24B99-82E3-48E6-8B1E-4E83EB3D2D3B#_ftn1) and is assumed to be general enough in nature to cover the extended transaction data.

Instead it is proposed that transaction data is authorised and disclosed using the existing "bank:transactions:read" scope.

### Non-Functional Requirements

Transaction data is already covered by existing NFR Data Standards. No changes to the existing NFRs are proposed.

### Reporting and Metrics

No changes are proposed for metrics data reporting. It is expected that the changes proposed are sufficiently represented in the existing Get Metrcis v5 payload.

### Error Handling

No changes are proposed for error handling. It is expected that the changes proposed are sufficiently represented by the existing Error Handling codes.

**Comment by markskript** [comment]
Note that in the past 14 days we have seen a SHARP increase in the service code "x2p1.03" being provided in production by one particular data holder. I would suggest that this change request needs to be expedited as that DH is currently (and has been for quite a while now) non-compliant with the standards.

**Comment by markskript** [comment]
Of the options above, Option 2 would be our preference - but our preference is for the quickest resolution based on feedback from Data Holders.

**Comment by CDR-API-Stream** [comment]
**Obligation date**
As discussed in the [MI 21 meeting](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-21:-Agenda-(13-November-2024)) it is proposed that Option 2 be progressed with an FDO of **FY25 # 3 -14th July 2025**.

This change would be a breaking change which would introduce a new V2 version of the [Get Transaction Detail API](https://consumerdatastandardsaustralia.github.io/standards/index.html#cdr-banking-api_get-transaction-detail). 

**Service versions**
It was also discussed that serviceVersion needs to be defined as an ExternalRef rather than an enumerated type to ensure the endpoint is not versioned each time a new service overlay version is introduced to the NPP infrastructure. A Data Holder did raise a consideration regarding lagging compliance if Australian Payments Plus introduced a newer version of any NPP service overlay. This is considered an implementation issue where the Data Standards would remain silent. Data Holders would be required to provide required data in accordance with the CDR rules and could do so in a manner that is inline with any upgrades to their payments systems as new versions are supported. 

**Additional NPP service overlays**
Any new NPP service overlays not defined by this change request proposal would need to go through future change requests and endpoint versions unless the service overlays were also considered External References. At present, option 2 proposes this list is a managed enumerated set of overlays.

**Additional consumer data defined within NPP service overlays**
Further, additional schema extensions for superannuation identifiers and extended payer/payee information shall be progressed in a separate change request for consideration in MI 22.

**Comment by da-banking** [comment]
Hi @nils-work 

Will it be an issue to only provide this information for the additional overlay service codes from the 14 Jul 2025 or are we expected to somehow go back over the last X years of transaction data we have stored and attempt to determine the correct values?

**Comment by nils-work** [comment]
Hi @da-banking 

Can you clarify what you mean by "attempt to determine the correct values"?
Do you mean you will have to derive the historical values in some potentially inaccurate way, you do not have the detail for historical transactions, or they have all previously been shared as `X2P1.01`?

I think the preference would be that if you have the correct values for the required range of historical data, it should be provided to better support consumers, but other options may be to require the detail for transactions made since the [decision](https://github.com/ConsumerDataStandardsAustralia/standards/issues/356#issuecomment-2540453211) date (12 December 2024) or the FDO (14 July 2025).

Other options or feedback from the community would be welcome.

**Comment by da-banking** [comment]
Hi @nils-work 
We don't have the overlay code in our stored historical data, all have previously been shared as X2P1.01

We are making changes to incorporate this moving forward to meet this requirement, however it will only be accurate from our implementation date (expected to be just prior to the FDO)

**Comment by da-banking** [comment]
Hi @nils-work 

Can you please confirm for the historical transactions is it best to mark them as isDetailAvailable=False if the overlay information is not available?

**Comment by nils-work** [comment]
Hi @da-banking 

The **_transactionId_** field description states: 
>... It is mandatory if _isDetailAvailable_ is set to `true`.

The **_isDetailAvailable_** field description states -
> `true` if extended information is available using the transaction detail endpoint. `false` if extended data is not available.

The **Get Transaction Detail** endpoint should return a 404 response (possibly `Invalid Resource` in most cases) if the provided _transactionId_ does not have any _extendedData_ available to be disclosed.

**Comment by da-banking** [comment]
Hi @nils-work 

We have a question with regards to the implementation of this change. Is there a date by which ADRs are supposed to stop calling v1 of Get Transaction Detail?

For example:
ADR calls Get Transaction for Account and returned in there are transactions for the new service overlay codes (BSCT, IFTI & CATSCT).
If we set isDetailavailable = True and the ADR calls v1 of Get Transaction Detail then the structure of what they are receiving would not be as per this change.
As in, it would still have "X2P101Payload" instead of "nppPayload"

Also these additional service overlays are not supported under v1, but we won't know which version of Get Transaction Detail the ADR is going to call when we provide the details of the transacton in Get Transactions for Account.

We would like to enquire how to handle this?

Thanks

**Comment by nils-work** [comment]
Hi @da-banking 

A proposal to set the retirement date is in the current Maintenance Iteration - [#681 - Retirement date for Get Transaction Detail V1](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/681).

I would suggest that the _isDetailAvailable_ field in **Get Transactions for Account** should reflect the availability of any supported overlay/version provided through the newer version of **Get Transaction Detail**.

When **Get Transaction Detail** **v1** is called, it should provide the detail for transactions supported in that version (`X2P1.01`).

If the _transactionId_ passed to **v1** is not of type `X2P1.01` (for example, newer versions supported by v2), the endpoint could return a [404 - Unavailable Resource](https://consumerdatastandardsaustralia.github.io/standards/?examples#error-404-resource-unavailable).

Do other participants have concerns or other views on this approach?

**Comment by da-banking** [comment]
Thanks Nils, that makes it clear and workable
