### ISSUE TITLE
V1.1.0: TLS Certificate from ACCC CA Only?

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#69]
# Request For Clarification
Following release to the Slate site of V1.1.0 yesterday we have now initiated analysis of changes using the diff previously provided in #56.

We note the following added to the header of the OpenID Endpoints section (`slate/source/includes/_security.md.erb`  line 482):

>NOTE: Where an end point in this section requires TLS only the certificate used is to be provisioned by the CDR CA 

This appears to suggest that the marked endpoints (including browser authorise endpoint) must be secured using ACCC CA's rather than a global certificate authority authorised by the Holder.

Is this the intended outcome of this sentence?

**Comment by perlboy** [comment]
Further on this and with reference to https://github.com/ConsumerDataStandardsAustralia/standards/issues/92 the wording specified proposes to require the presentation of a CDR CA TLS for JWKS and OIDC discovery endpoints.

This will make a typical IdP deployment very difficult if the Holder wishes to present a non-CDR CA for end consumer consumption.

**Comment by CDR-API-Stream** [comment]
The implied inclusion of the `authorize` end point was an oversight of the language and was not intended.  This has been added as errata to the release notes for v1.1.0 and will be clarified in a future version.

**Comment by WestpacOpenBanking** [comment]
Westpac believes that the issues which arise from this new requirement must be addressed urgently. This is because if we configure our identity platform in the way suggested, then all customers will experience errors in the authorisation flow.
 
This is because the CDR certificate authority will not, by default, be registered within the root certificate store of any browser or operating system available.
 
Typical error messages that might be expected in the authorisation process are "The site's security certificate is not trusted!" in Google Chrome or "This Connection is Untrusted" in Mozilla Firefox.
 
In addition to the fix described above, Westpac recommends the removal of the new requirement to use an ACCC root CA for TLS endpoints because:
1. It aligned to the relevant standards. While not explicitly stated, the OIDC standard for discovery of open ID provider metadata implies that the OpenID provider metadata endpoint is public. Similarly for jwks_uri.
2. As described in perlboy’s comment, implementing ACCC root CAs for TLS endpoints is difficult, requiring a new domain name for this type of connection. This leads to complexity for data holders and data recipients, both in implementation and because of the flow on impacts of introducing this new domain name. This complexity makes implementation challenging within the time left for.
3. Supporting widely recognised root CAs is the default behaviour for all client libraries. Therefore, this approach will simplify implementation for the majority of data recipients.

**Comment by spikejump** [comment]
Intuit supports both comments made by @perlboy and @WestpacOpenBanking

**Comment by anzbankau** [comment]
ANZ seeks clarity on this topic as a priority, participants will need a clear position for testing and implementation.

**Comment by CDR-API-Stream** [comment]
Clarity has been provided.  The authorize end point is not intended to use the CDR CA root for its TLS certificate and this is stated in the errata.  It will be corrected in the next standards update.

**Comment by commbankoss** [comment]
Thanks for clarification provided for /authorise endpoint. 

Can you please clarify which certificate is proposed to be used for JWKS and OIDC discovery endpoints (Data Holder’s endpoints moved from MTLS to TLS in version 1.1).

**Comment by CDR-API-Stream** [comment]
Currently the standards require that the infosec end points that are TLS must use a certificate from the CDR CA except for the authorize end point

**Comment by CDR-API-Stream** [comment]
If there is no further need for clarity on this topic this issue will be closed.  If there are specific views on how the current, clarified position should be changed, these comments would be welcome on #95

**Comment by cdradr** [comment]
Can someone please clarify what is achieved by using CDR CA for public endpoints?

**Comment by perlboy** [comment]
> Can someone please clarify what is achieved by using CDR CA for public endpoints?

In the context of other decisions there is little value added. The referenced elements in #95 appear to seek to redefine the context in which my comments were given and appear to only reiterate a lack of understanding of public key cryptography.

**Comment by perlboy** [comment]
Closing this issue since there is now a related decision proposal.
