### ISSUE TITLE
V1.1.0 Reintroduction of request_uri and/or Pushed Request Object

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataStandardsAustralia/standards-maintenance#74]
# Description

With the introduction of `existing_refresh_token` and in addition to the concerns raised in #57 the FAPI specification specifically outlines that `request_uri` is suitable for the passing of sensitive data within request objects:

> 7.1 Introduction
>The client may not want to send the request object by value, either because it is too large, or because it contains sensitive data and the client does not want to encrypt the request object. In such cases it is possible to send the request object by reference using a request_uri. 

`request_uri` removal was first specifically noted within the CDS spec analysis conducted by the FAPI WG but was rejected by the Chair with the following statement:

> The removal of the request_uri was deliberate to improve the security profile as it removes the need for a Holder to call an arbitrary external URL.  This was requested by representatives of Australian holders.  The request_uri approach is optional in FAPI (and in the UK Implementor’s Draft) so the strict removal of this as an option is a simplification only.

# Area Affected
Request Object

# Change Proposed

Either:
1. Reintroduce `request_uri` and/or Pushed Request Object support in line with the upstream specifications.
2. Reverse the decision to ship sensitive information within Request Object payloads

**Comment by tlodderstedt** [comment]
Given the CDR standard uses request objects and various scopes and claims, requests will become considerably large, which might cause URL lengths and latency problems. 

I think introducing a facility to let the data recipient push the authorization request in the back channel will facilitate robustness of the protocol. Using request_uri in combination with Pushed Authorization Requests (https://tools.ietf.org/id/draft-lodderstedt-oauth-par) could be a solution.

It would also address the concern that initially caused the removal of request_uri from CDR since the URI would be maintained by the data holder itself.

**Comment by perlboy** [comment]
@tlodderstedt this was responded to by the DSB in the reply letter I have requested to be published in full within #73, and stated the following:

> The removal of the request_uri was deliberate to improve the security profile as it removes the need for a Holder to call an arbitrary external URL. This was requested by representatives of Australian holders. The request_uri approach is optional in FAPI (and in the UK Implementor’s Draft) so the strict removal of this as an option is a simplification only

I assume @anzbankau, @commbankoss, @WestpacOpenBanking or @NationalAustraliaBank can provide commentary as to where the request of "Australian holders" originated from and the reasons for doing so.

**Comment by CDR-API-Stream** [comment]
This has been a topic of active discussion in the DSB and the use of the FAPI Pushed Request Object pattern may potentially address a number of issues from the size of the request object to the issue of confidential data being transferred via the front channel.

This issue is complex and has far reaching implications, however, so may not be best addressed via the maintenance stream.  When the consultation on concurrent consent is opened before the end of the month this thread will be referred to.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 42 open issues within Standards Maintenance. In an effort to optimise our own backlog we are closing those which have no actual response from the DSB. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

1.3.0 introduced Pushed Authorisation Request after concurrent consent was discussed in https://github.com/ConsumerDataStandardsAustralia/standards/issues/99
